### ISSUE TITLE
"checkout" only shows local branches, not remote branches

### ISSUE THREAD

**Issue by maxheld83** [akonwi/git-plus#102]
bug or my mistake/stupidity?

**Comment by jvandyke** [comment]
FYI, in "Git Plus: Menu" there is a "Checkout remote branch" command which works as intended. This isn't available in the standard command set exposed to Atom's default command palette. Perhaps it should be, but it is accessible now.

This is a common case for us using a git-flow type workflow. We need to checkout out branches from other developers to test or help with. Also, we need to checkout release/hotfix branches that others have created.
