### ISSUE TITLE
ignores gitignore file

### ISSUE THREAD

**Issue by bean5** [akonwi/git-plus#106]
I selected "Add All" and it did just that...but not really what I wanted.

**Comment by mpdehaan** [comment]
I'm observing that a file listed in .gitignore still is offered to be added when choosing "Git Plus: Add All and Commit"

.gitignore is properly in the root of the project.

**Comment by bean5** [comment]
Sorry I didn't response @akonwi . It has been a while, but, yes, I had a .gitignore file.

**Comment by akonwi** [comment]
If you have a .gitignore file and run the add all command, though the notification says "added all files", only the non-ignored files will be added. If you try to run the add command on the ignored file specifically, an error will be displayed.

@mpdehaan Can you explain how the file is being offered to be added? The command should just show you a commit message file with the staged/unstaged non-ignored files
