### ISSUE TITLE
Error when trying to push

### ISSUE THREAD

**Issue by gmenih341** [akonwi/git-plus#135]
I'm trying to push via Atom, but I can't get it to work. I've read all the issues that already exist, and none of them helped me.

I'm on Windows 8.1. I have my SSH keys set up correctly, as I can push via git bash, but when I try to push in Atom, I get the following error:

    Permission denied (publickey).
    fatal: Could not read from remote repository.

my GIT_SSH variable is set, and git is in my PATH variable. It's not too much of an issue, as I can simply run git bash to push, but I've been pulling my  hair out over this all day.

**Comment by akonwi** [comment]
I'm sorry to hear that but I'm near clueless about why windows users are having this problem and I can't debug it myself. My best advice if nothing else helped is to refresh your keys and maybe also re-install atom

**Comment by gmenih341** [comment]
Yeah, it's really weird. Some people reported that they got it working eventually, but they didn't explain how, so that doesn't help.

Anyway, I've tried new keys, as well as installing Atom on a different PC. I guess I'll just cope with it and use git bash.

**Comment by akonwi** [comment]
Even on a different PC, you had the same problem?

**Comment by gmenih341** [comment]
Yes, it's the exact same issue on both my PCs.

**Comment by ogdans3** [comment]
Here's what fixed it for me:

My key file names was github_rsa and github_rsa.pub. Changing these names back to the default: id_rsa and id_rsa.pub fixed all the problems!

http://stackoverflow.com/questions/17383177/permission-denied-publickey-errors-on-windows-when-using-moovweb

**Comment by Geelik** [comment]
Thank you for this, it worked for me.

**Comment by timmyLan** [comment]
back to the default key file names ~ It's not work for me :(

**Comment by akonwi** [comment]
@timmyLan If you're on Windows, I can't be much help in debugging the issue. There seem to be a bunch of issues with ssh keys and configs on windows

**Comment by timmyLan** [comment]
I fixed my error...just add my ssh again to my github and it work...lol~~~
