### ISSUE TITLE
Fatal: " is not a valid branch

### ISSUE THREAD

**Issue by acorbi** [akonwi/git-plus#138]
git-plus 4.3.1
OS = OSX 10.10

When trying to create a new branch and after giving the name i get:
<code>Fatal: " is not a valid branch name</code>

Steps to reproduce:
1. CMD+SHIFT+P
2. Type new branch and select "Git Plus: New branch"
3. Input whatever value
4. Press enter

Expected result: A new branch is created and checkedout 
Obtained result: Error message and no new branch

**Comment by mmerian** [comment]
Got the same problem.

My environment :

git-plus 4.3.1
ubuntu-gome 14.10
installed Atom from ppa:webupd8team/atom

**Comment by akonwi** [comment]
I think the new changes in the atom API include changes to the view elements. The views are using the shadowDOM and I can't find documentation on using the new input views. 

I'm going to keep fiddling around and trying to find some answers
