### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by rodurma** [akonwi/git-plus#139]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.172.0
**System**: Mac OS X 10.9.5
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.3.1
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:185

TypeError: path must be a string
  at TypeError (native)
  at fs.exists (fs.js:185:11)
  at Object.fs.exists (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:245:14)
  at /Users/rodrigo/.atom/packages/git-plus/lib/views/branch-list-view.coffee:48:14
  at Workspace.module.exports.Workspace.eachEditor (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:347:9)
  at git.cmd.stdout (/Users/rodrigo/.atom/packages/git-plus/lib/views/branch-list-view.coffee:47:24)
  at exit (/Users/rodrigo/.atom/packages/git-plus/lib/git.coffee:26:7)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```
### Commands

```
     -4:07.6 core:save (atom-text-editor.editor.is-focused)
     -1:17.8 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:17.8 core:cancel (atom-text-editor.editor.is-focused)
     -1:16.4 git-plus:menu (atom-text-editor.editor.is-focused)
  2x -1:10.9 core:move-down (atom-text-editor.editor.mini)
     -1:10.4 core:confirm (atom-text-editor.editor.mini)
  3x -1:07.4 core:backspace (atom-text-editor.editor)
     -1:00.6 core:save-as (atom-text-editor.editor)
     -0:59.1 core:save (atom-text-editor.editor)
     -0:56.2 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:54.0 core:confirm (atom-text-editor.editor.mini)
     -0:11.8 git-plus:menu (atom-text-editor.editor.is-focused)
  4x -0:07.2 core:backspace (atom-text-editor.editor.mini)
     -0:04.6 core:confirm (atom-text-editor.editor.mini)
  2x -0:03.1 core:move-down (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "laravel-theme"
    ]
  },
  "git-plus": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v1.1.0
color-picker, v1.2.6
emmet, v2.3.2
file-icons, v1.4.5
git-plus, v4.3.1
laravel-theme, v0.3.0
project-manager, v1.14.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by akonwi** [comment]
What is the issue here?

**Comment by wenlock** [comment]
@akonwi looks like an auto-reporting thing, but I saw this today as well when trying to checkout master with git-plus, and switching from a feature branch back to master.   Not sure what the root cause or side-effects are for now.  I'm ignoring the error on my side atm.

My checkout seems to be valid and properly switched to master.

**Comment by wenlock** [comment]
I should mention i was on 0.174 with ubuntu 14.04

**Comment by akonwi** [comment]
@wenlock thanks for specifying. I'll keep an eye out for this problem too

**Comment by capaj** [comment]
I had this when I tried to switch branches with git-plus on 0.187.0 on windows 10.

**Comment by tylerFowler** [comment]
Just got this switching branches with git-plus on 0.189.0 on OSX 10.10.2

**Comment by gianpaima** [comment]
I had this when I tried to switch branches with git-plus on 4.5.0 on windows 8.

**Comment by nikmartin** [comment]
Uncaught TypeError: path must be a string
fs.js:207
Hide Stack Trace
TypeError: path must be a string
  at TypeError (native)
  at fs.exists (fs.js:207:11)
  at Object.fs.exists (ATOM_SHELL_ASAR.js:286:16)
  at /home/nmartin/.atom/packages/git-plus/lib/views/branch-list-view.coffee:59:14
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/local/share/atom/resources/app.asar/src/workspace.js:267:9)
  at git.cmd.stderr (/home/nmartin/.atom/packages/git-plus/lib/views/branch-list-view.coffee:58:24)
  at Socket.<anonymous> (/usr/local/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

**Comment by radix** [comment]
I got this while merging master into a branch I was working on.

**Comment by tomalec** [comment]
I got it as well while merging gh-pages into a branch I was working on

**Comment by IamAdamJowett** [comment]
Also got this when switching branches on 5.2.3 on Windows 8.1

**Comment by akonwi** [comment]
I may have to give up on this. I think the root cause is in the `TextEditor` object that atom is returning. It seems to be a bug and for some reason `editor.getPath()` is returning something other than a string in these scenarios. I'll open an issue in the atom repo.

**Comment by jcuenod** [comment]
Don't mean to flog a dead thread but just to note, this issue still exists.
Happened to me while I was merging a branch into a sub-branch.

**Comment by akonwi** [comment]
I've added some logging and attempted to handle this gracefully. If it occurs again, there will be a notification warning you to check the dev console and share what is the logs on this thread.
