### ISSUE TITLE
Remove message about development being done

### ISSUE THREAD

**Issue by Trudko** [akonwi/git-plus#142]
Hi, would you mind to remove the message about development being done? I can create pull request for that.

**Comment by akonwi** [comment]
I've edited it to specify that I won't be developing new features but I will keep handling bugs and issues as best as I can.

Why do you want the message removed?

**Comment by Trudko** [comment]
I am writing article about some Atom packages and I've mentioned yours(I can send you article after I will publish it) and I didn't want to link people to package which description says it's no longer developed so they won't think it's abandoned package.

**Comment by akonwi** [comment]
Oh cool, that's exciting

**Comment by Trudko** [comment]
@akonwi  heh :) I will send you email with the details.
