### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Stanzilla** [akonwi/git-plus#144]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\Benjamin\AppData\Local\atom\app-0.175.0\resources\app\src\atom.js:55:11)
Object.activate (c:\Users\Benjamin\.atom\packages\git-plus\lib\git-plus.coffee:85:9)
```

**Comment by grizzilus** [comment]
This deprecation has been removed in the most recent version.

**Comment by Stanzilla** [comment]
Thanks!
