### ISSUE TITLE
'Search in Directory' becomes broken

### ISSUE THREAD

**Issue by Arlanthir** [akonwi/git-plus#153]
When this plugin is enabled, I can't use atom's 'Search in Directory' feature, the results always come up empty. After disabling only this plugin and restarting atom (or starting atom in safe mode) the results show up again.

**Comment by akonwi** [comment]
Are you referring to the 'Fuzzy Finder: Toggle File Finder' command? This is very odd and I'm not sure how my package can be preventing atom's core features. I haven't come across this and I use this feature a lot. Are you still having this problem? I published a new update today but I'm not sure if that will make much of a difference.

**Comment by Arlanthir** [comment]
I'm sorry for the late reply, this happened in my work computer and I could only test it today.
It was the right-click in folder > Search in Directory, but now it seems all good. Not sure if you fixed it or atom did, but it's behaving now. Thanks!
