### ISSUE TITLE
Using GitRepository slows down atom over time

### ISSUE THREAD

**Issue by grizzilus** [akonwi/git-plus#158]
This package now uses `GitRepository` directly from atom. Each time it is called an instance is created and they are never destroyed. Once this happens a large number of times, atom slows own considerably.

For example, the following steps produce a noticeable lag:
1. Open a git repo project in atom
1. Open a file
1. Activate the git-plus command palette 40 times (just repeatedly press `cmd-shift-h` or the relevant keybinding)
1. Focus a window other than atom
1. Refocus atom  by clicking on a new line on the editor

You will see noticeable lag for the cursor to appear on window focus.

**Comment by Victorystick** [comment]
It is quite severe. When I measured, it took up to 2 seconds for Atom to respond. As you can see it is caused by:

```javascript
77:   if (refreshOnWindowFocus) {
78:     onWindowFocus = (function(_this) {
79:       return function() {
80:         _this.refreshIndex();
81:         return _this.refreshStatus();
82:       };
83:     })(this);
```

![screenshot from 2015-02-17 16 18 49](https://cloud.githubusercontent.com/assets/703602/6230522/d4b6f328-b6c0-11e4-947c-b5bd9a32fd68.png)

**Comment by akonwi** [comment]
Instances of GitRepository were not being destroyed before, now the relevant information is cloned out and the instance is destroyed immediately.
