### ISSUE TITLE
Diff displays Haml lines beginning in '-' as being removed

### ISSUE THREAD

**Issue by EthanML** [akonwi/git-plus#162]
In `.haml` files which contain lines beginning with a hyphen such as variable declarations etc., these lines seem to (at least sometimes) be mistakenly included in the diff as having been removed.

**Comment by akonwi** [comment]
This is difficult to handle in atom. If you use the `word diff` setting, then the defined grammar for the package will look for `-` as deleted lines. If you turn off the word diff setting, then you'll see the traditional line by line deletions.

Unfortunately, at this point I'm not sure there is a way to dynamically change grammars

**Comment by akonwi** [comment]
Diffs are rendered differently now and this should no longer be a problem. I can no longer replicate this issue.
