### ISSUE TITLE
Project.getPath is deprecated.

### ISSUE THREAD

**Issue by anion155** [akonwi/git-plus#179]
Use ::getPaths instead
```
Project.getPath (/usr/share/atom/resources/app/src/project.js:585:12)
dir (/home/anion/.atom/packages/git-plus/lib/git.coffee:147:57)
```

I was trying to init git repo, but than happen this...

**Comment by akonwi** [comment]
Are you running atom in 1.0.0 mode?

**Comment by anion155** [comment]
Sorry, but I don't really understand what are you talking about.

**Comment by akonwi** [comment]
you can start atom in 1.0.0 mode which is a preview of the upcoming 1.0 release. You just need to start atom with the `-1` flag.
