### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by robbens** [akonwi/git-plus#188]
So I recently did a clean install of OS X Yosemite.

Now I **can't push from either Atom or Sublime**. 
Pushing from **terminal works fine**.

When I **open Atom with sudo it works great**. Weird!

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I installed Atom with `brew cask install`

**Comment by akonwi** [comment]
Perhaps installing atom with homebrew is the reason why you need to open it with sudo access. I didn't install atom that way. If the problem persists, one solution is to to alias `atom` with sudo access

**Comment by robbens** [comment]
@akonwi 
Thanks!

But it seems to be a problem with my known_hosts file. It's generation weird shit.

Anyways. There is no issue with git-plus :+1:

**Comment by akonwi** [comment]
Awesome!

**Comment by spyalert01** [comment]
I am having my atom in windows8
I manage to git push using git shell in windows8.
After I install atom, and tried with atom-plus PUSH. It says host key verification failed, invalid remote.... something

Here is my config file for git...

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
[remote "origin"]
	url = ssh://usenrmae@103.99.999.99:5099/volume1/homes/git/git-repos/shoppingcart.git
	fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by spyalert01** [comment]
Do I need to include my ssh private key in Atom? how do I do that if I need to do so?
