### ISSUE TITLE
Nothing to commit

### ISSUE THREAD

**Issue by tokejepsen** [akonwi/git-plus#196]
Getting a "Nothing to commit" message, but Source Tree and other git packages for Atom can pick up the change.

**Comment by akonwi** [comment]
Is this a consistent issue?

**Comment by tokejepsen** [comment]
> Is this a consistent issue?

Its consistent across multiple git repositories.

**Comment by akonwi** [comment]
That's vey interesting. I've created a [new branch](https://github.com/akonwi/git-plus/tree/fix-196) to work on this. I added some code to output some information during the commit command so if you could, clone that repo into `.atom/packages/` and then run `apm install` inside of it. In atom, when you use the commit command, open up the dev console and share what's been logged please. Hopefully that'll help me better understand what's going on

**Comment by tokejepsen** [comment]
How do I copy the console output in the best way? Is there a specific part of it you need?

I did notice something in the console, that it seem to not find the git project?

![capture](https://cloud.githubusercontent.com/assets/1860085/7955757/b50a8228-09d2-11e5-8ffd-28273db4376c.PNG)

**Comment by akonwi** [comment]
Anything from the "git-commit.coffee" file is what I'll need so thanks. 

Yea so the repository object is not connected to the project I think. I've actually been working on an update which might fix this. I'll update the 'fix-196' branch and you can let me know the results

**Comment by tokejepsen** [comment]
It found the project now:) But it hasn't found any files to stage.

![capture](https://cloud.githubusercontent.com/assets/1860085/7978997/560d2b74-0a93-11e5-9d12-205658c463a5.PNG)

**Comment by akonwi** [comment]
This is very strange. Have you staged the files using the `git add` command before running `commit`? If so, then run this in the command line after your files are staged and make sure the output is a list of staged files: `git diff-index --cached HEAD --name-status -z`

**Comment by tokejepsen** [comment]
Ahh, yes. Forgot to add the file, its working now:)

**Comment by akonwi** [comment]
great!

**Comment by cgdeboer** [comment]
I am still seeing this issue. While I can `add` the file then `commit` as a work around. One shouldn't have to add a file that is already tracked. @akonwi , can I provide any more clarity on that?

**Comment by cgdeboer** [comment]
in contrast. `commit all` works perfectly.

**Comment by akonwi** [comment]
@cgdeboer I think it's working as intended. The file may be tracked by git but that's separate from being staged for a commit. `Commit all` works because it does `git add --update` for you to stage the tracked files with unstaged and possibly new changes. Similarly, you can also use `Add all and commit` in this scenario.

Perhaps the term 'add' is a bit of misnomer. The intent behind it is actually 'stage things to be committed'.

**Comment by cgdeboer** [comment]
Thanks for the note. So the command `add and commit` is really what I'm
looking for.


On Fri, Mar 4, 2016 at 9:27 AM, Akonwi Ngoh <notifications@github.com>
wrote:

> @cgdeboer <https://github.com/cgdeboer> I think it's working as intended.
> The file may be tracked by git but that's separate from being staged for a
> commit. Commit all works because it does git add --update for you to
> stage the tracked files with unstaged and possibly new changes. Similarly,
> you can also use Add all and commit in this scenario.
>
> Perhaps the term 'add' is a bit of misnomer. The intent behind it is
> actually 'stage things to be committed'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akonwi/git-plus/issues/196#issuecomment-192301335>.
>



-- 
*Calvin DeBoer*
Director of Trading & Technology
cdeboer@horizoninvestments.com <sfarrow@horizoninvesments.com>

[image: Horizon Investments]

*Horizon Investments*
13024 Ballantyne Corporate Place, Suite 225
Charlotte, North Carolina 28277

*D* 704-919-3608 (Direct)
*O* 704-544-2399 (Office)
*M* 704-564-6640 (Mobile)

www.horizoninvestments.com

[image: View Sean Farrow's LinkedIn profile]
<http://www.linkedin.com/in/seanfarrow>

Confidentiality Notice: This transmittal is a confidential communication.
If you are not the intended recipient, you are hereby notified that you
have received this transmittal in error and that any review, dissemination,
distribution or copying of this transmittal is strictly prohibited. If you
have received this communication in error, please notify this office
immediately by reply or by telephone at the number above and immediately
delete this message and all its attachments, if any. Advice, if any, given
in this email is not intended to be advice concerning tax matters and
cannot be relied upon by a taxpayer for the purpose of avoiding penalties
provided in the Internal Revenue Code.

**Comment by singstar** [comment]
git add --update  that is work for me
