### ISSUE TITLE
Setting for Git Path ignored in OSX Yosemite

### ISSUE THREAD

**Issue by mortiz** [akonwi/git-plus#200]
Hello,

I am experiencing an issue after upgrading to the latest version of git-plus on OSX Yosemite. Upon upgrade of git-plus, my previous Git Path setting (/usr/local/bin/git) was deleted which caused git-plus to use the OSX system git. Git on OSX Yosemite has some known issues. At any rate when I add the setting back, it appears to be ignored. For instance when I try to do a git pull after quitting atom and restarting it, I get the following error:

`/Library/Developer/CommandLineTools/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory`

This indicates that git-plus is still using the OSX system git instead of the git at /usr/local/bin. Other settings appear to work, for instance Message Timeout being set to a higher value causes error messages to stay on the screen longer. This was not an issue under the previous version. 

Thanks,
Mike

**Comment by akonwi** [comment]
That's very weird. No changes have been made related to that setting. Have you tried uninstalling and reinstalling the package?

**Comment by mortiz** [comment]
Agreed. I have tried the following sequence:

- uninstall git-plus
- quit atom
- start atom
- install git-plus
- quit atom
- start atom
- cmd-shift-h, select pull, select origin/master

I get the same error. I noticed that even after uninstalling git-plus that my ~/.atom/config.cson still contains:

```
  "git-plus":
    gitPath: "/usr/local/bin/git"
```

I manually removed that and did the same reinstall sequence as above with identical results.

**Comment by akonwi** [comment]
I just pushed an update. When you run the pull command, open the dev console. There should be output stating the path to git that the package is going to use.

**Comment by akonwi** [comment]
Are you still having this problem?

**Comment by ericychoi** [comment]
Came here to report the same issue; I am using zsh and iterm.  There were a number of threads back in 2014 on the same error message:

https://github.com/atom/atom/issues/3367
http://stackoverflow.com/questions/24022582/osx-10-10-yosemite-beta-on-git-pull-git-sh-setup-no-such-file-or-directory
https://github.com/SublimeGit/SublimeGit/issues/150
But supposedly they should be resolved with the current version of iterm (which is what I am using).

Maybe I am hijacking this thread (if so I can open another one), but the gist is that I am getting
/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory

on git pull.  Any suggestion on how to proceed?  I have not encountered this on sublime or anywhere else.

**Comment by akonwi** [comment]
@ericychoi Yea that issue has been resolved if I'm not mistaken. It's been working for me for a while even in atom. Perhaps you'll need to update Xcode or its command line tools.

**Comment by vkatariya8** [comment]
I've just installed Atom, and I'm facing the same issue. I have the latest version of Xcode, and the same ```git pull``` works on zsh and with the Sublime Git plugin.

**Comment by akonwi** [comment]
@vkatariya8 Can you open up the dev console and look for the message "Git-plus: Using git at [path]" and verify that the path is correct? If not, make sure you've set the correct path in the package settings

**Comment by vkatariya8** [comment]
I updated Xcode CL tools, and it works now.
