### ISSUE TITLE
Is there a Git Plus command equivalent of git commit -a?

### ISSUE THREAD

**Issue by nikmartin** [akonwi/git-plus#201]
On Linux, Git Plus `Add All Commit` adds unstaged files to my commit  - what I'm trying to accomplish is:
> git commit -a: Tell the command to automatically stage files that have been modified and deleted, but new files you have not told git about are not affected.

`Git Plus Add` just adds the current file.
Is there a Git Plus command for that?

**Comment by akonwi** [comment]
There isn't a command for that. You can run it from the Git Run command though

**Comment by ssfrr** [comment]
Seems like a good candidate for a checkbox option:

* [ ] "Add All" adds untracked files

or something. My normal git usage is to `git commit -am"my commit message"` and I generally want to be explicit about when I add a previously-untracked file.

**Comment by akonwi** [comment]
Good call. That can be added as a setting

**Comment by akonwi** [comment]
I've added a new command: `commit -a` which should achieve this.

It stages the modified but unstaged changes before it shows the commit message window. You guys can test it out by cloning this [branch](https://github.com/akonwi/git-plus/tree/add-all)

**Comment by treeder** [comment]
Can we get this rolled into master? Also, could there be an option to replace Cmd-Shift-A P with this?

**Comment by akonwi** [comment]
@treeder Yea I'll publish this today. If you want to bind this to that keymapping you can add this to your personal keymap.cson:

``` coffeescript
'.platform-darwin': // Or .platform-win32
  'cmd-shift-a p': 'git-plus:commit-all'
```
