### ISSUE TITLE
Commands in submodules not working

### ISSUE THREAD

**Issue by phord** [akonwi/git-plus#204]
I see work has been done specifically to address submodules, so I'm not sure what I'm running up against here.

I have a project Foo which has a submodule Bar.  Coincidentally the Bar submodule working directory is in the path 'Foo/Bar'.  My submodule's .git file is a 'git-link' (meaning a regular file which contains a string referring to the actual .git folder location for this repository).  The contents of the .git file are this:

    gitdir: ../.git/modules/Bar

I have some files in Bar like this:

    /home/phord/Foo/Bar/source/some/path/bar.c
    /home/phord/Foo/Bar/source/some/path/bar.h

I started atom like this:

    cd /home/phord/Foo/Bar
    atom source/some/path

Within atom I clicked on bar.c and bar.h to edit the files.

Now, Git-Plus actions on these files do not work.  

Git-Plus: Diff   =>  "Nothing to show"
Git-Plus: Add  =>  fatal: Pathspec 'Bar/source/some/path/bar.c' is in submodule 'Bar'

The error shown for "Add" is the same error I get from git cli if I do this:

    cd /home/phord/Foo
    git add Bar/source/some/path/bar.c

So I think Git-Plus is trying to use Foo as the git repo for these files when it should be using Bar.  I'm not a Coffeescript (or even js) programmer, and I'm not sure how to debug atom.  If you need more info or want me to try something, let me know.

**Comment by akonwi** [comment]
Sorry about that. With the changes I made for the new atom api, I missed a few details regarding submodules

**Comment by phord** [comment]
Thanks for the quick response.  However, this doesn't seem to help.  :-(  I installed the update today to 5.1.1, but I see the same results as before.

**Comment by akonwi** [comment]
Interesting. I have a submoduled project as well and I'm not having issues after the changes I published. I've replicated your scenario and it's working fine. I'll keep tinkering around for a solution though.

**Comment by akonwi** [comment]
I've published a new update. Open the dev console with 'alt-command-i' and when you run a command in the submodule, there will be some info logged to the console. 

It should print out the working directory and the path. Make sure those are correct. If they aren't then something is up.

**Comment by phord** [comment]
I don't know what happened.  It's working fine now. D-:

I saw you pushed another release and I installed and tested it.  Problem went away.  I came here to check on what you did, and all you did is add debug output?  Dang.

I did test it this morning with 5.1.1, and I exited all my atom instances manually and tried again to verify it was still broken.  But now I can't reproduce it using 5.1.2.  Sorry for the extra noise.

**Comment by akonwi** [comment]
haha that is odd. No worries though. I'm glad it's resolved now

**Comment by phord** [comment]
It's back.  Intermittently.  Maybe.

I can't explain it.  It could be related to other packages I have installed.  I'll experiment.

I noticed today that when I tried to 'Git Plus: Add' I was prompted for "Which repo?" and I was shown three choices, one of which was my superproject, but the other two were the projects for other files I had open in Atom at the time.

Another time I was prompted with my superproject name twice, but not my submodule name.

I quit Atom to go add some extra debugging (because in the "not a submodule" case, no debug is emitted), and when I restarted it, the problem was gone.  :-)

**Comment by phord** [comment]
I suspect the issue is related to differences between the Atom "project" and the file in the current window.  When I 'git add' a file, the file must be added to the submodule it is in.  But if I started Atom in some other folder, it seems to suggest a different "project path", I suppose.  

This theory doesn't pan out in my attempts to reproduce it, though.  I noticed "Git Log" shows the wrong log when I try it from different submodules' files.  Maybe worth pursuing, but not as much of a problem as what I was seeing with 'Git Add'.

**Comment by akonwi** [comment]
Ok then. I'll explore this as well and see if I can replicate the issues. 

If you try to run a command while there isn't an active file to edit and you have multiple separate repos as projects, you will be asked which of these repos you want to work with. __This should not be the case if the only repo in the project is the superproject. It should run the commands on the superproject.__ 

If you open atom with the submodule as the root, then you won't be able to execute commands on the superproject.

The `Git Log` is an issue I'll also look into.

**Comment by phord** [comment]
I can replicate some of what I saw before.  Maybe the root cause is my weak understanding of Atom.  In particular I find the "Project Folders" in Atom to be vague and poorly documented, but they seem to be of critical importance to this and other Git-related plugins.  Atom's core git commands do not seem to have the same limitation.

Git-Diff seems to work mostly as expected if the .git directory or any subdirectory of it is one of the "Project Folders".  But if it's not, Git-Diff does not seem to notice and it does not follow the normal git convention of walking up the directory tree for the file to find the first level which contains a .git directory.  

I noticed many other packages have the same or similar issue, including atom/git-diff, atom-minimap/minimap-git-diff.  

But the editor's built-in "Editor: checkout head revision" does not seem to have this problem.

Here's a demo...

Suppose I have a subdirectory named foo, a git repository at foo/bar, and a subdirectory within the repo named baz (whose path is foo/bar/baz).  Inside each directory is a file with the same name but with .txt appended, like foo/foo.txt, foo/bar/bar.txt and foo/bar/baz/baz.txt.

mkdir foo && git init foo/bar && mkdir foo/bar/baz
echo foo > foo/foo.txt
echo bar > foo/bar/bar.txt
echo baz > foo/bar/baz/baz.txt
git -C foo/bar add bar.txt baz/baz.txt
git -C foo/bar commit -m"Initial commit"

Now I open atom to edit foo/foo.txt (which is not in any git repository)
atom foo/foo.txt

In atom's tree view I see "foo" and I see it's subdirectory "bar".  
![screenshot from 2015-06-18 15 24 05](https://cloud.githubusercontent.com/assets/123908/8240154/a1edc47c-15ce-11e5-9dc0-fa2fcfcfa35f.png)

I click on bar to see its contents, then click on bar.txt to open it.
![screenshot from 2015-06-18 15 24 36](https://cloud.githubusercontent.com/assets/123908/8240169/b58dff1a-15ce-11e5-8b9b-10ea6d92b1ce.png)

Notice that the .git dir shows up in this tree view here.  That's unexpected.

From here Git-Plus does not recognize that bar.txt belongs to any git-dir.  The git-plus commands seem to do nothing.  I see "no repos found" in the log.  But if I run 'Editor: checkout' it works as expected.
![screenshot from 2015-06-18 15 41 46](https://cloud.githubusercontent.com/assets/123908/8240426/8c842bf6-15d0-11e5-83c4-c8a658f7dd01.png)

Next I close atom (important) and open it again like this:
atom foo/foo.txt foo/bar/bar.txt
![screenshot from 2015-06-18 15 35 36](https://cloud.githubusercontent.com/assets/123908/8240292/ae167450-15cf-11e5-9428-1de82ed5c417.png)

Now I see a different tree view.  Noticeably, the 'bar' directory shows up as its own project path and it has a different icon (a repo icon?).  Git-Plus recognizes that bar.txt belongs to a repo now, as do git-diff and minimap-git-diff.
![screenshot from 2015-06-18 15 39 16](https://cloud.githubusercontent.com/assets/123908/8240381/34883a32-15d0-11e5-9d97-6d7379882b7f.png)

I usually get into the above situations through a different sequence of operations.  I use the command line a lot and I've been using 'atom' instead of 'vim' lately to edit files.   But if atom is already open, then when I open another file from the commandline it simply opens a new tab in the existing editor instance.  This is fine with me, but it also seems to lead to the same condition where git-plus doesn't recognize my git repos for the subsequent files. 

For example, if I edit a file in some place and then later edit another file in a different place, like this:

    atom foo/foo.txt         # new instance
    atom foo/bar/bar.txt     # new tab in existing instance

Then git-plus doesn't know bar.txt belongs in a repo.

However, if I start with a bar.txt from the beginning (or any files in the same repo):

    atom foo/bar/bar.txt     # new instance
    atom foo/foo.txt         # new tab in existing instance

Then git-plus *does* know bar.txt belongs in a repo.

So, I guess this problem is intrinsic to Atom in some ways.  Or maybe all the packages are using some common library with a misguided idea of how to find the gitdir.

**Comment by akonwi** [comment]
I understand what's going on now. Yea this is sort of an intrinsic aspect of atom. The package used to work with repos on a file by file basis. So if for some reason, you opened a file from another repo inside the current project/repo, then commands would be available for that file in its repository. That was pretty expensive and there wasn't really an elegant way to manage that unfortunately. The use case for that was that atom could only have one root folder.
 
Now atom can have multiple projects opened at the same time and be treated separately. If your `foo` directory isn't a repository and there are subdirectories which are repositories, then you can open atom with:
``` bash
atom */
```
and each subdirectory will be a project and 'foo' shouldn't appear in the tree-view.

**Comment by phord** [comment]
So, is the _real_ problem that Atom doesn't automatically open the containing projects for each opened file?  Maybe there's another package for that, if only in the future.

**Comment by akonwi** [comment]
Yea I would say that's the problem.

**Comment by phord** [comment]
Open issue at the atom level: atom/atom#2203
