### ISSUE TITLE
Commit closes active file

### ISSUE THREAD

**Issue by filipesilva** [akonwi/git-plus#209]
Whenever I do a commit (I usually do CTRL+A A to add all and commit), after I save the commit message both the commit file and my previously active file are closed. 

This has always happened to me since I've used this package (since the beginning of the year I think) but only know did I think of reporting it. Currently I am on windows 8 and atom 0.209.0, but it also happened in windows 7 and across all versions of atom.

**Comment by akonwi** [comment]
Has this been happening in the most recent versions of the package?

**Comment by filipesilva** [comment]
It seems to only happen sometimes. Right now, I had 3 files opened, first file active, did `add all and commit`, entered message and save. Message and previously active tab were closed.

Afterwards I had only one tab open, same sequence of events, but it did not close.

**Comment by laughedelic** [comment]
I have the same issue

**Comment by ndland** [comment]
I am running into the same issue.

**Comment by cakenggt** [comment]
I am also having this issue.

**Comment by cakenggt** [comment]
This bug has disappeared for me after updating atom to the latest version (1.0.3).

**Comment by akonwi** [comment]
@filipesilva Is this still an issue for anyone?

**Comment by filipesilva** [comment]
I just got it myself. Let me get back to you in a few days of usage to make sure it wasn't a fluke.

**Comment by filipesilva** [comment]
Ok after a few days working with it, I can verify the problems still happen (double commits windows, closing current window) roughly with the same frequency.

This is on a clean install on a win10 machine now.

**Comment by jagged3dge** [comment]
Confirming that saving a commit message window closes active file tab. Issue still exists.

**Comment by cakenggt** [comment]
I confirm also on Atom version 1.0.5 . The bug where it closed the active tab had disappeared until this version.

**Comment by akonwi** [comment]
Can someone share with me a video or gif so I can get the context around this? I think it'd be really helpful

**Comment by jagged3dge** [comment]
![test2](https://cloud.githubusercontent.com/assets/3892333/9262310/93bad400-4231-11e5-9729-5ce6f85ce42f.gif)

**Comment by filipesilva** [comment]
Oh man this is great! Thanks :D
