### ISSUE TITLE
Could not create status list error

### ISSUE THREAD

**Issue by entrocode** [akonwi/git-plus#21]
Setup:  mac and github for mac (https://mac.github.com/) along with Atom (obviously).  

When I "add all" and then "commit" (and uncomment the appropriate changes) using git-plus the commit pops up in github for mac.  In github for mac, when I click the sync or sync branches buttons it USUALLY pops up with a message that says "Could not create status list".  If I click "Edit" next to the unsynced commit, no files show up as having changed.

Weird thing is... if I try this a few times it does eventually work.  I have been unable to notice a pattern.

Am I doing something wrong?

**Comment by sunil592002** [comment]
Not able to fix this issue. I have created a back up of old repo and cloned it again and copied the files changed on my old repo to the newly created one.

This might be a bad idea :( but not get time to look into the issue

**Comment by hcinko5** [comment]
In my case it was cause because a very long path (more than 15 nested folders). Deleting the long path solved the problem.
