### ISSUE TITLE
Commands run twice

### ISSUE THREAD

**Issue by filipesilva** [akonwi/git-plus#213]
Some commands seem to be running twice, I think. I say this because of two things that happen:

-`Add all and commit` shows a message about index.lock, which I suppose is the second one failing.
![image](https://cloud.githubusercontent.com/assets/4172079/8278833/817eed74-18c6-11e5-9478-306170dbd26f.png)

-Some commands, sometimes, open two windows. This, for example, was the same `Add all and commit`, without me finishing the previous one. It does not happen consistently. Some 15m before this happened on a git commit --amend and I think it ended up amending two commits back (that or I messed up my repo some other way).
![image](https://cloud.githubusercontent.com/assets/4172079/8278863/caa2a252-18c6-11e5-8272-7994de67197d.png)

I suspect that somewhere two commands are ran at the some time, and sometimes they both run, sometimes one hits the lock. I don't know if this is related, but my shortcuts seem to have duplicated buttons?
![image](https://cloud.githubusercontent.com/assets/4172079/8278896/2173513a-18c7-11e5-933f-7c1c15b63de7.png)

**Comment by akonwi** [comment]
The shortcuts are different. I'm puzzled about why commands may be running twice and why after commits, the active file gets closed

**Comment by filipesilva** [comment]
I'm sorry, I didn't mean that those entries had the same shortcut, I meant that each of them shows it's shortcut twice. Is that intended?

Is there any more information I can give you regarding this issue? It would seem #97 is related, and if I had to bet #209 might also be (if two commands are running, it might be that saving the commit pane triggers two closes?).

**Comment by akonwi** [comment]
No that's not intended. That's an atom bug then. That's not the case for me on my mac. 

I think you're right though about the index.lock being related. The next step I'll take will be to delete that and we'll see if that solves the problem.

**Comment by akonwi** [comment]
I've created a new branch called 'index'. Could you clone that and test it for me?

**Comment by filipesilva** [comment]
I deleted the existing package, cloned the repo into `.atom/dev/packages`, checked out the `index` branch, ran `apm link`, and then loaded atom.

Created a new repo, added a few files, did a couple of commits and amends. Did not see the .lock message, did not have active file closed, and shortcuts did not display twice. I checked the reflog as mentioned in #214 and I did not find repeats `reset: moving to HEAD^`.

It looks like it was fixed as far as I can tell. Good job!

**Comment by akonwi** [comment]
Great! I'll give it a few days before I publish those changes just in case you run into something else.

**Comment by filipesilva** [comment]
Ah, I still seem to have files being closed on me. Just happened :/

**Comment by adamalbrecht** [comment]
+1 I'm seeing this issue as well.

**Comment by tpoisot** [comment]
:+1: me too (Atom 1.0.7 on Fedora 22)

**Comment by filipesilva** [comment]
It's been a while since I've had the problem myself. I think the last git plus patch fixed it for me.

@tpoisot what's the shortcut for the git plus command palette? I've only ever used the atom command palette.

**Comment by tpoisot** [comment]
@filipesilva Shift-Ctrl-H

**Comment by akonwi** [comment]
Is this still an issue?

**Comment by filipesilva** [comment]
I still have it, but it's very very rare. Once every 50 commits maybe? It's extremely hard to reproduce. @tpoisot, do you still get it?

**Comment by jcuenod** [comment]
I'm getting this issue on Antergos: Atom 1.7.4 with Git-plus 0.7.1

**Comment by jcuenod** [comment]
Okay, I fixed it by uninstalling gitplus, restarting atom and reinstalling.

**Comment by robrecord** [comment]
I am getting this. Will try the fix.
