### ISSUE TITLE
'commit amend' fails and resets to wrong location

### ISSUE THREAD

**Issue by phord** [akonwi/git-plus#214]
In the command-line I amended a commit (successfully) while on a detached head.  I realized I needed another change added, so I made the change and used Git-Plus to add the file. Then I used Git-Plus to amend the previous commit.

Git-Plus opened the commit message in a new buffer but it immediately reported an error:

    Git-Plus
    : Commit amend aborted!

It then reset my head to the wrong previous location (ORIG_HEAD, but it was wrong because of the series of resets Git-Plus performed; see below).

When I eventually cancelled the amend by closing the left-open commit message tab, Git-Plus reset my head again to a new (wrong) location.  Then it again reported the "amend aborted!" error.

    Git-Plus
    : Commit amend aborted!

Here's the output from 'git reflog --relative-date' showing the commit I successfully amended from the commandline and then the subsequent resets performed by Git-Plus.  The most recent reset occurred after I closed the (already aborted) commit message tab.  The previous 5 resets occurred immediately when I tried the "Git Plus: Commit amend".

    37ac942 HEAD@{12 seconds ago}: reset: moving to ORIG_HEAD
    59f6d6d HEAD@{41 seconds ago}: reset: moving to ORIG_HEAD
    37ac942 HEAD@{41 seconds ago}: reset: moving to ORIG_HEAD
    59f6d6d HEAD@{42 seconds ago}: reset: moving to HEAD^
    37ac942 HEAD@{42 seconds ago}: reset: moving to HEAD^
    5be67c5 HEAD@{42 seconds ago}: reset: moving to HEAD^
    4376c78 HEAD@{3 minutes ago}: commit (amend): OemConfig: Expand "keys" to 16-bits

I do not have any idea why the 'commit amend' failed, nor why Git-Plus tried to reset to HEAD^ three times (effectively resetting to HEAD^^^).

Maybe this is related to #213.  If so, maybe Git-Plus is running the amend command three times; this would explain why two of them are failing with the reported error, though I don't know what happens to the third.  I do not see three reported "aborted!" error messages.  

Also when I close the commit message tab, one of my open file tabs is also closed.  I had about 10 files opened when I ran into this.  After trying to reproduce it several times, I noticed all my files had been closed.  It seems they were closed one at a time as I ran each test.  This is likely a separate issue already reported in #209.  But I mention it here in case it is important.

Some notes on my conditions:

Here's my current log when I tried this (for correlation with my reflog above):

    4376c78 - (HEAD)
    5be67c5 - (HEAD^^)
    37ac942 - (HEAD^^^)
    59f6d6d - (HEAD^^^^)
    75496f0 - (HEAD^^^^^)

I am on a detached head (no branch label checked out).

I initially had three project folders open (Ctrl+Alt+O).  I thought this might be related to the three resets performed, but I removed two of the project folders and tried it again and the same (three) resets pattern occurred.

**Comment by akonwi** [comment]
Right now the implementation resets to head in order to get the previously staged files to recreate the commit file. A quick fix is to not reset but that means the new commit file won't have those details. I'm going to work on backing up those details and then you can give it a test and tell me how you feel about it

**Comment by akonwi** [comment]
I've pushed a new branch, [amend](https://github.com/akonwi/git-plus/tree/amend) with the hopeful fix. Clone that and replace the `git-plus` directory in `.atom/packages` and let me know what you think.
