### ISSUE TITLE
Stash stack

### ISSUE THREAD

**Issue by tsm91** [akonwi/git-plus#218]
Hello, is there any chance to implement stash stack? Right now i cant specify which stash do i want to take, it  will always operate with the top most one.

ping @Zren

**Comment by Zren** [comment]
Sublime's Git plugin handles this like so:

Stash Apply/Drop will `git stash list` first, then if there's more than one it will create a fuzzy search box.

![](http://i.imgur.com/KEdRSco.png)

Stash Pop always grabs the top. So no changes there.

**Comment by Zren** [comment]
It could probably be implemented similar to git branch:

* https://github.com/akonwi/git-plus/blob/master/lib/models/git-branch.coffee
* https://github.com/akonwi/git-plus/blob/master/lib/views/branch-list-view.coffee

Also here's the source code for the sublime implementation.

https://github.com/kemayo/sublime-text-git/blob/master/stash.py

**Comment by tsm91** [comment]
Im totally new to atom, and never really used sublime, on top of that i also unfamiliar with coffee script :d

For now I rather pass this implementation process, would take at least a day to get up and running, but this is the exact behavior I imagined.

**Comment by niobium0** [comment]
I'm using stashing extensively. `Ctrl+Shift+P; "stash pop"` is very much worthless to me as I always inspect whether I'm popping the correct thing. My routine is:
1) `Ctrl+Shift+P; "stash list"` (custom command)
2) `Ctrl+Shift+P; "Git Plus Run"; "stash pop {0,1,2,3...}"`.

I'd very much prefer that stock `stash pop` would do a `stash list` and present options as a select-list.

**Comment by akonwi** [comment]
I'm going to work on this next...3 years later haha

**Comment by akonwi** [comment]
Just pushed v7.12.0 with a new command `Manage Stashes`. The behavior is similar to the `Tags` command

**Comment by arborrow** [comment]
I feel like I am missing something but am not able to find the Manage Stashes command. Should it be in the menu? I'm able to use run but I would like to understand how to make use of this functionality. Thanks in advance for any explanation about how to access Manage Stashes. 
![Screenshot from 2021-12-13 21-30-50](https://user-images.githubusercontent.com/532371/145916401-b30a8bcc-778d-4798-aea3-0b68f2235d37.png)
