### ISSUE TITLE
Doesn't work push, pull on windows, but add, commit works.

### ISSUE THREAD

**Issue by talgatbaltasov** [akonwi/git-plus#219]
It adds and commits fine, but it doesn't pull and push. 
i have user.name and user.email at git global.

**Comment by movingSone** [comment]
Is there a way to detect this same error? I am having the same issues, though  I can push the files with same changes through command line.

**Comment by akonwi** [comment]
Is there an error notification? Or perhaps some feedback from the developer console?

**Comment by talgatbaltasov** [comment]
@akonwi no, there is no error notification or some feedback

**Comment by DSigmund** [comment]
+1 does not work here to

**Comment by GaetanBt** [comment]
Doesn't work here too !

**Comment by rossfenrick** [comment]
+1 doesn't work

**Comment by movingSone** [comment]
I was checking the coffee scripts inside, does Git Push only supports remote link for repositories? 

Didn't get any error, just success that it was added successfully. After that I went to console and pushed it, though I had to enter username and password.

**Comment by pcan** [comment]
+1

**Comment by akonwi** [comment]
Are all of you using windows?

**Comment by TZanke** [comment]
Git push error:

fatal: could not read Username for 'http://....': No such device or address

user.name is set in global and local gitconfig via 'git config (--global) user.name "Name" '

Ubuntu 14.04 LTS
ATOM 1.0.3
Git-Plus 5.3.3

**Comment by tkipf** [comment]
+1 doesn't work (OS: Mac OSX, otherwise same config as TZanke)

**Comment by joncombe** [comment]
I added a comment to ticket #224 which may help some users.

**Comment by anderflash** [comment]
```bash
fatal: could not read 'Password' for 'https://....': No such device or address
```

+1 doesn't work(Linux manjaro 3.19.8.4-1-MANJARO SMP PREEMPT Wed Jul 22 07:08:31 UTC 2015 x86_64 GNU/Linux)

**Comment by PBartrina** [comment]
@anderflash Due to workplace firewall configuration, I can only do git operations via https. So it doesn't quite solve the password problem for me. 
Thank you for the help, though

**Comment by mloskot** [comment]
This is bug report about Windows environment, so not sure why folks submitting Linux-related experiences.

Anyhow, on Windows 8.1 Pro as well as Windows 10, with latest Atom 1.1.0 and packages up-to-date, here is what I'm geting on attempt to Git Plus > Push:

![git-plus-win8-push-error](https://cloud.githubusercontent.com/assets/80741/11129024/7e779310-897d-11e5-8023-0c0a3227f830.png)

I do not use SSH key authenticacion, but password only.
If I switch to MinGW/MSYS shell command line, I can `git push` and I'm getting dialog box prompting me for password. All works there.

**Comment by akonwi** [comment]
@mloskot Right now the package favors an ssh setup and doesn't expect to be prompted for credentials. I suggest looking into the [git credential store](https://git-scm.com/docs/git-credential-store) if you're not using ssh

**Comment by mloskot** [comment]
@akonwi That is OK. It's just, this caveat is not mentioned anywhere on https://atom.io/packages/git-plus May be good to explain it and avoid flood of similar bug reports. Thanks.

**Comment by akonwi** [comment]
@Arekusei The git credential store is bad? 

@mloskot That's a good point. I'll make the change

**Comment by Wintercypher** [comment]
@akonwi 
I was able to fix my problem. Simple solution as well. 
Once I copied my name and email from my global config and duplicated it in the local config, I was able to push pull etc without issue.

**Comment by akonwi** [comment]
I'm closing this issue because the package favors repositories that have ssh setup without a passcode for remote repository interactions and I've added that in the README.

For solutions to removing the dependency on the passcode, see https://github.com/akonwi/git-plus/issues/224, which may also include help regarding the proper configurations for windows machines.

**Comment by mads839** [comment]
My operating  system is  windows .push command is not working.showing no error but cloud repository is not updating ...I think some issue in system kindly help

**Comment by asdrubal1107** [comment]
I have an error when pushing in windows, it does not generate an error, but it does not update me in the cloud either, I would like to be more specific but in the console it does not generate any type of error, I have consulted, I think it is problems with the system, please help.
