### ISSUE TITLE
All git-plus command is not recognized

### ISSUE THREAD

**Issue by primAulia** [akonwi/git-plus#221]
Hi there,

I tried to install the plugins and call the command. It returns me this error.

> 'git' is not recognized as an internal or external command,
operable program or batch file.

I've added the executable path of git into the PATH variables, but it still can't work. Advice please?

**Comment by movingSone** [comment]
Can you check how did you add it? Did you add  ;  divider between the paths?

**Comment by primAulia** [comment]
Apparently my git installation is corrupted. I reinstall and everything works now.
