### ISSUE TITLE
Can't change add to a git repo inside a path ignored by parent .gitignore

### ISSUE THREAD

**Issue by terala** [akonwi/git-plus#225]
I have a git repo at my home, with holds my settings and ignores everything else using .gitignore. All my sources are in ~/src, which are ignored in .gitignore. When I have other repos in ~/src, I can't add a file in any repos in ~/src folder. It keeps throwing error that the file is ignored by .gitignore. How do I get git-plus to recognize the repo the file belongs to?

**Comment by akonwi** [comment]
Are you trying to stage files in repos that are inside ~/src? If so, make sure you open those repos as projects in atom.

**Comment by terala** [comment]
Yes. My gut repo is in ~ and ~/src is ignored. I do have other repos under
src, but they are not recognized at all whether I open them as projects or
not. It is defaulting to ~ and does not show any pending changes.

**Comment by akonwi** [comment]
what do the .gitignore files look like?

**Comment by terala** [comment]
```
# Ignore everything 
**

# Do not ignore these.
!.gitignore
!.bashrc
!.bash_profile
!.inputrc
!.vimrc
!/.vim/
!/.ssh/
!/.fonts/

/.ssh/known_hosts
```
This is what I have.

**Comment by akonwi** [comment]
Sorry I dropped off this issue. Can you verify this is still a problem for you? I just tried to replicate it and I'm not seeing it. 

If I open atom with `atom ~/` then only the unignored files are in the project. If i open atom with `atom [something ignored]`, everything still works fine.
