### ISSUE TITLE
git commit --verbose

### ISSUE THREAD

**Issue by neumannrf** [akonwi/git-plus#227]
I would like to enable verbosity on my commit messages without having to go through "Git Plus: Run". I see 2 ways of doing this:

1) Add a checkbox on the git-plus Settings page that says "Enable verbose commit messages" and modify the "Git Plus: Commit" command to add "--verbose" according to the checkbox.
2) Create another command "Git Plus: Commit (verbose)" that contains the "--verbose" by default.

If this is not in your plans already, how one could go about adding this functionality? What files would I have to edit / create?

Thanks!

**Comment by akonwi** [comment]
This has been raised before at #90.

In order to implement it, you'll need to change `lib/models/git-commit.coffee`. This means get the diffs and add them to the the commit file
