### ISSUE TITLE
No keyboard shortcut to stage files.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [akonwi/git-plus#231]
Hello

When staging files, you can select the files you wish to stage using the keyboard, but you can't confirm the dialog (the green button) with any keyboard shortcut (unless, of course, there is some shortcut I'm missing). This breaks the keyboard workflow as you need the mouse to press the button. Escape and tab seem to both cancel the dialog. Perhaps Control+Enter or Control+S (or both) or something would be a good choice?

Thanks in advance

**Comment by JeanMertz** [comment]
Having the same issue :+1: Haven't found a shortcut for that action yet.

**Comment by akonwi** [comment]
I've added `Shift-Enter` as the shortcut to confirm
