### ISSUE TITLE
Can't open menu when no file is open.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [akonwi/git-plus#232]
Hello

When no file is open in the currently active pane (e.g. when closing the last opened file), you can no longer open the git plus menu. This may be intentional as it requires a file for some commands. Perhaps it would be interesting if it falls back to the (first?) currently opened project, disabling options that are specific to the current file?

Thanks in advance

**Comment by akonwi** [comment]
Cmd-shift-H opens up the menu. Or even the `Git-plus: Menu` option in atom's command palette

**Comment by hotoiledgoblinsack** [comment]
Doh, you can close this issue, this was due to a manual keybinding that was only active in the editor class rather than the workspace. My apologies.

**Comment by akonwi** [comment]
haha no worries
