### ISSUE TITLE
Specifying an empty value for 'git show' generates an error.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [akonwi/git-plus#234]
Hello

When just pressing the return key to confirm the 'git show' input dialog without entering any value, the following error is generated:

```
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
git <command> [<revision>...] -- [<file>...]'
```

EDIT: This may not be entirely incorrect, as entering a non-existent revision generates the same error, perhaps the dialog should just be cancelled for an empty value?

Thanks in advance

**Comment by akonwi** [comment]
That error is git's response to an invalid entry. I think it should be shown since it would be the same as if you ran it manually in the command line
