### ISSUE TITLE
Commit Pane is too eager

### ISSUE THREAD

**Issue by jsg2021** [akonwi/git-plus#235]
I have auto-save turned on in atom, so when a pane blurs it saves.  Git Plus's commit edit view closes and continues on save... this has bitten me several times.  

Can we get an option to only continue the commit if-and-only-if:
- I close the pane. 
- or I manually invoke the save key strokes
- or use a new non-editor like git-control
- or ignore auto-save for the commit editor

**Comment by radamant** [comment]
@jsg2021 I had this happen to me recently. I attempted to disable autosave in git commit buffers with the following:

```cson
"*[data-grammar~=\"git-commit\"]":
  autosave:
    enabled: false
```

but that seemed not to do the trick. Any ideas how to disable auto save when in a git-commit window?

**Comment by jsg2021** [comment]
I don't know, that looks like something that should work. Will see what the atom team says. :)

**Comment by akonwi** [comment]
I've turned autosave on but I'm not having this problem. I'm changing tabs, toggling into the tree-view, and just about everything else while the commit message is open but it's still there until I save or close it.

**Comment by jsg2021** [comment]
@akonwi do you have a message typed? if its the initial content, its okay.

**Comment by akonwi** [comment]
Ah I see. I'll try to make time and create a pull request to the autosave package to allow some configuration or a service for external packages to use. Hopefully the atom team beats me to it

**Comment by akonwi** [comment]
It doesn't seem like the autosave maintainers are going to accept my pull request or address the issue. I'm not sure what more to do and this is over a year old.

**Comment by akonwi** [comment]
My pull request to the autosave package has been merged and published. The changes to fix this issue will be in the next release

**Comment by jsg2021** [comment]
:) 👍
