### ISSUE TITLE
Issue with comments in MySQL files

### ISSUE THREAD

**Issue by dorian-marchal** [akonwi/git-plus#237]
In MySQL files, comments are colored in red (the  start-comment sequence is `--` in MySQL) : 

![diff](https://cloud.githubusercontent.com/assets/6225979/8645450/d3901732-2947-11e5-8d54-7ff4a571e1ba.png)

**Comment by akonwi** [comment]
I'm unable to replicate this

**Comment by radix** [comment]
I'm getting this with my Haskell files (also uses `--` as a comment) as well as `.md` files where I use `-` as a bullet point.

**Comment by akonwi** [comment]
This is a tough problem. The syntax highlighting is done with regex and I don't know an expression that can identify an actual deleted line marker.

**Comment by akonwi** [comment]
Diff rendering has been re-written in a way that fixes this problem. I can no longer reproduce it.
