### ISSUE TITLE
Better (configurable?) support for git aliases

### ISSUE THREAD

**Issue by Ajedi32** [akonwi/git-plus#239]
I have quite a few git aliases I use frequently with command line git. It would be nice if I could access those more easily from atom. Currently I can use git-plus:run, but it would be great if I could somehow add the commands directly to the top-level Atom command palette. (Whether automatically, or with some amount of configuration required on my part beforehand.)

**Comment by akonwi** [comment]
If you want to use your aliases in the `Run` command, then add those aliases to your .bash_profile because the commands run in a child process of bash I think

**Comment by Ajedi32** [comment]
Sorry, I meant git aliases, not bash aliases. (I'll edit to make that more clear.) As I stated, I can already access them from Run, but that requires an additional step when compared to the native git commands. This feature request is for better support for aliases, such that I am able to access them from the top level command palette, just like the native git commands.

**Comment by akonwi** [comment]
Can you a couple of examples of aliases you'd like to have in the command palette?

**Comment by Ajedi32** [comment]
I store my personal aliases on GitHub: https://github.com/Ajedi32/git_aliases

So from that list, I'd probably want `temp`, `pop`, `mb`, `recommit`, `fa`, etc (the full list is under `aliases/` in that project). Aliases are usually set up differently for everyone though, so if this does become a feature it would have to be pretty flexible.

**Comment by akonwi** [comment]
That seems awfully complicated and difficult because it would be catering to users individually. Something you could do, which is what I do is set up your own keymappings to the different commands and those mappings can reflect your aliases.

An example I'd use:
> '; g a': 'git-plus:add'
> '; p o p': 'git-plus:reset'

I use the semi-colon as a leader that way I can type my alias afterwards

**Comment by Ajedi32** [comment]
Yeah, that was why I said "configurable". Unfortunately, many of the aliases I use aren't _just_ shortened forms of git commands; they often come with arguments tacked on. For example, `git pop` is `git reset HEAD~`.

Again, I'm not all that familiar with Atom's API, so I have no idea whether this is possible or not, but the way I was envisioning it was some sort of option in the settings page that lets you choose existing aliases from a list (`git config --get-regexp ^alias\.` will give you a listing on the command line), and maybe specify what kind of arguments they take, then adds those commands to the atom command palette. Of course, it's up to you whether this is something you think this is something `git-plus` could potentially support.

**Comment by akonwi** [comment]
I'm sorry I forgot about this thread for so long. Though I think this is possible, it's not something I'll prioritize but I do want to look into it.

**Comment by akonwi** [comment]
I've just published a new version with a feature that allows users to define their own commonly used commands locally. It's an experimental feature right now and I would love if you gave it a try and provided feedback. I think at least some of your aliases are good candidates for these.

You can read about it here

**Comment by Ajedi32** [comment]
Yeah, sorry I haven't gotten a chance to try it out. Most of my development lately has been in an environment where I'm using an IDE, so I haven't been doing a whole lot with Atom lately. Once my focus shifts back to the projects that I'm using Atom with I'll definitely check this out.
