### ISSUE TITLE
Git Plus: Status not working

### ISSUE THREAD

**Issue by cakenggt** [akonwi/git-plus#240]
When I try to run `Git Plus: Status` either from the command palette (selecting it from the palette when I search for it) or from the keyboard shortcut, a dialog comes up at the top of the screen and says 'No matches found' with a blinking text box, the same as if I typed in a nonsense command into the palette. When I attempt to type into the blinking text box, nothing pops up or anything, giving me no context as to what is creating the dialog.

I am able to commit, add, push, all that stuff using git plus from the file that I execute the status from.

**Comment by akonwi** [comment]
Do you have changes that should be displayed when you run the status command? The nothing to show is meant to indicate no changes have been made.

**Comment by cakenggt** [comment]
It seems as though I do get things showing up when I have changes that should be displayed. Thank you for your help!
