### ISSUE TITLE
clicking git add in an atom settings dialog has bad unintended consequences

### ISSUE THREAD

**Issue by nikmartin** [akonwi/git-plus#243]
I have atom open and the project view open with a root folder of a git project displayed. I went into atom's settings view and was going to add a file pattern to the 'Ignored Names' input field, and somehow ended up clicking 'Git add' in the context menu by mistake. I canceled the context menu and pasted the string I was trying to paste in there, and about 3 minutes later, a confirmation notice popped saying 'git add succeeded'. I panicked and went out and did a git status, and sure enough, every file and folder from the root down had been added. luckily, my working tree was in a state that git reset undid the add without affecting any other of my working set.

Git-plus should not be active on a non project file related dialog/tab

**Comment by akonwi** [comment]
The next update will have this fixed.
