### ISSUE TITLE
Provide a service for other packages

### ISSUE THREAD

**Issue by olmokramer** [akonwi/git-plus#245]
It would be awesome if you could provide a service for other packages to consume. Would be very useful for packages implementing a git user interface ([I'm working on one](https://atom.io/packages/tree-view-git-branch) myself right now, so that's why . That way those packages don't have to worry about their git implementations and this one doesn't have to worry about UI :) Any chance you will consider this?

**Comment by akonwi** [comment]
This is a great idea. I've been thinking about how to make parts of this package useful for others. This will  be a priority.

**Comment by akonwi** [comment]
What kind of API are you hoping for with the service? Are there specific methods you'd like exposed?

At the moment, most commands are run with `gitCmd` and this is it's method signature:

``` coffeescript
# Public: Execute a git command.
#
# options - An {Object} with the following keys:
#   :args    - The {Array} containing the arguments to pass.
#   :cwd  - Current working directory as {String}.
#   :options - The {Object} with options to pass.
#   :stdout  - The {Function} to pass the stdout to.
#   :exit    - The {Function} to pass the exit code to.
#
# Returns nothing.
gitCmd = ({args, cwd, options, stdout, stderr, exit}={}) ->
```

What I'm not super pleased with is that there are a lot of callbacks with this technique. I want to move to promises instead which will be better for external use

**Comment by olmokramer** [comment]
Thanks for the reply! I was thinking just the same functions as the commands git-plus provides. So package authors could do for example

```coffee
module.exports = MyAwesomePackage =
  // ...

  consumeGitPlus: (@gitPlus) ->

  // commit the current file
  commit: ->
    @gitPlus.commit()
```

And for my own package I could really use a function to checkout branches. I can do that in a PR sometime soon if that's ok :)

**Comment by akonwi** [comment]
That sounds great! I really like this idea

**Comment by olmokramer** [comment]
Awesome! Can't wait to see this implemented :-)

**Comment by akonwi** [comment]
I've just pushed a new branch called 'service' with a bit of implementation. You can clone that and give it a run.

`package.json` should look like:

``` json
"consumedServices": {
  "git-plus": {
    "versions": {
      "1.0.0": "consumeGitPlus"
    }
  }
}
```

Usage

``` coffeescript
consumeGitPlus: (GitPlus) ->
  GitPlus.getRepo().then (repo) ->
    GitPlus.commit repo
    GitPlus.checkoutNewBranch repo
    GitPlus.checkoutBranch repo
```

You don't need to use the `::getRepo` method if you already have a specific repository object. But you must pass that `repo` to the commands

**Comment by olmokramer** [comment]
Thanks! Looks good and easy to use.
I may send some PRs when I get some time to work on my package and feel there's something missing :)
