### ISSUE TITLE
Windows can't commit two times 

### ISSUE THREAD

**Issue by heartshare** [akonwi/git-plus#252]
After save the commit and push to the master 
COMMIT_EDITMSG seem lock and show permission problem and can't commit second time until close the atom editor and recommit again ok

use mysysgit try : fatal: could not open '.git/COMMIT_EDITMSG': Permission denied

Windows 7

**Comment by akonwi** [comment]
I just pushed an update. Check it out and let me know if the issue is fixed

**Comment by heartshare** [comment]
fixed after updated  thanks
