### ISSUE TITLE
double tab somtimes opens on private repo add all commit push

### ISSUE THREAD

**Issue by daTokenizer** [akonwi/git-plus#254]

**Comment by akonwi** [comment]
Can you elaborate this please?

**Comment by daTokenizer** [comment]
when working on private repos double tab act as a shortcut to "add all commit push"

**Comment by akonwi** [comment]
Are you saying that pressing the tab key twice starts that command?

If so, check your keymap file and make sure you don't have a mapping for double tapping the tab key. This package doesn't contain a mapping for that.
