### ISSUE TITLE
Takes all resources - other programs stop working 

### ISSUE THREAD

**Issue by jaulz** [akonwi/git-plus#256]
(Originally I posted it here: https://github.com/atom/atom/issues/8196)

After upgrading to the latest version (1.0.3) I frequently face the issue that Atom takes all the resources (new MacBook Pro; Chrome with a lot of tabs open and XCode) and other programs suddenly stop working:
-Node.js: error with code EAGAIN
-No new terminal: bash: fork: Resource temporarily unavailable
-Chrome: no new tab

As soon as I close Atom everything runs smoothly again. Also I already tried to increase the ```ulimit -n``` but nothing helped so far. Has someone else also experienced these issues? Is it Atom itself or maybe a system setting? 

P.S: just in this second Atom also stopped working and the error report says the following (creating this issue from within Atom is also not possible as Atom does not react to this click):
```
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120
Hide Stack Trace
TypeError: undefined is not a function
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120:27)
  at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:111:12)
  at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:23:18)
  at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:398:37)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:77:26
```

**Comment by akonwi** [comment]
Why do you think this is related to Git-Plus? The stack trace you shared doesn't seem to have anything pointing to my package. `GitRepository` is part of the atom api. 

There was an issue of atom being slowed down by creating tons of GitRepository objects in #158 but that has been resolved for a while and now there is only one use of GitRepository but it is rare and is destroyed immediately

**Comment by CKrawczyk** [comment]
I see a similar thing happen every time atom updates the git-plus package (all other packages update just fine).  I have no idea if this issue is related to this package, or if it is some bug in atom's package update code.  Aside from updating, I see no performance issues.

System:
MacBook Pro (late 2014 model)
Atom v1.0.7
