### ISSUE TITLE
Doesn't seem to work with submodule

### ISSUE THREAD

**Issue by lparmentier-quatral** [akonwi/git-plus#257]
I've the follow message when i'm trying to add:

fatal: Pathsec 'apps/app/file.php' is in submodule 'apps/app'

**Comment by akonwi** [comment]
Is the project root, the parent repo or the submodule?

**Comment by lparmentier-quatral** [comment]
It's when I'm opening atom on project root which is the parent repo, and when i'm trying to do a add of a file in a submodule. Is this enough clear ?

**Comment by akonwi** [comment]
Here is my attempt at replicating the issue. 

1. I have a repo named 'fizzbuzz' and a submodule inside as 'cosmo.js'.
2. I've made a change inside `fizzbuzz/cosmo.js/README.md`
3. While the README is open, I'm using `Git Add`
4. I run `Git Commit` to commit the change in the submodule
![submodule](https://cloud.githubusercontent.com/assets/2013804/9261920/d66e83ba-41d6-11e5-98a8-4f0fb8273f05.gif)

**Comment by lparmentier-quatral** [comment]
How are you making your .gif image like that ? I'll give you my reproduce

**Comment by akonwi** [comment]
[Licecap](http://www.cockos.com/licecap/)

**Comment by lparmentier-quatral** [comment]
![issue-atom](https://cloud.githubusercontent.com/assets/4061387/9333073/ecb89076-4595-11e5-8877-ea6582c4556c.gif)

**Comment by akonwi** [comment]
That's puzzling. Are you using the latest version of the package? If so, can you uninstall the package and clone this [branch](https://github.com/akonwi/git-plus/tree/257) into `.atom/packages/`. Then run `apm install` and try again.

Open the dev console and you should see some info logged about where the repo for the file is. Can you verify if that is correct or not?

**Comment by nahuelhds** [comment]
+1 for supporting this.
Doing changes in my submodule and then pressing "CTRL + SHIFT + A P" just says "Nothing to commit", which is wrong as I have my submodule repo changed.

**Comment by akonwi** [comment]
I'm tagging this as a duplicate and this is the original -> https://github.com/akonwi/git-plus/issues/312

This is an issue with atom core (https://github.com/atom/atom/issues/2203). Atom only recognizes the repositories at the top level of a project. Unfortunately, this package leverages atom's git environment for finding repositories.

**Comment by akonwi** [comment]
Update: You should be able to do most of the commands like add, commit, and diff on submodule files now
