### ISSUE TITLE
Toggle the drawer with output messages

### ISSUE THREAD

**Issue by chriskaukis** [akonwi/git-plus#258]
When I push and pull sometimes I want to read the messages that are in the drawer that pops up on the bottom above the status bar. However, it closes sometimes before I can finish reading and I do not see a means to toggle it or show/hide. 

Can (or is there already?) there be a means to open and close the message output drawer that shows up when pulling and pushing?

**Comment by anderson-arlen** [comment]
+1

**Comment by hotoiledgoblinsack** [comment]
Also related to #241.

**Comment by akonwi** [comment]
Sorry for the late reply. There is a pin icon in the status-bar that toggles the output drawer. It's not mapped to a keybinding yet

**Comment by akonwi** [comment]
I'm closing this since Atom now has the docks and git-plus is taking advantage of that.
