### ISSUE TITLE
Default push-to branch

### ISSUE THREAD

**Issue by kelso** [akonwi/git-plus#259]
Specific usage - for Heroku users:

Let's say I am on branch develop and want to push to heroku master. I usually run:

```
git push heroku develop:master
```

Trying to do this with Git Plus, but the result is that develop branch on Heroku is created. Would be nice to show prompt for target branch also. It would be killer feature for Heroku users :+1:

**Comment by akonwi** [comment]
Use the `Run` command and then you can enter `push heroku develop:master`. The run command lets you do commands not implemented.

If you'd like to work on this feature that'd be cool. I'm not sure it would save many keystrokes though

**Comment by kelso** [comment]
@akonwi Run command works, thanks!

I'm little bit confused that I see Heroku remote output in these error boxes (instead nice log frame in the bottom when I do regular push to bitbucket/github):

<img width="608" alt="screen shot 2015-08-14 at 17 37 22" src="https://cloud.githubusercontent.com/assets/35310/9277583/772f543a-42ab-11e5-863e-1b97cec4d716.png">

**Comment by akonwi** [comment]
The output of the run command has been put into the the terminal-like output view with color highlighting in recent versions.
