### ISSUE TITLE
Commit Message pane does not get destroyed when done

### ISSUE THREAD

**Issue by batjko** [akonwi/git-plus#260]
Hi there,

I am using the default setting to open a new pane for commit messages.
However, once I save my commit message, which automatically closes the message text, it does *not* close that pane!

As an illustration:
![gif](http://i.imgur.com/l8XCclB.gif).

I've only started using this package today, so let me know if I'm doing something wrong, but it looks like a bug to me.

I'm on Atom 1.0.7, git-plus 5.4.0, Win10 64bit.

**Comment by batjko** [comment]
Works! Thanks for the quick response! :bow:

**Comment by akonwi** [comment]
no problem!
