### ISSUE TITLE
No notification when a git push and pull is starting

### ISSUE THREAD

**Issue by IamAdamJowett** [akonwi/git-plus#264]
Firstly, kudos on a great plugin. 

I have a small UX issue, and that is there is no indication when a push or pull is starting, which for large commits, makes it hard to know when it is just a large push or pull, or when you have credential issues that you need to jump into the command line for. 

This is especially an annoyance if you have assigned keyboard shortcuts to push and pull as I have.

**Comment by akonwi** [comment]
Right now, the notification for pushing and pulling is a pane that appears above the status-bar. Is this not displaying for you? 

I'm not completely satisfied with the using the lower pane though because it isn't consistent with the other popup notifications and they can appear too quickly and not allow enough time to be read. #241 is a task to improve the UX there.

**Comment by IamAdamJowett** [comment]
@akonwi I see the pane when pushing and pulling has __finished__ which I am thinking you are talking about, not when it is starting or in progress. Is it supposed to show when it starts?

If it is not, even a spinner in the bottom right where you show the changes would work when a git push or pull starts. Again, not a major thing in the greater scheme of things, but might be a nice UX change.

**Comment by akonwi** [comment]
Good point. I also like the suggestion for a spinner. I'm working on some refactoring right now which will make the codebase easier for changing the notification system so I'm going to hold off on those changes until I finish the refactoring

**Comment by IamAdamJowett** [comment]
@akonwi no problems, look forward to the changes, and jumping in and helping where I can.

**Comment by akonwi** [comment]
Awesome! Help is always appreciated haha

**Comment by IamAdamJowett** [comment]
Hey @akonwi nice work on solving this issue I raised, like what you have done.

**Comment by akonwi** [comment]
Great! Thank you very much! It's good to hear that!
