### ISSUE TITLE
List of available commands so that we can create key binding for each

### ISSUE THREAD

**Issue by chrisduong** [akonwi/git-plus#265]
Hi,

For e.g. I want to create a key board shortcut, for creating a new branch, instead of having to type `Cmd-Shift-H` and then choose "New branch" option.

With shortcut, I can go straight to type the "new branch name". But I cannot find the corresponding command of `git-plus`.

Thanks.

**Comment by akonwi** [comment]
All the commands are accessible for keybindings by dasherizing the command title.

For example:
> `Git Add` ==  `git-plus:add`
> `Git Add All Commit And Push` == `git-plus:add-all-commit-and-push`

and for `Checkout New Branch` it would be `git-plus:checkout-new-branch`.

I'll add this info to the readme

**Comment by chrisduong** [comment]
Thanks. That is very helpful.
