### ISSUE TITLE
Delete Local Branch issue

### ISSUE THREAD

**Issue by graineri** [akonwi/git-plus#266]
When trying to delete a local branch that has a slash as part of its name, it fails.

Example:
* Branch Name: feature/whatever
* Error:
```
Git-Plus
fatal: 'feature' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists
```

**Comment by akonwi** [comment]
Are you using the latest version of the package? This was already an issue at #233 and the fixes were published in version 5.3.0

**Comment by graineri** [comment]
Yes, I'm using version 5.4.5.

**Comment by akonwi** [comment]
I just pushed an update. Give it a shot

**Comment by graineri** [comment]
Works perfect! Thanks a lot!

**Comment by akonwi** [comment]
Awesome!
