### ISSUE TITLE
Branch drawer (sometimes) shows no matches

### ISSUE THREAD

**Issue by filipesilva** [akonwi/git-plus#267]
I think this started happening today, or a at best a couple days ago. I'm on windows 10, atom 1.0.7, git-plus 5.4.6.

I open the command pallete, type in git pull, and sometimes I get a list of branches and sometimes I don't. I think a gif will help. The first two tries show no results, the third one you can briefly see results, and the last one finally shows them.

![pull](https://cloud.githubusercontent.com/assets/4172079/9384148/4bb8730a-4746-11e5-91bc-5b536b703c92.gif)

**Comment by lgrube** [comment]
Ive been having this problem for awhile now except mine never show up. Hopefully someone can answer this right away. Im using SSH keys instead of https

**Comment by lgrube** [comment]
mine started working. not to sure what i did though.

**Comment by akonwi** [comment]
Is this an issue @filipesilva ?

**Comment by filipesilva** [comment]
@akonwi I cannot tell, as I do not use Atom anymore. Will close.
