### ISSUE TITLE
duplicate tabs for some(?) operations

### ISSUE THREAD

**Issue by jabbrwcky** [akonwi/git-plus#268]
With Version 5.4.4 / Atom 1.0.7 I get duplicate tabs opened for the following actions:

commit message for Git: Add All And Commit
diff view for: Git Diff

Closing on of the duplicate tabs also closes the other one. A bit annoying.

**Comment by akonwi** [comment]
Is this still an issue?

**Comment by jabbrwcky** [comment]
No, it has not occured for a while now
