### ISSUE TITLE
Cmd-Shift-A P shortcut only works after use of Cmd-Shift-A

### ISSUE THREAD

**Issue by mpseidel** [akonwi/git-plus#269]
When I make an edit and hit [Cmd-Shift-A P], nothing happens. Only if I add with [Cmd-Shift-A] once first, [Cmd-Shift-A P] starts working as expected. Am I missing something?

Using 5.4.6 on Windows.

**Comment by mpseidel** [comment]
@akonwi thanks for the quick response! Doesn't seem to solve the issue here though. I am using vimmode as well but no autosave plugin if that helps. Let me know if you need more info.

**Comment by akonwi** [comment]
That is really bizarre! From what I'm experiencing, that specific keymapping doesn't activate the package but everything else does. But once the package is activated, the mapping works as expected.

Is that the same for you? Or does it just not work at all before you Git Add?
