### ISSUE TITLE
Enhancement - Ability to specify empty pull command (to improve workflow).

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#270]
Hello

The pull command currently requests you to specify a branch to pull from, which is good. However, seeing as a lot of pulls tend to go from the origin branch to the local branch of the same name (e.g. origin/master to master), a `git pull` without arguments suffices for this task. Perhaps it would improve the workflow if the first item in the branch selection screen would be a 'special' item which would not add any arguments to the command so you can always blindly press the return key to pull the origin of the current branch?

Thanks in advance and look forward to your response

**Comment by akonwi** [comment]
That's a good idea. I think the same should be done for pushing too right?

With the exception of fixing critical bugs, I want to hold off on changing/add features because I'm currently trying to do some major refactoring to make the package much easier to extend and test.

**Comment by akonwi** [comment]
I've pushed this into a new branch. I'd rather not push it until you've given it a test run and get your feedback

**Comment by Gert-dev** [comment]
I've tried it out, but don't immediately see any difference from before. I've analyzed the branch and stepped through the modified code using breakpoints and it goes into the `if remotes.length is 1` if statement every time. The actual remotes listed are then `origin/master`, `origin/branch_x` and `origin/HEAD->origin/master`, even though I'm on branch `master`, which should (?) default to `origin/master` (instead it always selects the first item in the list, which happens to be `origin/HEAD->origin/master`). Maybe I'm doing something wrong? If I've read the code correctly an extra item named `== Current Branch ==` should be showing up?

**Comment by akonwi** [comment]
Oops, I put the logic in the wrong place. Take a pull and try again

**Comment by Gert-dev** [comment]
Seems to work great, can't immediately see any bugs or anything. This will surely improve the Git workflow as you can now blindly press the return key when pulling in most cases, thanks!

**Comment by akonwi** [comment]
Awesome, I'll publish this as well

**Comment by scippio** [comment]
How to set up in the keymap?
