### ISSUE TITLE
win7 report an error : (

### ISSUE THREAD

**Issue by chuandadexiaoyu** [akonwi/git-plus#271]
when I Install on win7, it report a error, is it because python not installed well : ( ?

In stalling “git-blame@0.4.5” failed.Hide output…

> runas@2.0.0 install C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-115727-7928-1i9g6bx\node_modules\git-blame\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-115727-7928-1i9g6bx\node_modules\git-blame\node_modules\pathwatcher\node_modules\runas>node "C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app\apm\bin\\node.exe" "C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Administrator\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Administrator\.atom\.apmrc" "install" "C:\Users\ADMINI~1\AppData\Local\Temp\d-115727-7928-15nzpwn\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by akonwi** [comment]
If you're installing git-blame, this is the wrong repository
