### ISSUE TITLE
Trouble When pushing to remote repo on Fedora

### ISSUE THREAD

**Issue by ClementVidal** [akonwi/git-plus#275]
Hi !

When i try to push commits to my distant repo on bitbucket, i get the following message: 
"
No protocol specified  
(gnome-ssh-askpass:11321): Gtk-WARNING **: cannot open display: :0
Permission denied (publickey).
fatal: Could not read from rmote repository.

Please make sure you have the correct access rights
and the repository exists.
**

Atom is started from a shell where ssh-agent is running.

I do not have much more informations, 
any of you already face this issue ?

Thanks a lot,

Clément

**Comment by akonwi** [comment]
There are a ton of issues similar to this. On non-mac systems, this seems to be a configuration mismatch. If you explore the issues related to 'ssh' and 'windows', you might find a solution.

**Comment by akonwi** [comment]
Someone posted their solution in #224 and #219

**Comment by piggyslasher** [comment]
@akonwi - Neither has any solutions that worked. I've read through. The first thread has all to do with Putty. And the second #219 is a discussion that went nowhere, especially since we're using git@ and not https.

Git-plus does not seem to work if you have set a passphrase for your SSH key. That's the bottom line. It simply doesn't work. Is there any where else I can look?

**Comment by akonwi** [comment]
@piggyslasher the original issue here is actually about a mismatch of configurations.

If interacting with a remote repo requires you to type anything more like credentials, then you won't be able to do it from the package at this point. I've stated that in the README. The package doesn't work that way. I don't know where you can look. The only immediate solution is to use [ssh-agent](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) so you don't have to type your passphrase every time
