### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by atre7** [akonwi/git-plus#277]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Ubuntu 14.04.3
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.4.7
### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at gitCmd (/home/aaa/.atom/packages/git-plus/lib/git.coffee:31:9)
    at Object.gitAdd [as add] (/home/aaa/.atom/packages/git-plus/lib/git.coffee:99:3)
    at gitAdd (/home/aaa/.atom/packages/git-plus/lib/models/git-add.coffee:9:7)
    at /home/aaa/.atom/packages/git-plus/lib/git-plus.coffee:78:108
    at process._tickCallback (node.js:367:9)
```
### Commands

```
     -9:06.3.0 application:new-file (atom-text-editor.editor.is-focused)
     -8:58.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -8:47.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:05.9.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -0:25.4.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:25 core:move-right (atom-text-editor.editor.is-focused)
     -0:23.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.2.0 git-plus:add (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "/home/aaa/Git/"
  },
  "git-plus": {
    "gitPath": "/home/aaa/Git"
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
atom-html-preview, v0.1.11
atom-jsfmt, v0.8.3
atom-jshint, v2.0.0
autoclose-html, v0.19.0
color-picker, v2.0.11
git-plus, v5.4.7
minimap, v4.13.2
pigments, v0.13.2

# Dev
No dev packages
```

**Comment by ejames9** [comment]
Getting this error every time I try to pull. Not sure what else to try.

**Comment by akonwi** [comment]
Is this still an issue?

If so, I suggest cloning the 5.5.0 branch from this repo and replace `~/.atom/packages/git-plus` with it. That branch is going to to be the next big release so it would be helpful to have more beta testers.

PS make sure to run `apm install` in the newly cloned repo

**Comment by c18js** [comment]
I have the exact same error and I cannot push. No Idea what to do. Where is the 5.5.0 branch I can't seem to find it.

**Comment by Jammizzle** [comment]
Can't do a single thing with git plus without receiving this error

**Comment by abyjoz** [comment]
still getting this... i am on 5.17 though

**Comment by abyjoz** [comment]
Just realized the i was getting this because in the Git-Plus settings->GitPath, i had the location of my local  project directory; instead, it should be the location of your git command.
so run the following command in terminal, and use that path in the git-path --

which git

**Comment by akonwi** [comment]
Thanks @abyjoz that's the correct solution. I just noticed @atre7 that your config for git path is incorrect. That setting is to the git binary or executable if you don't have it in your PATH. Otherwise you can leave it blank and the package will just default to using `git`
