### ISSUE TITLE
Git-plus not support pre-commit githooks on MacOSX

### ISSUE THREAD

**Issue by kglazkov** [akonwi/git-plus#279]
Git-plus not support pre-commit githooks on MacOSX

**Comment by akonwi** [comment]
From my understanding, the hooks are taken care of by git. Is there a flag or option that needs to be set first. 

Otherwise, I don't see why they wouldn't run. The package simply runs "git commit --cleanup=strip --file=COMMIT_EDITMSG" in a child process.

**Comment by akonwi** [comment]
Fixed with pr #341
