### ISSUE TITLE
Support Git in Git please!

### ISSUE THREAD

**Issue by envygeeks** [akonwi/git-plus#280]
Say we have a main git repository that has sub repositories.  It would be nice if you checked for a git repository in the files directory before you checked for a git repository in the parents directory (or even asked which repository to use.)

This is common for us as our build server has a ports directory that is a git repo but we also store repos we maintain for other projects (like octopress/docker and jekyll-docker.)

**Comment by akonwi** [comment]
Right now the implementation works like this:
- get current file path
- check if the file belongs to an open project in atom
  - If it does
    - check if that project is a git repo
      - is that repo a submodule

Are you using submodules or just sub repositories?

**Comment by envygeeks** [comment]
We use sub-repositories only for this project because git 1.7+ supports repos in repos in repos.  So what happens is this:

* https://github.com/envygeeks/docker
  * https://github.com/jekyll/docker
  * https://github.com/octopress/docker

Now what would be nice if that if we are in the root of the project then use the projects git repository but if we are ctrl+x on a file and that file belongs to a repo that is in the projects repo, use that repo.

So say I am in https://github.com/envygeeks/docker/tree/master/dockerfiles/jekyll/Dockerfile and I edit something, at that point I would prefer it to commit to https://github.com/jekyll/docker, but when I add all files in the parent of the project, I would prefer it to use https://github.com/envygeeks/docker.

This might be complicated logic because I'm bad at explaining things but hopefully that clears everything up at least a bit.

**Comment by akonwi** [comment]
That makes sense. It is complicated logic and that's actually how the package used to work while atom was still pre-1.0.0. That release of atom allowed opening multiple projects in the same window and I removed all the complex logic to just use what atom was now providing. A solution for what you want is to open atom with `atom . */`. This will open the parent and all the child directories as their own projects.

I'll explore a way to bring back that old behavior in a clean way though

**Comment by akonwi** [comment]
If you're using proper submodules, then you should be able to do most things now from atom. I made some changes a few months ago that support using submodules.
