### ISSUE TITLE
Commit message triggers autosave when no other files open

### ISSUE THREAD

**Issue by billyjanitsch** [akonwi/git-plus#282]
Repro:

1. Open a project
2. Open a file, make changes
3. Close the file
4. Add All, Commit, and Push via git-plus
5. Type a commit message
6. Save

The push is successful, but the autosave dialog is triggered on the commit message editor. This doesn't happen if you have at least one file open when you Add/Commit/Push (presumably since the commit message then opens in a new pane).

**Comment by akonwi** [comment]
What is the autosave dialog? May be this is similar to #235.

**Comment by billyjanitsch** [comment]
![wedsxeotmh](https://cloud.githubusercontent.com/assets/1158733/9822272/644253c0-588d-11e5-9162-afa4f5779071.gif)

**Comment by akonwi** [comment]
Is this related to the auto-save package? Maybe try disabling that feature and see if this still happens. I've opened a pull request to that package to allow other packages to disable it on a per-file basis but nothing has changed yet.

**Comment by billyjanitsch** [comment]
I don't have autosave enabled.

**Comment by akonwi** [comment]
Yea I haven't seen this happen yet. 

I have a new branch called 5.5.0 in this repo which is going to be the next release. You can clone that and replace your installation of git-plus with it and try it out to see if this still happens

**Comment by billyjanitsch** [comment]
Looks to be fixed on 5.5.0. Thanks!

**Comment by yuvipanda** [comment]
Can someone close this issue now? :)
