### ISSUE TITLE
Implement commit of multiple "selected" files

### ISSUE THREAD

**Issue by Jerotire** [akonwi/git-plus#283]
Feature Request!

It would be great to be able to select the files that one would like to commit using the directory tree in an open project.

For instance, several times I wanted to commit lets say 2 out of 10 modified files (as I sometimes work on multiple problems at the same time). I would like to use the CTRL + Left Click in the directory tree, and Add/Commit those selected files.

At its current state, I am only able to commit a single file (selected TAB), or the whole project. Without me using the commandline, which in my opinion defeats the purpose of git-plus (I don't want to touch the cmdline :D).

**Comment by akonwi** [comment]
Check out #274. It seems like another alternative to what you're suggesting that I like a lot and want to move towards.

**Comment by akonwi** [comment]
There are also two commands - `Stage files` and `Unstage files` which allow you to select multiple files.
