### ISSUE TITLE
Bug - Shortcut for staging files doesn't appear to be working.

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#292]
Hello

Recently you added a shortcut to confirm the **Stage Files** dialog (thanks for that!), but it appears the shortcut isn't working. In `select-list-multiple-view`, the `keypress` event handler seems to never be executed. If I change it to `keydown`, it seems to work correctly. I also only see a keycode check for 13 in the code (the enter key), but could it be that the check for the shift modifier key is missing?

Thanks in advance

**Comment by akonwi** [comment]
I can't seem to reproduce this. It works for me and switching to `keydown` breaks the whole thing haha. The reason I used 'keypress' is actually kind of hack-ish but it's the only way it worked for me. When the enter key is pressed, the event is caught internally by atom and doesn't continue bubbling out. The keypress event doesn't get thrown for modifier keys but when a modifier is pressed, the enter key event does in fact trigger an event for other listeners (at least in my experience).

I'm working a new release in the 5.5.0 branch. You can clone that and replace your installation of Git-plus to test if you have this problem there as well.

**Comment by hotoiledgoblinsack** [comment]
The 5.5.0 branch does not seem to solve the problem. Well, I must admit this is very strange, could it perhaps be some kind of platform issue (I'm on Linux)?

**Comment by akonwi** [comment]
I figured it was probably related to platform differences. I'm on Mac but it still works even when I use the `ctrl` key as the modifier. I'll try to improve this, ideally with `onkeydown` and checking for a modifier.

**Comment by akonwi** [comment]
Does this still occur?

**Comment by dayletter** [comment]
@akonwi I am having this issue as well
OS: Ubuntu 16.10
Atom: 1.12.6
git-plus: 5.28.0

**Comment by Gert-dev** [comment]
For me, this is no longer a problem, but it works using `shift + return` rather than `control + return`.

**Comment by akonwi** [comment]
@dayletter Have you tried using `shift + return`?

**Comment by akonwi** [comment]
The next release will fix this actually. You will be able to use both shift and ctrl as a modifier
