### ISSUE TITLE
Git Init not working

### ISSUE THREAD

**Issue by remi6397** [akonwi/git-plus#293]
Hi, in my atom on Windows, "Git Plus: Git Init" just disappears from command palette when clicked. No errors visible on screen, even in developer console.
Could anyone check this weird behavior?

**Comment by akonwi** [comment]
That's odd. I'm working on the next release which will be a big change. 

You could clone the 5.5.0 branch in this repo and replace your local installation of the package, run `apm install` in it and test to see if this is still an issue. If you run into any other issues please let me know

**Comment by chiangs** [comment]
@akonwi I don't have the "git plus: git init" in either the git plus pallet or the atom general pallet. I'm on mac el capitan, latest atom and git-plus packages as of today 23 jan 2017.

It's not available even when I create a new project folder.

**Comment by akonwi** [comment]
@chiangs Do you have a non-git project open? The init command will only be the atom palette when there isn't a git repo open and it will never be in the git-plus palette.
