### ISSUE TITLE
Nothing to commit

### ISSUE THREAD

**Issue by thenoid** [akonwi/git-plus#294]
Running into a situation where even though there are changes to commit, git-plus doesn't see them.  Atom see the differences (yellow arrows), the git-scm client sees that there are changes to commit, but not git-plus when I select the commit command.  

I can at times get it to see the changes, by re-adding the file, but it only works momentarily.

![git-plus says nothing to commit](https://cloud.githubusercontent.com/assets/2242308/10125580/7584e7ba-653f-11e5-9088-9758c6875b46.png)
![git shows diff](https://cloud.githubusercontent.com/assets/2242308/10125578/74fd83ec-653f-11e5-89f7-04c30e192679.png)
![commiting stuff](https://cloud.githubusercontent.com/assets/2242308/10125579/7574394c-653f-11e5-9431-7aa86eb8e197.png)

**Comment by VermillionOne** [comment]
ran into this also

**Comment by akonwi** [comment]
I'm preparing a big release for the upcoming weeks. You can find it in the 5.5.0 branch of this repo. You can clone that and replace your local installation of the package with it to try it out and see if this still happens there. The feedback would be helpful in case you run into any other things as well.

**Comment by voromax** [comment]
Same problem here

    Atom version 1.1.0 (installed using Homebrew Cask)
    git-plus version 5.5.4
    git version 2.6.3

Git Plus: Commit All 
works fine

**Comment by p0la** [comment]
Hi, I have the same problem. Note that "commit all" is working fine though.

**Comment by scippio** [comment]
I think, you must first call Git plus: Add

**Comment by akonwi** [comment]
@scippio Thanks for that. I just noticed in @thenoid's screenshots, there are no staged files.

You need to stage files with the add commands before committing

**Comment by ave19** [comment]
So, normally, in git, once you've added a file to a repository, you don't need to add it again.  You can just commit from then on.  Why do you have to keep adding files in git-plus?

**Comment by akonwi** [comment]
There is a difference between adding files to a repository and adding files to the index to be committed. The 'Git add' command adds the file to the index which means it is ready to be committed. If you create a new file and do 'git add /file/path' in the cli, that simply adds a new file into the index. 

You can read more on 'git add' [here](https://git-scm.com/docs/git-add)

**Comment by ave19** [comment]
Nothing like sacrificing usability to the man page!  I'm sorry, you've lost a customer.  No hard feelings, though.

**Comment by akonwi** [comment]
@ave19 This package is just a medium for executing the same commands you would do in the terminal with the convenience of staying inside the editor. I've explained how git as a version control system handles the 'add' command you would otherwise type in the command line. If the concern is the usability of the 'add' command, then it should be raised with the version control system and not this package.
