### ISSUE TITLE
Create annotated tags

### ISSUE THREAD

**Issue by chrisduong** [akonwi/git-plus#295]
I think it is useful that this plugin support to create an annotated tag.

**Comment by IamAdamJowett** [comment]
+1 this, as tags are so vital to versioning for me, being able to add, and push tags would be great. @akonwi any plans for this? If I can sedate the kids long enough, perhaps I can help on this feature.

**Comment by akonwi** [comment]
There are tag features in the package. They can be accessed through the `Tags` command in the palette. You can add a tag with an annotation message. The tags can also be pushed, checked-out, verified, and deleted.

Is there something missing?
