### ISSUE TITLE
[Feature pull request]Click on status bar branch to open beanches menu

### ISSUE THREAD

**Issue by kandros** [akonwi/git-plus#297]
Hello, i created this little snipper in my init.coffee
```coffeescript
editorEl = document.querySelector('atom-text-editor')
gitBranchEl = atom.views.getView document.querySelector('.git-branch')
gitBranchEl.addEventListener 'click', ->
  atom.commands.dispatch(editorEl,'git-plus:checkout')
gitBranchEl.style.cursor = 'pointer'
```
I'm not sure where to put this for make a pull request

**Comment by akonwi** [comment]
the activate method in `lib/git-plus.coffee` might be the place for it.

The 5.5.0 branch is what I'm working on for the next release so can you make a clone of that branch and work with that instead?

**Comment by akonwi** [comment]
this is now in the latest release
