### ISSUE TITLE
Please give an error when git isn't configured (or other problem)

### ISSUE THREAD

**Issue by rrthomas** [akonwi/git-plus#298]
Twice now I've forgotten the sage advice:

"IMPORTANT: Make sure your gitconfig file is configured or at least your user.email and user.name variables are initialized"

I have added files and committed files and each time git-plus gives me a nice green pop-up box. I have failed to notice that it doesn't contain any status text, and have therefore failed to realise that git-plus is LYING! Things are NOT OK!

Please, when git returns an error status, make the box *RED*.

**Comment by akonwi** [comment]
I think this should be gone in the current release. I'll keep an eye out for it. Please let me know if you see another instance of this
