### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by pokemane** [akonwi/git-plus#301]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v5.4.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /C:/Users/.../.atom/packages/jshint/index.js:245

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at lint (C:\Users\...\.atom\packages\jshint\index.js:245:10)
  at complete (C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
  at delayed (C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)

```

### Commands

```
     -0:31.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "node-debugger"
    ]
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
jshint, v1.8.1
react, v0.12.10

# Dev
No dev packages
```

Really not sure what triggered this error, honestly.  I created a new project, did the normal ```git init``` and got set up with my initial files and folders.

**Comment by akonwi** [comment]
Do you think you can replicate this?

**Comment by pokemane** [comment]
Honestly unsure; it was happening quite a few times with a couple projects but hasn't happened since, and I've updated the package a couple times since this.  I wouldn't be opposed to closing this, since it seems to be isolated (nobody else has reported it) and hasn't happened again for me.
