### ISSUE TITLE
File tree coloring not updateing on commit

### ISSUE THREAD

**Issue by icimasa** [akonwi/git-plus#302]
Hi,

on windows 10, the color on a file in the file tree when changing it is marked as orange, however on commit the file coloring is not reset to grey, it is still set as checked out or changed. I get an error when running dev tools, could be a clue maybe?

'save-session.dataSaveFolder' could not set the default. Attempted default: undefined; Schema: {"type":"string","description":"The folder in which to save project states"}

reported in config.js

//Martin

**Comment by akonwi** [comment]
This doesn't seem to stem from the git-plus package. Perhaps check your config.js and make sure that `save-session.dataSaveFolder` setting is properly configured.

**Comment by Ajedi32** [comment]
I'm having a similar issue (though not with the `save-session.dataSaveFolder` error). It seems to be related to line endings. git on the command line doesn't report the file as changed, but `git-plus` is showing the file as changed.

Opening the file shows +22, -22 in the stats indicator in Atom, but doesn't show any individual line in the file as changed. (There are no bars indicating changed lines on the left.) If I change the file, the changed lines are shown as changed in the bars on the left, but no other lines in the file are shown as changed (as the stats indicator seems to indicate).

Showing hidden characters lets me see that the line endings in the file are indeed different, but these changes are ignored by git, as per my settings.

Now here's something weird I discovered in the process of debugging this issue. This might actually be a bug in git...

```text
$ git config core.autocrlf
input
$ git config --global core.autocrlf
$ git config --local core.autocrlf
$ git config --system core.autocrlf
```

git seems to think my `core.autocrlf` setting is set to "input", but I don't have it set to that anywhere in my settings. Why? I have no idea. Anyone know if this is a bug? And if so, where do I report it?

Anyway, here's a temporary workaround that fixes the problem with git-plus for me. Just set `core.autocrlf` explicitly:

```text
$ git config --global core.autocrlf input
```

Where is `git-plus` getting its information on whether to ignore line endings? Shouldn't it just be running `git config core.autocrlf`?

**Comment by icimasa** [comment]
thanks @Ajedi32 for the update, the config --global setting did do the trick also for me and now it works like a charm.. :)

**Comment by akonwi** [comment]
@Ajedi32 It may be important to distinguish between git-plus and atom's inherent git features. The status-bar git stats, gutter highlighting, and tree-view highlighting are atom core packages. Git-plus simply runs commands so it has no idea of line endings and changed files until you run `git status`, `git diff`, etc within the command palette. 

You might be right about this behavior being a bug with git though, or at least with the git tools in atom

**Comment by Ajedi32** [comment]
Ah, then isn't this entire issue irrelevant to git-plus, since it's about the file coloring in the tree view?

**Comment by akonwi** [comment]
Yea I don't think it belongs here. You may want to open it in the tree-view package

**Comment by Ajedi32** [comment]
Yeah, based on what I read in http://blog.atom.io/2014/03/13/git-integration.html it seems it's part of the core APIs. I'll open a new issue in the Atom core.
