### ISSUE TITLE
Git Push creates new branch on remote instead of pushing upstream

### ISSUE THREAD

**Issue by engelant** [akonwi/git-plus#304]
Hello there,
I'm not sure if mybe I did something wrong, but I have the following issue:
My local git is set up to have two remotes:
origin
backup

I have two branches locally:
development
release

And they are set eahc with an upstream:

development: backup/master
release: origin/master

Let's say Im currently on the release branch and want to do a git push from the console, so I do "git push" and everything gets pushed to "origin/master" as it's set as upstream.
If I try to push from Atom I get to select between [origin] or [backup]. As soon as I select one of them, let's say origin, the stuff gets pushed to origin/origin, creating a new branch calles like the remote.

Anyone any thoughts on that?

**Comment by akonwi** [comment]
I'm sorry I didn't respond to this sooner. I haven't noticed this and I can't replicate it now. Is this still the case?
