### ISSUE TITLE
Cmd-Shift-A P doesn't working

### ISSUE THREAD

**Issue by KienTrong** [akonwi/git-plus#316]
I'm going to commit and push using Cmd-Shift-A P but it's not working, do you guys know how to solve it?

* Mac os El Capital
* Keyboard Viewer : http://cl.ly/image/0w0s1A1q373E
* Git Plus 5.5.6
* Atom 1.1.0

**Comment by akonwi** [comment]
What exactly isn't working? Does the commit part still work but not the push or does nothing happen at all when you use the key mapping?

If the push isn't working, I have an idea as to why and will be working on it soon

**Comment by KienTrong** [comment]
When I press Cmd-Shift-A P to commit and Push, this message will show http://cl.ly/image/0Z1F3F2r0711, no commit or push.

**Comment by KienTrong** [comment]
Also here is my Atom -> Git Plus package shortcut : http://cl.ly/image/1R0W3i0Y441K not sure why that shortcut hasn't in the list.

**Comment by akonwi** [comment]
With the latest release this should be fixed. Have you updated?

**Comment by KienTrong** [comment]
Running latest verison, still there is no shortcut display : http://cl.ly/image/1C0r0Q3W0r45 :(

**Comment by akonwi** [comment]
Is the actual keybinding working though? And does the command work on its own?

The menu won't show the shortcut because it has a second part, which is the 'p'. If the command was just 'cmd-shift-a', then it would show a shortcut
