### ISSUE TITLE
Issue with command: Git plus add, commit, and push

### ISSUE THREAD

**Issue by renesansz** [akonwi/git-plus#317]
In regards to the command, it seems after doing the commit, the command takes you to `git pull` instead of `git push`.
Unlike before, wherein after commit it takes you to git push automatically.

**Comment by akonwi** [comment]
This is a result of pull request #291. I actually made pulling before pushing the default implementation, which shouldn't be the case. I want to make it a configuration setting instead and not force that on anyone. This is probably related to #316 too
