### ISSUE TITLE
"add all commit and push" makes me choose a branch to pull every time

### ISSUE THREAD

**Issue by SlimeQ** [akonwi/git-plus#319]
after latest update, every time i use the "add all commit and push" function, it prompts me for a branch, pulls it, then pushes to current branch... this has on more than one occasion caused me to accidentally merge a branch into my current, it's bad

**Comment by akonwi** [comment]
Related to #317 #316. I made that the default implementation and I've since realized that's not right. I'll make this a configuration setting so it can be opted into.

I apologize for causing terrible things in your repo :sad:

**Comment by SlimeQ** [comment]
:+1: thanks!

**Comment by mautematico** [comment]
Thank you!
