### ISSUE TITLE
Feature Request: git fetch --all

### ISSUE THREAD

**Issue by drazisil** [akonwi/git-plus#320]
When I create a new branch on github, I seem to have no easy way to let atom know that branch exists without going to the term and doing a `git fetch --all`

Does this feature exist, or can it be added to the `git fetch` command?

**Comment by akonwi** [comment]
This doesn't exist currently. It could be done with the `Git Run` command though. It allows you to do things that aren't part of the package without going to the terminal. You can enter `fetch --all` in the input after selecting `git run`

**Comment by drazisil** [comment]
Nifty, I'll give it a shot, thanks.

**Comment by mediafinger** [comment]
@akonwi great package, thx a lot!

I would recommend to mention the `git run` command in the README. I overlooked it at first as well.
