### ISSUE TITLE
Cant find git binary at windows 8

### ISSUE THREAD

**Issue by mightydok** [akonwi/git-plus#322]
Catch an error:
```
Uncaught BufferedProcessError: Failed to spawn command `git`. Make sure `git` is installed and on your PATH
```

But git installed and PATH to git binary available at proccess.env from atom developer console. Change settings to full git path or path to git binary directory dont help.
Plgin version 5.6.1

**Comment by akonwi** [comment]
Are you saying the 'Git path' option in the package settings isn't working for you?

**Comment by mightydok** [comment]
@akonwi yes, more info on screenshot: http://joxi.ru/l2ZYJgpCkPZGmJ

**Comment by envygeeks** [comment]
What happens if you quote the value?

**Comment by mightydok** [comment]
@envygeeks check screenshot, same error. I open pull request for fix.
