### ISSUE TITLE
Is possible call something like: git-plus:pull:current ?

### ISSUE THREAD

**Issue by scippio** [akonwi/git-plus#325]
Is possible call something like: git-plus:pull:current ?

thx

**Comment by akonwi** [comment]
Check out #270

**Comment by scippio** [comment]
Thx, but how to set up in the keymap?

**Comment by akonwi** [comment]
Right now setting up a keymapping isn't possible

**Comment by akonwi** [comment]
You can set up a keymapping for the pull command but you'll still have to select "== Current ==" in the dropdown if you have more than one remote repo. 

The command to map to is `git-plus:pull` or `git-plus:pull-rebase`
