### ISSUE TITLE
Git push is not working

### ISSUE THREAD

**Issue by THPubs** [akonwi/git-plus#327]
Hi, Im on Ubuntu 14.04 (Elementary OS). In my system most of the other command like git log and git commit works. But git push does not. It says everything is upto date but it does not push. I have to push manually from the terminal.

**Comment by rustanacexd** [comment]
same here! exactly the same scenario

**Comment by chenasraf** [comment]
Do you have git with SSH configured ?

**Comment by THPubs** [comment]
Ok with the new updates it started to work again!
