### ISSUE TITLE
can not push

### ISSUE THREAD

**Issue by Javacym** [akonwi/git-plus#328]
git-plus
 Pushing... 
can not finish push   another question: does git-plus support git clone??

**Comment by akonwi** [comment]
Do you have ssh setup completely? Does pushing in the terminal prompt you for credentials?

There's no clone command right now

**Comment by Javacym** [comment]
no! i do not know why ssh-agent fail work...i only use https link ,that is work.

**Comment by chenasraf** [comment]
You need to get [SSH git](https://help.github.com/articles/generating-ssh-keys/) to work in order for this to work properly. Otherwise you'd have to authenticate before any action you take, and Atom/git-plus doesn't support that for now

**Comment by akonwi** [comment]
See #224
