### ISSUE TITLE
Move commit message window to the left if possible

### ISSUE THREAD

**Issue by IamAdamJowett** [akonwi/git-plus#329]
The git commit notification hides the area you are are trying to type into for the commit message. As it hangs around a little, this is quite annoying for the workflow, especially if you are using keyboard shortcuts to make the process quicker.

Not sure if this is possible, but can the commit message window be on the left instead of the right to fix this UX issue?

![git-message](https://cloud.githubusercontent.com/assets/294948/11258386/5bd24afe-8ea4-11e5-8d85-ac2a6229dccf.jpg)

**Comment by akonwi** [comment]
There's a setting for the package titled as 'Split pane direction'. It defaults to the right but you can change it

**Comment by IamAdamJowett** [comment]
Well now I feel like a fool :+1: ... thanks for that mate, liking the changes recently.
