### ISSUE TITLE
Linux, OSX: " Invalid refspec '[object Object]' " - pull using rebase

### ISSUE THREAD

**Issue by jaimefortega** [akonwi/git-plus#332]
I've tried to use the "pull using rebase" option from the menu, but I get the following error at the Atom's embedded Output Console:

fatal: Invalid refspec '[object Object]'

Also, it shows an empty list. It looks like that this happens only in the Linux version of Atom, because it works in the Windows version. I found this weird since I can push to my remote master branch without a problem. This also happens with "pull".

If I choose the "rebase" option from the menu, it shows the branches.

![git_plus_pull_bug](https://cloud.githubusercontent.com/assets/2206328/11316448/23aefd8c-8fe6-11e5-8396-4af64f61ec97.png)
[UPDATE]
It looks like that this happens in OSX too.

**Comment by igorsousa-b** [comment]
I'm having the same issue, but with both regular git pull and git pull using rebase.

**Comment by jaimefortega** [comment]
I also have a problem with just pull.

**Comment by Siilwyn** [comment]
Confirmed at Ubuntu 14.04. Both git pull and git pull using rebase.

**Comment by uZer** [comment]
Hi,
Same issue here
Atom 1.2.4 + Plugin git-plus 5.6.6
Windows 10
git 2.6.3.windows.1

Regards,

**Comment by teefax** [comment]
A possible fix for this should be in #342

**Comment by igorsousa-b** [comment]
Since 5.6.10, it now pulls but does so twice every time.

**Comment by jaimefortega** [comment]
That's strange. In my case, it pulls just once. Are you using the 1.2.4 version of Atom? I've also reinstalled my entire OS, because I had a problem with my HDD. Now, everything works fine. Maybe it's pulling from two branches.

**Comment by jaimefortega** [comment]
This bug was fixed in git-plus 5.6.10. I'm closing the issue.
