### ISSUE TITLE
Windows 10 x64, Atom 1.2.4.Push and Pulls not working. 

### ISSUE THREAD

**Issue by damianpirchio** [akonwi/git-plus#335]
First of all, sorry about my poor english level. I would try to tell you my problem.

I was reading all the issues referred to pull/push problems, ssh authentications, etc. 

My situation: 
1 - User email and name configured.
2 - Git path added to windows environment variables.
3 - SSH keys tested and working ( I've followed this tutorial https://help.github.com/articles/generating-ssh-keys/)
4 - Pulls/Push working perfect from github desktop, powershell, cmd, bash.
5 - My git config:

[core]
	bare = false
	filemode = false
	symlinks = false
	ignorecase = true
	logallrefupdates = true
[core]
	repositoryformatversion = 0
[remote "origin"]
	url = https://github.com/damianpirchio/inmobiliaria.git
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

5 - Problem detected when i'm using atom's git-plus plugin:

If a make a pull, the output console says:
---------------------------------------------------

fatal: Invalid refspec '[object Object]'

If a make a push:
----------------------

github --credentials get: github: command not found
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

I don't know what else to try. I know that this is a repeated issue, I would appreciate your help.
Thanks.

**Comment by tmaiero** [comment]
Same issue here except I am on windows 7.  

Love the package and use it for everything but a push a pull from our remote repo.  


Besides the Windows 10/7 difference exact same errors as the op.

If there is any additional info someone needs to help with this feel free to post and I will get it to you.

**Comment by akonwi** [comment]
The problem with pulling should have been fixed with pull request #342. 

As for the error when trying to push, I'm not quite sure what that is. Why does the shell think 'github' is a command? Is your path to git correct in the package settings?

**Comment by akonwi** [comment]
This is the same issue as #336 except that @damianpirchio, you have ssh setup. You should probably change the url in your config for remote origin to "git@github.com:damianpirchio/inmobiliaria" so it uses ssh to interact with the remote rather than https

**Comment by damianpirchio** [comment]
Thanks @akonwi  the pull problem was fixed with the last update and then i've changed the url in my config for remote as you said, and everything works fine now.

**Comment by akonwi** [comment]
:+1:
