### ISSUE TITLE
https problems

### ISSUE THREAD

**Issue by zacharyaugustine** [akonwi/git-plus#336]
the package seems to shell out to whatever git I have installed, so why won't it work with https? Git works fine in Bash. I used credential.helper in Git Bash, too. 

In Atom, I can add and commit and all that, but I get these errors on push:

> bash: /dev/tty: No such device or address
> error: failed to execute prompt script (exit code 1)
> fatal: could not read Username for 'https://github.com': Invalid argument.

**Comment by zacharyaugustine** [comment]
I was successful using by creating an OAuth token, then using changing my repo's git config in Bash using: 
> git remote set-url https://{token}@github.com/username/project.git

However,  I will need to do this for each repo, which is a big annoyance. Do you have any workarounds?

**Comment by zacharyaugustine** [comment]
The solution was only temporary. I have detailed the problem further and my reluctance to use ssh here:

http://stackoverflow.com/questions/33993304/git-remote-url-automatically-resets

**Comment by akonwi** [comment]
This package is designed with a bias for ssh when it comes to interacting with a remote repository. I'm not sure why ssh would brick your local git functionality. 

Right now, the package won't ask for your credentials like it does in the terminal. That is something that will need to be implemented for non-ssh users

**Comment by akonwi** [comment]
linking this to #335
