### ISSUE TITLE
Change position of notification popup

### ISSUE THREAD

**Issue by xoxys** [akonwi/git-plus#344]
Hi,
is it possible to change the position of the notification popup from "top left" to "bottom left"? 
![unbenannt](https://cloud.githubusercontent.com/assets/3391958/11725257/05b0770a-9f79-11e5-873e-b5a1fcc57625.png)
The popup overlays the input box for the commit description (see screenshot). So you have to wait or close it every time by hand. Maybe it is possible to move the popup to the bottom. Personally, I would prefere to remove notification popups completely and replace it with status bar notification.

Thanks for your great work

**Comment by akonwi** [comment]
As far as I know, there isn't a straightforward way to change notification location. I use the "Atom Material" theme which stacks notifications from the bottom. There is an issue requesting status-bar notifications in the atom package -> [here](https://github.com/atom/notifications/issues/14). You may want to +1 that maybe. I'd like to contribute to making that a reality if I ever get a chance

<img width="1440" alt="screen shot 2015-12-14 at 11 29 44 pm" src="https://cloud.githubusercontent.com/assets/2013804/11802095/a0889e80-a2ba-11e5-91a4-2faf9410a242.png">

**Comment by crshd** [comment]
I'm having the exact same issue, it's incredibly irritating. And no, there is no way to change the notification position (except for setting it in styles.less, or using a UI theme).

Maybe a good alternative would be to split the commit buffer down instead of right?

**Comment by laughedelic** [comment]
:+1:

**Comment by akonwi** [comment]
@crshd @xoxys There is a setting to change which direction the commit and diff panes open in.

**Comment by crshd** [comment]
Oh, found it. That's great, now the popup doesn't bother me at all, anymore.

**Comment by max-mykhailenko** [comment]
Maybe I can do this with css changes in atom `styles.less`?

**Comment by natedunn** [comment]
I got the notifications set to the bottom right by updating the styles.less file with this:

```
atom-notifications {
  top: auto;
}
```

@max-mykhailenko

**Comment by akonwi** [comment]
I'm closing this because it's more of an atom issue. The solutions we have are to use themes or edit our local `styles.less`
