### ISSUE TITLE
ctrl-shift-A p for commit and push not working

### ISSUE THREAD

**Issue by evilebottnawi** [akonwi/git-plus#345]
Last version atom and last version git-plus. After press this keystroke atom behaviour as if I had pressed ctrl-shift P and show Command Palette

**Comment by themccallister** [comment]
Having the same issue. However, I'm using cmd shift H for Mac with the latest version of Atom. Editor locks up and does not provide the commit_message pane.

**Comment by IgnitedCoder** [comment]
Same issue here... cmd shift H -> commit -> Atom is done for, it just hangs!

**Comment by akonwi** [comment]
For some reason I can't replicate these problems with a newly installed version of the package
