### ISSUE TITLE
Updated Atom

### ISSUE THREAD

**Issue by IgnitedCoder** [akonwi/git-plus#347]
Since updating Atom to the latest version when I do a commit Atom hangs and become unresponsive. I've tried updating package dependancies but that fails every time. Please look into this, Atom is awesome. 

Platform: 
Mac El Capitan
Atom 1.3.1

**Comment by akonwi** [comment]
I'm unable to reproduce this. I'm also using Atom 1.3.1. I'd suggest re-installing atom

**Comment by IgnitedCoder** [comment]
http://www.screencast.com/t/V5i3vq13K - Here's what happens. hope this helps.

**Comment by akonwi** [comment]
That's really odd. I can't imagine it's a conflict between packages. Have you tried re-installing atom?

**Comment by coderstephen** [comment]
I am experiencing this issue as well, and I am not entirely sure what the cause is.

**Comment by coderstephen** [comment]
Update: Found the culprit. Whenever the [`atom-autocomplete-php`]() package is enabled, it causes "commit" to freeze Atom.

The relevant issue is https://github.com/Peekmo/atom-autocomplete-php/issues/212, which turns out to actually be an issue with Atom: https://github.com/atom/atom/issues/10060.

**Comment by akonwi** [comment]
Great! I hope that fix enters the official branch soon

**Comment by Peekmo** [comment]
Hello,

This issue can be closed :+1:

**Comment by akonwi** [comment]
Great! Thanks
