### ISSUE TITLE
Git Commit causes tab change

### ISSUE THREAD

**Issue by pdxwolfy** [akonwi/git-plus#354]
Every time I do a commit, the current tab is set to the leftmost open tab. Can Git Plus be modified to not change the current tab?  TIA.

**Comment by akonwi** [comment]
Would it be possible to show me a clip of this? Also are there any errors in the dev console?

The package tries to go back to your active tab before the commit message

**Comment by pdxwolfy** [comment]
Hi akonwi,

I'm attaching a clip. Note that there are no console messages - not even an info message.
[badtab.zip](https://github.com/akonwi/git-plus/files/72561/badtab.zip)

**Comment by pdxwolfy** [comment]
Actually, it turns out that there is a console message that appears immediately after I open Atom:

/Users/wolfy/.atom/packages/tree-view-git-branch/lib/main.js:66 Cannot read property 'classList' of null TypeError: Cannot read property 'classList' of null
    at getProjectRootEl (/Users/wolfy/.atom/packages/tree-view-git-branch/lib/main.js:65:12)
    at /Users/wolfy/.atom/packages/tree-view-git-branch/lib/main.js:54:29
    at process._tickCallback (node.js:368:9)(anonymous function) @ /Users/wolfy/.atom/packages/tree-view-git-branch/lib/main.js:66

**Comment by akonwi** [comment]
The error in the console is coming from the tree-view-git-branch package. 

That behavior is really odd though. There isn't anything that changes the tab. It simply saves a reference to the current pane. Which version of atom are you using?

**Comment by pdxwolfy** [comment]
Version 1.3.2

**Comment by pdxwolfy** [comment]
It looks to be some sort of conflict with another package: tab-smart-sort - if I disable that package, the tab change does not occur. As to which of the two packages is actually changing the tab, though ... Git-Plus processes all the modified files, but probably shouldn't need to change the tab, and the tab sorter is only supposed to do something when opening a file. I'll report the issue to that package's maintainer too.

**Comment by akonwi** [comment]
Interesting. I don't see anything in that package's code that could conflict with mine. I do notice that it makes a slight change to the prototype of atom's Pane class but it doesn't seem to be at all related to changing the active tab. 

I installed that package myself and this 'bug' only happens when the `Place Special Tabs On Right` setting is set to true.

**Comment by pdxwolfy** [comment]
I tried turning off that setting, and the only difference I see is that the first tab I opened gets selected, not the left-most tab. Weird.

**Comment by pdxwolfy** [comment]
Confirming that this fix seems to the trick. Thank you

**Comment by akonwi** [comment]
Glad to hear it! :+1:
