### ISSUE TITLE
Diff - Editor is not responding

### ISSUE THREAD

**Issue by tststs** [akonwi/git-plus#355]
As the title says, the editor is unresponsive every time i trigger `Diff` via the package menu.
Caused by any file that has changes.

Nothing is thrown before the editor is becoming unresponsive. Just the dialog with `keep waiting` and `close` appears after some time.

- Atom 1.3.2
- git-plus 5.8.2
- OSX 10.11.2 (15C50)

**Comment by akonwi** [comment]
I can't reproduce although you may be able to do some debugging for me. Take a look at [this file](https://github.com/akonwi/git-plus/blob/master/lib/models/git-diff.coffee) and maybe you can spot something that could be causing the problem. I'd also suggest, opening that file locally and adding some breakpoints to see where the problem starts

**Comment by akonwi** [comment]
I did notice there was an unresolved promise when there were no diffs to show. I'm not sure that was the problem though because it should have had the same effects for everyone

**Comment by tststs** [comment]
Sure thing. It's getting late here, so i'll have a look at this tomorrow.

If there are no diffs to show, the info notification pops up correctly and everything is working fine. It seems it only happens if there are diffs.

I'll come back to this tomorrow.

Greetings from Berlin.

**Comment by tststs** [comment]
It is caused by this line of code: [splitPane.coffee](https://github.com/akonwi/git-plus/blob/master/lib/splitPane.coffee#L13).

The editor gets unresponsive if the returned method from directions[splitDirection] is executed.
In this case it is:

```javascript
splitPane.coffee:14 () {
  return pane.splitRight(options);
}
```

After further investigation, the editor only is becoming unresponsive if `options = { copyActiveItem: true }` is set. If i set `options = { copyActiveItem: false }` it opens the pane (with no content) but the editor is not becoming unresponsive. Maybe that helps.

**Comment by tststs** [comment]
This is the content of the `atom_git_plus.diff` file.
The text editor with this content pops up right before the editor gets unresponsive.

```
diff --git a/www/js/controllers.js b/www/js/controllers.js
index 46c98fe..a48840d 100644
--- a/www/js/controllers.js
+++ b/www/js/controllers.js
@@ -16,6 +16,7 @@ angular.module('xxxxxx.controllers', [])
  this.goTo = function (state, params) {

    $state.go(state, params || {});

  };

  this.init();
```

**Comment by akonwi** [comment]
This does help a bit. Issue #354 is related to this splitPane module as well. I'm working to get rid of that module and have a more direct way of splitting the panes

**Comment by tststs** [comment]
:+1:  works like a charm

**Comment by akonwi** [comment]
Awesome!
