### ISSUE TITLE
Rename 'Changelog.md' to 'CHANGELOG.md'?

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#358]
Hello

Atom can list the contents of the changelog in the package details. However, this doesn't seem to be happening. I think this may be due to the fact that the Changelog file isn't fully upper case.

Thanks in advance

**Comment by akonwi** [comment]
I'm not sure that's true. I can see the changelog

<img width="1440" alt="screen shot 2015-12-30 at 12 49 06 pm" src="https://cloud.githubusercontent.com/assets/2013804/12054755/1224607a-aef4-11e5-9a75-9fab9e34c8be.png">

**Comment by jsg2021** [comment]
MacOS's filesystem is case insensitive. I believe on linux it won't load.

**Comment by Gert-dev** [comment]
Yes, that's correct, I am indeed on Linux, Atom must be checking for `CHANGELOG.md` internally and on case insensitive filesystems it will still correctly resolve if the casing is differeent.

**Comment by akonwi** [comment]
Ah gotcha. That change will be in the next update
