### ISSUE TITLE
How to use  git plus rebase origin branch 

### ISSUE THREAD

**Issue by m927259903** [akonwi/git-plus#361]
First . I like `git-plus` very much. It greatly enhance efficiency of my work.
However. I don't know how to use `rebase`  rebase my origin branch to local branch
liked

``` git
git rebase origin/master
```

THX

**Comment by m927259903** [comment]
No people help me ? 
sounds bad

**Comment by akonwi** [comment]
Why don't you use the 'Pull Using Rebase' command?
