### ISSUE TITLE
Does not work with ssh-agent

### ISSUE THREAD

**Issue by LukasMa** [akonwi/git-plus#363]
At first: I'm on windows, which could be the problem (Win 10 Pro, 64bit)

I don't know if this is a bug or just not implemented yet. However, I'm not able to use git-plus when I protect my default identity (id_rsa) with a passphrase. The key is added to the agent, and executing `ssh-add -l` shows me valid output (key is loaded).

It's no problem to open a command prompt, navigate to my local repo and execute a push/pull/fetch/whatever. But git-plus won't work.

Is this issue on my side?

**Comment by ranietots32** [comment]
Same problem here. This has been an issue with git-plus for a long time now, when I first tried git plus push it just doesn't work and it doesn't ask me for my password like it would on the terminal. The same goes for any git command that connects to the remote repo.

Some of the submitted issues say the issue only happens in Windows and how it handles SSH. 

I just really really REALLY hope this is fixed eventually. My workflow in Atom would be flawless if this was fixed.

**Comment by bobum** [comment]
is your remote https?  if so need to switch it to ssh

switching the remote from http to ssh did it or me - it was crated as https...needs to be SSH for git-plus

command looks like this:
`git remote set-url origin git@github.com:path/to/my/repo.git`

**Comment by ranietots32** [comment]
No sir, I've always used ssh for all my remote repos.

**Comment by LukasMa** [comment]
Same here. Used ssh all the time.

**Comment by akonwi** [comment]
The package was created with the assumption that your remote setup uses ssh and doesn't require a passphrase and I only recently added that claim to the README. 

I've been thinking about how to go about implementing this but I haven't had a chance to get started.

I'm closing this and referencing #336 because it is essentially aiming for the same result

**Comment by ranietots32** [comment]
If you created this with the assumption that your remote setup uses ssh and doesn't require a passphrase ... then can you at least point us to a page/guide/article on how to set up a passwordless SSH on Windows?

**Comment by akonwi** [comment]
https://help.github.com/articles/generating-an-ssh-key/#platform-windows

**Comment by WLyKan** [comment]
I met the same problem because 

> Enter passphrase for `key` '/Users/***/.ssh/id_rsa'

**Comment by WLyKan** [comment]
i solved it.
@raniesantos 
check it out https://help.github.com/articles/working-with-ssh-key-passphrases/#saving-your-passphrase-in-the-keychain
