### ISSUE TITLE
Allow Copy/Paste from Console Output

### ISSUE THREAD

**Issue by Nemesis9765** [akonwi/git-plus#366]
As a user, after pushing a branch, I would like to be able to select and copy text from the console output window.  If it requires the window to be pinned prior to having that functionality available is fine.

<img width="453" alt="git_plus_console" src="https://cloud.githubusercontent.com/assets/1054015/12181515/4cf66c20-b548-11e5-9bb7-f98f70652261.png">

**Comment by ViBiOh** [comment]
:+1:

**Comment by akonwi** [comment]
Unfortunately, that isn't something I can control. Atom doesn't allow selection of text outside of instances of text-editor elements. If you notice you can't select and copy text in a notification or other ui elements.
