### ISSUE TITLE
Add commit without make a new pane

### ISSUE THREAD

**Issue by miftahafina** [akonwi/git-plus#367]
Can we add a commit without automatically make a new pane? Because I can't see the top of line in COMMIT_EDITMSG when I open many file in atom. See pic below.
![23](https://cloud.githubusercontent.com/assets/5361135/12200597/620d10f4-b652-11e5-9ee1-1f9e921b429b.png)
I have to wait until its notification is dissapear and it takes some seconds.

**Comment by akonwi** [comment]
You can either change the direction in which the pane opens or disable the "Open in pane"
