### ISSUE TITLE
Not pushing the changes to bitbucket

### ISSUE THREAD

**Issue by ramanandapanda** [akonwi/git-plus#368]
Hi I tried to add, commit and push to my bitbucket repo. It should ask for my password but nothing happened it was showing pushing changes.... and hiding the popup.
And I found its not commited. To commit it I needed a pull request again and again a push manually in terminal.

**Comment by tannerellen** [comment]
I believe you need to use ssh to push. I ran into this problem too using https for my remote as https requires a password. Even if you store the password in the keychain it won't work. Switch your remote to ssh and it should work great. Keep in mind that you will need to create an ssh key for that to work: https://help.github.com/articles/generating-ssh-keys/

**Comment by bobum** [comment]
switching the remote from http to ssh did it or me - it was crated as https...needs to be SSH for git-plus

command looks like this:
`git remote set-url origin git@github.com:path/to/my/repo.git`

**Comment by akonwi** [comment]
refer to #336
