### ISSUE TITLE
Use atom's new scoring algorithm for git-plus:menu

### ISSUE THREAD

**Issue by kausters** [akonwi/git-plus#372]
A while ago Atom introduced a new, much improved [sorting algorithm](http://blog.atom.io/2015/10/29/atom-1-1-is-out.html) for its Command Palette and other menus by switching to [fuzzaldrin-plus](https://github.com/jeancroy/fuzzaldrin-plus), and recently made it the [default](https://github.com/atom/command-palette/commit/b2167ae17334f2bd2c262009f3e70f6030356b30).

I wish the Git Plus Menu (`Cmd+Shift+H`) used the same algorithm so, for example, entering `S` into the menu's search field would show `Show`, `Status`, `Stage` etc. on top instead of `Tags` and `Push`. This would make it more usable and in-line with the current Atom defaults.

**Comment by akonwi** [comment]
:+1:
