### ISSUE TITLE
 The push command does not work

### ISSUE THREAD

**Issue by arthurmteodoro** [akonwi/git-plus#373]
The push command does not send the files to the GitHub , until the message appears , but is not completed

**Comment by tannerellen** [comment]
I believe you need to use ssh to push. I ran into this problem too using https for my remote as https requires a password. Even if you store the password in the keychain it won't work. Switch your remote to ssh and it should work great. Keep in mind that you will need to create an ssh key for that to work: https://help.github.com/articles/generating-ssh-keys/

**Comment by bobum** [comment]
switching the remote from http to ssh did it or me - it was crated as https...needs to be SSH for git-plus

command looks like this:
`git remote set-url origin git@github.com:path/to/my/repo.git`

**Comment by akonwi** [comment]
I'm closing this because it seems to be a duplicate. 

As @tannerellen and @bobum have suggested, using ssh and having it set up without a requirement of entering credentials will work. Otherwise, there isn't support for https
