### ISSUE TITLE
Windows: run without git.exe in the path

### ISSUE THREAD

**Issue by stijnsanders** [akonwi/git-plus#375]
Is there a way to replace "git" with the full path to git.exe in any command calls? (e.g. with a configuration setting?)

I have git installed, but don't have the path of git.exe listed in the PATH environment variable, and don't want to. Calling git with the full path works in normal use.

What I now get is an error

    'git' is not recognized as an internal or external command, operable program or batch file.
    'git status --porcelain --untracked-files=all' exited with error code 1

**Comment by akonwi** [comment]
There's a field in the package settings to enter the full path to your git executable. It defaults to 'git' if left blank
