### ISSUE TITLE
add flag for git commit --verbose

### ISSUE THREAD

**Issue by growlsworth** [akonwi/git-plus#378]
I know this is really opening up a major can of worms for all different options and flags. Personally, I like reviewing my full commit when writing my commit message. Perhaps others would see value in this simple flag. Is there a way to do this in the current settings?

Thanks!

**Comment by akonwi** [comment]
No there isn't a way to do it. I have actually tried to push this feature twice now but have ran into issues. 

I'm going to close this and reference the original issue about this.

See #90
