### ISSUE TITLE
How to git add a folder

### ISSUE THREAD

**Issue by chrisduong** [akonwi/git-plus#379]
Hello,

I cannot figure out the way to use the *"Git-Plus shortcut"* to "git add" a folder. 

For e.g. whenever I rename a file (This mean I have deleted a file and created a new file), in "Tree View", Atom recognized the change and highlight the folder. I have to open the terminal and run the command " git add <target folder>" before I'm able to use the shortcut "shift + cmd + C" to commit the change.

**Comment by akonwi** [comment]
if you have the file open as the current editor, Git Add will stage it. Otherwise calling Git Add All will stage everything. You could also use the Stage Files command to select which files to stage.

**Comment by chrisduong** [comment]
Nice,  thanks.  I had done that before but haven't figured it out.
