### ISSUE TITLE
Uncaught BufferedProcessError: Failed to spawn command `git`. Make sure `git` is installed and on your PATH

### ISSUE THREAD

**Issue by BottieYOYO** [akonwi/git-plus#387]
Hi!
When I try to run Difftool for file which placed not in root of git project (example: my_project/js/app/main.js) I get this error:

> Uncaught BufferedProcessError: Failed to spawn command `git`. Make sure `git` is installed and on your PATH

git is present in my PATH.

When I run it for file that placed in root of project (example: my_project/index.html) everything is OK. 

Atom 1.4.0
Ubuntu 14.04

What's wrong? Can u fix this?

**Comment by dahjelle** [comment]
I see the same issue with Atom 1.4.1, Mac OS X 10.11.2, Git Plus 5.12.1. I also tried hardcoding the path to git in the configuration and the issue persisted.
