### ISSUE TITLE
Stage hunks from within file?

### ISSUE THREAD

**Issue by martinklepsch** [akonwi/git-plus#388]
Often it's handy to stage things with `git add --patch` to split things up into multiple commits. Does this plugin provide means to stage only the current hunk?

**Comment by martinklepsch** [comment]
I just found "Stage Hunk" which allows this kind of thing. Besides the selection mechanism already present it'd be great to stage the hunk the cursor is currently in.

**Comment by akonwi** [comment]
Issue #92 raised this but you've updated the title so I'm going to make this the official thread for this feature since.

**Comment by akonwi** [comment]
#246 is a request for something very similar to this. I'm going to mark this as a duplicate and #246 can be the source for this
