### ISSUE TITLE
Not pushing/ committing

### ISSUE THREAD

**Issue by OgdenStephanie** [akonwi/git-plus#390]
My GitPlus does not seem to be working anymore and I'm hoping you might be able to help me out ASAP?  It worked beautifully for about 2 weeks, now it won't do anything.  I have double checked to make sure I'm connected to the correct repository.  There are no errors that appear, when I push add or commit, just nothing happens.  I have updated to the most recent update.  Nothing.
Any ideas?

**Comment by akonwi** [comment]
Open up the dev console in atom and try to execute a git command. There should be an error or something logged in the console. Let me know what you see. I think that will be helpful

**Comment by scott-wilson** [comment]
I think this is related, but I'm getting the following error in the terminal (Windows 7 64 bit, latest Atom and git-plus):

```
Uncaught (in promise) fatal: Unable to create 'C:/repo/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

One thing I noticed is a restart of Atom fixes. I'm assuming the index.lock is getting cached somewhere.

**Comment by ludberg** [comment]
I'm also experiencing this issue. I do Add All, Commit and Push. No errors and it looks like everything went fine but it didn't push (in my case to Github). 

I'm not seeing any errors.

**Comment by AlexNPavel** [comment]
Same issue here. Popup says "Pushing..." then disappears and nothing happens
