### ISSUE TITLE
git diff all opens 2 tabs for same file

### ISSUE THREAD

**Issue by michaelaye** [akonwi/git-plus#391]
I currently have only one file in my project with a change in the workfiles. However, when I launch "git plus diff all" via the command palette, it opens 2 tabs for the same file:
![screenshot 2016-01-31 17 13 15](https://cloud.githubusercontent.com/assets/69774/12706263/f6f52d12-c83d-11e5-9733-5beed6aeafe2.png)

Interestingly, when I close one of the tabs, the other one closes as well.

**Comment by akonwi** [comment]
You may have another package installed that could be causing this behavior.

What else do you have installed?
