### ISSUE TITLE
Feature Request: Add Commit Description with Commit Message

### ISSUE THREAD

**Issue by hemanthg4** [akonwi/git-plus#393]
Not sure if this is already possible.

It would be great if we can add a Commit Description just like int he Github Desktop App, and Git via terminal. 

Description on commit helps large teams communicate better.

Attached Screenshot of Github App Example.
<img width="275" alt="screen shot 2016-02-05 at 10 02 53 pm" src="https://cloud.githubusercontent.com/assets/1073955/12852340/7437e66a-cc54-11e5-9ac6-dddd3f0d65a5.png">

Thanks in Advance.

**Comment by akonwi** [comment]
The description is everything after the first line of your commit message. Just start a new line and that will be the description.
