### ISSUE TITLE
Git Commit

### ISSUE THREAD

**Issue by mgibson80380** [akonwi/git-plus#394]
When I select Git commit from the packages menu or use short cut ctrl+shft+x I get 2 commit panes pop up, when I close one it closes both. When i type in one the commit message appears in both. When I save the commit 1 goes through then I get an index.lock. I have delete this file every time before I can commit again any git application such as this one and source tree.

**Comment by akonwi** [comment]
Is this still occurring?

**Comment by mgibson80380** [comment]
No now it comes up with a nice pop up at bottom of the screen .All seems to be fixed, thanks.
