### ISSUE TITLE
Git plus: Log shows only 25 positions

### ISSUE THREAD

**Issue by Nosenation** [akonwi/git-plus#395]
Hey,
I found that git plus: log shows only 25 commits on enter. When you click one commit, then it will load rest, but not on enter. 
![image](https://cloud.githubusercontent.com/assets/1431712/12919442/5c660380-cf44-11e5-9f6a-aa796a9bb55e.png)

Btw: Is there option to disable Git plus: Log (not to show on list in menu etc.) ?

**Comment by akonwi** [comment]
Loading more commits after the click is actually a bug. The intention is to only load more commits as the list scrolls towards the bottom to simulate an infinite list. It seems that a click in your situation, triggers some scroll event. I'm actually having a tough time replicating this. Can you make a gif or video?

And no there is no option to disable the command.

**Comment by Nosenation** [comment]
Now it looks ok.

**Comment by Gert-dev** [comment]
There seems to be a different issue attached to this one: only a fixed set of items are loaded when the log is opened, but if your screen is high enough, there is no scroll bar and thus the point at which infine scrolling (the loading of the next "page") kicks in can never be reached.

The only solution to this is to temporarily make the Atom window smaller, scroll down to the bottom to instigate the next load and then resize the Atom window again. Perhaps it would be a solution to let the amount of items depend on the editor viewport size?
