### ISSUE TITLE
Not detecting new remote branches

### ISSUE THREAD

**Issue by ludberg** [akonwi/git-plus#398]
I created a new remote branch and was going to switch to in in Atom. However, when running 'Checkout Remote' I could only find one branch (master). 

If I did git run >> "branch -r" I also found one branch. 

After I opened up a console (I'm using Win 8.1) and did git branch -r (found two) Atom and git plus was able to find it using Checkout Remote. 

Caching issues?
Config error on my end?

**Comment by akonwi** [comment]
Hmm... I'm not sure why running the command in the console returned a different result. 

I'm not sure this is a bug in the package. The `-r` flag as I understand it from git docs, shows the remote "tracking" branches. So if I create a new branch remotely, I need to fetch/pull to update the local repository so it will track the new branch.
