### ISSUE TITLE
Adding deleted files with git add command

### ISSUE THREAD

**Issue by codewp** [akonwi/git-plus#399]
In sublime text git there is a feature that list changed files in git add command output like below picture it's benefits is that developer can stag deleted files too. Can you please add this feature to Atom git-plus?

![atom-git-add](https://cloud.githubusercontent.com/assets/10684451/13028565/1ac0c1da-d288-11e5-87a3-56a3b28cf2f2.png)

**Comment by akonwi** [comment]
You can accomplish this with the 'Stage Files' command
