### ISSUE TITLE
In progress indicator for more events

### ISSUE THREAD

**Issue by simon-ls** [akonwi/git-plus#401]
This is very small, but I think it would be a nice UX addition.

During a push, a notification pops up to say "pushing...". It would be good if this type of behaviour occurred during other operations. For instance when I use the "add all" command there is a good few seconds before the success message appears. During this time a notification could be displayed, with the message "adding..."

**Comment by akonwi** [comment]
I wonder if that delay you experienced with the add all was related to #415
