### ISSUE TITLE
Issue with git push

### ISSUE THREAD

**Issue by acegautam** [akonwi/git-plus#402]
GitPlus is awesome, and am loving it. But I did see an issue with push specifically when I had merge conflicts. I made a change in a file directly in the remote repo, and made a different change in the same file locally.

Tried pushing, expected it to reject / fail, asking me to pull first. But it didn't do anything. Asked for a commit message, showed up message "pushing.." and then just faded off. Of course, the push was not done.

I am planning to use it soon on production, but with this bug, I can't unfortunately. Can you help? Thanx. Am using version 5.13.0 on Atom(Win 7).

Cheers,
Gautam

**Comment by feakuru** [comment]
same here! seems the handling of a situation where not only you push to the repo hasn't been built into the package :(

**Comment by akonwi** [comment]
I just pushed an update (5.22.0) that should fix this.
