### ISSUE TITLE
Commit closes panes

### ISSUE THREAD

**Issue by redbassett** [akonwi/git-plus#405]
(Potentially related to #394?)

I typically use Atom with a two-column view. When I run a `commit` command, the commit message editor opens in my current pane, however when I save the message, it is closed and I am left with a single pane.

**Comment by akonwi** [comment]
Can you verify if this is still a bug?

**Comment by akonwi** [comment]
I'm closing this seems it's stale

**Comment by redbassett** [comment]
Yes, the issue is still occurring in version `5.27.0`. Steps to reproduce:

Open two panes, side-by-side. In the left, open a file, make changes, and save. Stage changes in git. Select the right pane (with no tabs open). Run the commit command from `git-plus` and type in a message. Save, the commit tab and right pane will close.

**Comment by akonwi** [comment]
Got it. I've figured out how to reproduce it and I now understand why it's happening. I'll try to push a fix in the next release.

**Comment by akonwi** [comment]
@redbassett So there's a caveat to making this work I think. Atom has a core setting labeled 'Remove Empty Panes', which you will need to disable along with the 'Open In Pane' option of this package.

**Comment by redbassett** [comment]
I was worried that there was a core setting conflicting with it. Does this setting fix the issue completely, or does this still require a patch from you?

**Comment by akonwi** [comment]
There are changes I need to make as well. I'll push them tonight potentially and tomorrow at the latest.
