### ISSUE TITLE
Issue using difftool with Kaleidoscope on OS X

### ISSUE THREAD

**Issue by CarlosZG** [akonwi/git-plus#406]
I use Kaleidoscope as difftool and it works fine when I invoke it via command line. However, when I try to use Git Plus on Atom Kaleidoscope is not launched to show the diffs. Thanks for your attention.
Best regards,
Carlos

**Comment by akonwi** [comment]
See the [problem here](http://stackoverflow.com/questions/6412516/configuring-diff-tool-with-gitconfig) and [solution here](http://stackoverflow.com/questions/255202/how-do-i-view-git-diff-output-with-a-visual-diff-program).

I don't use difftools. That seems like what you're facing though
