### ISSUE TITLE
Better handling of errors

### ISSUE THREAD

**Issue by surrealchemist** [akonwi/git-plus#407]
I just realized today that my work yesterday didn't get committed because of spacing errors. I had "space before tab in indent" message back from the server, but since the message after push is so short and I didn't have much sleep I didn't realize, or the message wasn't obvious enough.

I think it would be helpful to have errors handled differently than success, to at least allow me to set a different timeout on error if that would be possible.

Ideally, an option to leave the error open till I can read it would be preferred. Might also be handy if a commit fails you could have a button or something to reset. When I am pulling in new code that tends to have spacing issues a lot I end up running `git reset --soft HEAD^` and then fixing the file that errors out, add/commit/push again etc. till all the problems are fixed. Usually this ends up being faster to do on CLI, so it would be cool if there was better workflow for it.

**Comment by akonwi** [comment]
I don't really understand the spacing issues. Why don't you increase the timeout for the notification so it's longer? You can also toggle the visibility of the notification pane with the pin icon on the right side of the status-bar
