### ISSUE TITLE
Git add: select files dropdown list

### ISSUE THREAD

**Issue by lbronsdijk** [akonwi/git-plus#411]
It would be great to be able to select modified files within a dropdown list when using `git add`, like Git for Sublime Text 3 does.

See
![](http://f.cl.ly/items/2o1G0P0c02103X3L002J/Schermafbeelding%202016-03-02%20om%2015.49.49.png)
... and ...
![](http://f.cl.ly/items/3L3J1A14021P2Y03171s/Schermafbeelding%202016-03-02%20om%2015.49.53.png)

**Comment by yuvipanda** [comment]
`Stage: Hunk` seems to provide almost this functionality (except not for new files)

**Comment by akonwi** [comment]
The 'Stage Files' command does this actually.
