### ISSUE TITLE
Suggestion: Split pane direction should default to 'down'

### ISSUE THREAD

**Issue by emveeoh** [akonwi/git-plus#412]
I would like to offer a friendly suggestion that the 'Split Pane Direction' setting should default to 'Down' instead of 'Right'. 

If there are other notifications present, they block the window for commit comments. You can't see what you are typing and have to exit out of all notification windows first. As you know, notifications default to that same Upper-Right location.

![screen shot 2016-03-03 at 2 44 02 am](https://cloud.githubusercontent.com/assets/16849690/13487728/2ad722ce-e0ea-11e5-842a-050c49051bcd.png)

**Comment by cortner** [comment]
+1: This would be much appreciated
