### ISSUE TITLE
Can't Push

### ISSUE THREAD

**Issue by Crazypkr1099** [akonwi/git-plus#413]
I literally tried everything to fix this problem. When I try to push after I add and commit, I get the error: 
github -- credentials store: github: command not found
To (SSHURLHERE)

I am using SSH and I have the key set up properly... If im doing this wrong could you please make a video on how to do this and connect it to atom. That would be a great help.

**Comment by Xzq70r4** [comment]
Same issue on Windows 10

**Comment by cbuteau** [comment]
I am also having this problem.
I have resorted to using the command line for pushes.
This is difficult for me because I am learning Git at the same time.

**Comment by SolarPolarMan** [comment]
Same. Thinks it's pushed. It ain't.

**Comment by cbuteau** [comment]
Lately it has been working and the atom package is what I have been using.
I actually used it's very nice interface to clean up my unused files so my code coverage would go up.

This helps me because although I get the concept of git the amount of command line houdini is HUGE.

**Comment by cbuteau** [comment]
On a previous project this finally worked.

On a new project I still have to go back to command line to do the push.
It's like it doesn't know that it fails the push/

**Comment by saidmoya12** [comment]
Always do

add all
Commit with message
pull (auto merge)
if merge errors can use Merge conflicts plugin
push

if problem persist send screenshot

**Comment by rcassani** [comment]
In order to have the **PUSH** working, you need to add the `GitHub.exe` (not `git.exe`) path to Environment Variable **PATH** and restart Atom.

This is how I found `GitHub.exe` path (in Windows)
1. Run GitHub desktop
2. Open the Task Manager, right click on GitHub (32 bit) process and select Open File Location

In my case GitHub.exe was in the folder `C:\Users\cassani\AppData\Local\Apps\2.0\H35QN991.JQW\RZJQ033T.E6B\gith..tion_317444273a93ac29_0003.0000_eb093b9833279bd4\`

**Comment by joshuadavidson** [comment]
I've been having this issue as well. I just added the GitHub desktop.exe path and it works like a charm. Thanks @rcassani!

**Comment by cbuteau** [comment]
Thanks @rcassani ...This resolved my problem too.
I had resolved to just do git push from the commandline.

I installed GitHub Desktop...added the exe folder to my path...bingo it works.

**Comment by akonwi** [comment]
I'm closing this since it seems like there's a solution. I'll link to this in the other thread related to pushing on windows

**Comment by cbuteau** [comment]
Add it to your documentation

**Comment by SolarPolarMan** [comment]
What about Linux users?

**Comment by akonwi** [comment]
@SolarPolarMan Is git in your path? If not run `which git` and paste the result into the Git Path field of the package settings
