### ISSUE TITLE
Git Commit and Push yields Git Status

### ISSUE THREAD

**Issue by pdxwolfy** [akonwi/git-plus#418]
When I do Cmd-Shift-Ap to commit and push, I get the commit editor as expected, and I can fill it in the appropriate commit info. However, when I save the result with Cmd-S, I get a commit-status window that says "No matches found".  The commit is saved and things are pushed - the commit status window is just an annoyance.

The issue is somewhat erratic in that it doesn't always happen, but it happens roughly 90% of the time. It doesn't appear to happen if I do Cmd-Shift-Aa

**Comment by pdxwolfy** [comment]
The "No matches found" thing also appears if I select File, Save via the menus, so it's apparently not related to key bindings.

**Comment by akonwi** [comment]
Is this still an issue? I can't reproduce it. If it is still a problem, we can reopen it.

**Comment by pdxwolfy** [comment]
I haven't seen the issue in a while, but can't confirm it is gone.
