### ISSUE TITLE
Add notification

### ISSUE THREAD

**Issue by albertosantini** [akonwi/git-plus#419]
`Git Plus: Add` adds the file and a green notification is displayed.
So far it is ok.

If I use the shortcut `Ctrl+Shift+A`, the shortcut suggested for `Add` command in the palette, I don't see any green notification.

I need to repeat the key sequence twice to see the notification or, for instance, using `Ctrl+Shift+X` to see the green notification and opening the COMMIT_EDITMSG pane.

It is like the latest green notification is hidden and showed only if there is another notification or event.

Any hint?

(With Atom 1.5.4 and Atom 1.6.0, git-plus 5.13.0)

**Comment by Gwasanaethau** [comment]
I have done some preliminary testing as this was annoying me too. It seems that after using `Ctrl+Shift+A`, `git-plus` is waiting for another keystroke. If you wait a few minutes and the press `a`, for example, you’ll get a message stating that all files have been added.

I have added a work-around on my local version by changing the shortcut from `Ctrl+Shift+A`, to `Ctrl+Shift+A z`. The adding of the files to staging then occurs immediately.

**Comment by albertosantini** [comment]
I am afraid something changed in Atom, because I noticed it from Atom 1.5.4.
I think Atom 1.5.3 was ok.

**Comment by bjonica** [comment]
I encounter this too. I noted a workaround in #415 that works for me, but it's definitely something that started happening sometime during the 1.5 or before the 1.6 version

**Comment by akonwi** [comment]
I'm closing this and marking as a duplicate. @bjonica has linked to https://github.com/akonwi/git-plus/issues/415 which has an explanation of what is causing this problem.
