### ISSUE TITLE
the package currently favors an ssh setup that doesn't expect to be prompted for credentials

### ISSUE THREAD

**Issue by shlomogoldstein** [akonwi/git-plus#420]
```
Also, the package currently favors an ssh setup that doesn't expect to be prompted for credentials in order to push/pull, .etc.
```

How do I setup my git / ssh to not ask for credentials ever more?

**Comment by akonwi** [comment]
[Here you go](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)

**Comment by shlomogoldstein** [comment]
I have done as written in your post (ssh-agent etc). It is still asking for my password. I am not using github, rather our own gitlab installation. What do I have to do?

**Comment by akonwi** [comment]
I don't know. I don't use gitlab. My best suggestion is look for help in their help documentations
