### ISSUE TITLE
Add support for gpg signed commits

### ISSUE THREAD

**Issue by AriaFallah** [akonwi/git-plus#427]
Currently fails throwing some error about `/dev/tty` because it can't password prompt the user.

**Comment by svagi** [comment]
More precisely
<img width="443" alt="screenshot 2016-04-14 23 18 26" src="https://cloud.githubusercontent.com/assets/1558135/14544046/6c9edee4-0297-11e6-93a1-af56d99ee5c9.png">

**Comment by aaronwest** [comment]
@akonwi - is there a workaround for this? I'd imagine more and more Atom users will be setting up Git to sign their commits now that GitHub [shows verified commits](https://help.github.com/articles/signing-commits-using-gpg/).

![verified-commits](https://cloud.githubusercontent.com/assets/231569/15549394/ee563834-2271-11e6-9263-b5df5975bbfa.png)

**Comment by AriaFallah** [comment]
@aaronwest 

If you're not so concerned about security, you can disable your password for you gpg key. That fixed it for me.

**Comment by svagi** [comment]
@AriaFallah Hmm, isn't security the whole point of signed commits? :)

**Comment by aaronwest** [comment]
> If you're not so concerned about security, you can disable your password for you gpg key. That fixed it for me.

Thanks for the response but I'd like to keep the PW on my key.

**Comment by AriaFallah** [comment]
@svagi 

Haha yes, but the gpg keys are stored on my computer, which only I use, so unless my computer gets stolen, no one else can use them. In that case, I have bigger problems, and I also can go on github and revoke the gpg key anyways.

**Comment by svagi** [comment]
## Workaround
Set `no-tty` in `~/.gnupg/gpg.conf` for running GPG non-interactively.

Ref: https://github.com/kemayo/sublime-text-git/issues/475

**Comment by niij** [comment]
@svagi 
Thank you.  This fixed the issue for me on git-plus v5.14.0 for Atom using GPG Keychain to unlock the key.  Would love to see a permanent fix for this.

    echo "no-tty" >> ~/.gnupg/gpg.conf

**Comment by vincentmorneau** [comment]
@akonwi Is this on the roadmap for a future release?

**Comment by akonwi** [comment]
Sorry I haven't been active on this issue. This is along the same lines as SSH. Because this package just creates a child process to execute git commands, it isn't interactive and won't prompt you for input. Right now the best you can do is use GPG Suite on Mac and GPG4Win on windows to store your passphrase so you don't have to enter it manually each time.

At this point, investigating a way to make the package interactive is not a priority for me. Anyone is welcome to do it though.
