### ISSUE TITLE
Allow git installations without path variable

### ISSUE THREAD

**Issue by JuanCAlpizar** [akonwi/git-plus#43]
I installed recently this plugin, working in windows 7 32 bits using atom 0.101.0, my git installation it's bound to the git bash, not to the PATH windows variable, hence when I try to execute the commands it throws the message

`"git" is not recognized as an internal or external command, operable program or batch file`

I looked into the plugin settings, but couldn't find any setting to setup git location. Is there a way to make it work in this case scenario?

**Comment by primAulia** [comment]
Hi @maschs,

What do you mean by "files under /lib". is it the directory under Atom main directories?

**Comment by akonwi** [comment]
@primAulia He's referring to the `lib` directory in `.atom/packages/git-plus/`. There is a setting now where you can enter the path to git though
