### ISSUE TITLE
How to start package on atom opening?

### ISSUE THREAD

**Issue by brunolemos** [akonwi/git-plus#430]
The package doesn't seem to be initialized with atom automatically.
Is there a way to do that?

Example, when I open atom:
![](https://s31.postimg.org/vyhs23dxz/Screen_Shot_2016_04_21_at_10_35_41_PM.png)

After I execute a Git Plus command, the package is initialized:
![](https://s31.postimg.org/forlz739z/Screen_Shot_2016_04_21_at_10_36_07_PM.png)

It's annoying me because I click on the branch name to change branches and it only works after I execute some command from git plus.

**Comment by akonwi** [comment]
This was fixed in version 5.18.0
