### ISSUE TITLE
Open GIT Bash(terminal) from Atom's Command Palette - Windows

### ISSUE THREAD

**Issue by sorcamarian** [akonwi/git-plus#432]
It would be great if we could open **GIT Terminal** from **Atom's Command Palette**, of course, in the current working directory.

I know there are plugins for adding a terminal into Atom, but for now, they are not as useful and fast as GIT Bash.

**Comment by akonwi** [comment]
This is a very specific feature and it doesn't fit in with the rest of the package's features. It seems like what you want is a terminal package for atom that supports Git Bash and I don't think this is the right place to make that request.

This isn't something I'd like to see in this package.
