### ISSUE TITLE
Encoded notification

### ISSUE THREAD

**Issue by wswebus** [akonwi/git-plus#433]
Hello

I have a notification problem. 
![111](https://cloud.githubusercontent.com/assets/16538668/14911659/79247b24-0dff-11e6-9dd3-615ec41686e0.jpg)

Any idea how to fix it? Test on other computer - works fine. 

Tried to reinstall plugin - no effect
Tried to reinstall Atom - no effect

OS: Windows 10 Pro x64

**Comment by VinkChenX** [comment]
+1...

**Comment by VinkChenX** [comment]
Enable the git command line , working now

**Comment by akonwi** [comment]
@VinkChenX can you provide the steps you took to enable the git command line?
