### ISSUE TITLE
Git Init not showing

### ISSUE THREAD

**Issue by parvinder30** [akonwi/git-plus#435]
I've just installed git plus in atom.As I tried to init my project in git plus, git init command is not there in the list.

**Comment by propertunist** [comment]
i have the same issue in fedora 23. i attempted to init my current project and the outcome was that a totally different project was initialised. it is possible that i somehow clicked on the wrong project... however, i now cannot initialise the correct project as the init option is not available. any idea why this is?

**Comment by akonwi** [comment]
Are you looking in the atom command palette or the git-plus command palette (which opens with cmd-shift-H)? Which options are available to you?  

In the default command palette, all the git-plus commands will be displayed but from this package's command palette, only the 'init' option should be available if the project is not a git repository.
