### ISSUE TITLE
Annoying sticky message won't go away

### ISSUE THREAD

**Issue by maasha** [akonwi/git-plus#438]
Adding and committing in Atom leaves this sticky notification that won't go away. Both on Mac and Linux.

<img width="448" alt="screen shot 2016-05-11 at 08 50 52" src="https://cloud.githubusercontent.com/assets/1158057/15172319/ac24b8fe-1755-11e6-9831-c4b510913c8d.png">

**Comment by mherodev** [comment]
I've also seen this pretty often, but I'm not certain how to reproduce it.

**Comment by akonwi** [comment]
Is this still an issue?

That sort of looks like a tooltip from hovering over the tab for the commit file. That's not something generated from this package.

**Comment by mherodev** [comment]
I've seen it once recently, but I cannot reproduce the bug and it's likely related to the smart tabs library rather than this plugin.

**Comment by maasha** [comment]
I still get this.

**Comment by akonwi** [comment]
@maasha Have you validated that this isn't because your mouse is hovering over the tab? The only tooltip this package creates is on the pin icon in the bottom right of the status-bar

**Comment by maasha** [comment]
Jup, it will not go away once there ...

**Comment by akonwi** [comment]
which theme are you using?

**Comment by maasha** [comment]
One Dark

**Comment by akonwi** [comment]
this is very odd. I'm honestly not sure what to do about this

**Comment by maasha** [comment]
The issue seems to have disappeared during some upgrade :o/ ?
