### ISSUE TITLE
Suggestion: Commit message syntax highlight

### ISSUE THREAD

**Issue by peterbabic** [akonwi/git-plus#443]
I really miss the feature I was used to with `vim`, which is COMMIT_EDITMSG's syntax highlighted as in 
![screenshot_2016-05-19_20-15-31](https://cloud.githubusercontent.com/assets/3952052/15404634/b6dfb50a-1dfe-11e6-8ce3-c1aaeac5c78c.png)
Any ideas how to implement this?

**Comment by akonwi** [comment]
git syntax highlighting is native to atom. Make sure the language-git package isn't disabled.
<img width="634" alt="screen shot 2016-05-19 at 9 43 50 pm" src="https://cloud.githubusercontent.com/assets/2013804/15414665/d69cc67e-1e0a-11e6-8ced-e78782abc1d0.png">

**Comment by peterbabic** [comment]
Thank You for the reply. I have the `language-git` package enabled, but it does not do the highlighting. I should try to investigate in the pakage's issues section probably.
