### ISSUE TITLE
Menu buttons show outside of menu

### ISSUE THREAD

**Issue by johnmuhl** [akonwi/git-plus#445]
![screenshot from 2016-05-23 11-07-27](https://cloud.githubusercontent.com/assets/7944/15476842/2c7c2926-20d7-11e6-86d5-4ec81aeb5ec0.png)

Atom 1.8.0-beta4
One Dark UI theme

**Comment by akonwi** [comment]
Do you have any custom css in addition to the theme? I can't replicate this

**Comment by johnmuhl** [comment]
I also tried with a new `.atom` directory and only installed git-plus (i.e. all default settings). Poking around in the devtools shows that `div.buttons` inside the `select-list` has a computed height of 0 but I can't figure out why. One way to reproduce is staging files (but any dialog with buttons is the same):

1. <kbd>Ctrl+H</kbd>
2. <kbd>sf</kbd>
3. <kbd>return</kbd>

**Comment by johnmuhl** [comment]
Note that 1.7.4 is fine. Only the 1.8 beta releases seem affected.
