### ISSUE TITLE
Feature request: support git commit -a

### ISSUE THREAD

**Issue by henti** [akonwi/git-plus#454]
I've noticed a couple of people logging bugs saying "git commit" is not working and getting "nothing to commit" errors due to not updating git index with git-add before hand. 

would it not make sense to add a "Git Commit Update" command to run "git commit -a" which is the functionality people are looking for ?

**Comment by akonwi** [comment]
See #201. `Add all and commit` does something similar as well. The issues about nothing to commit seem to come from a lack of understanding of how git works
