### ISSUE TITLE
Looking for 'git status' and 'git pull origin master' commands

### ISSUE THREAD

**Issue by thomasdot** [akonwi/git-plus#461]
Hello,

How can I run `git pull origin master` and `git status` within Atom using the git-plus package? Is this even possible? I don't mind doing this from the command line, but I don't want to miss functionality within Atom using git-plus.

Thanks.

**Comment by niij** [comment]
Please at least read the README before opening an issue.  From the second Heading on the readme:

### Showing the Git-Plus Palette
>- `Cmd-Shift-H` on MacOS
>- `Ctrl-Shift-H` on Windows + Linux
>- `Git Plus: Menu` on the atom command palette.

**Comment by omgimanerd** [comment]
I have a similar question and I don't want to open an issue, but is there a way for one to keybind `git pull`?

**Comment by akonwi** [comment]
There's a command called `Status` that lists which files have been changed. Selecting a file from that list will open it. 

The `Pull` and `Pull Using Rebase` commands allow you to chose which branch to pull from
