### ISSUE TITLE
Push with tags (git push --tags)

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#462]
Hello

It would be neat to be able to push including tags, i.e. `git push --tags`. It might be interesting to even do it by default on push, but I assume that there is a specific reason it requires an extra argument in Git.

Thanks in advance

**Comment by akonwi** [comment]
This is already a feature. You can work with tags in the "Tags" option of the command palette.

**Comment by Gert-dev** [comment]
Doh, now that you mention it I noticed that I can select a tag for additional options. I thought showing the list of tags was the end point (or that selecting one of them would check them out).
