### ISSUE TITLE
Verbose commits

### ISSUE THREAD

**Issue by mathuin** [akonwi/git-plus#464]
I tend to run `git commit -v` so I can remember what's involved with my commits.

I would like to make this package use this option when committing.

Unfortunately I have never worked with Coffeescript, and I'm not sure which approach would be best.  If someone else can give design suggestions, I'm willing to tinker and come up with a pull request eventually.  A checkbox for verbosity? A text box for options?  Just tell me. :-)

My workaround is to modify my gitconfig which will suit me for now, but others might see value in this option.  If the gitconfig modification is the right solution, feel free to close this issue.

**Comment by TrevorBurnham** [comment]
@mathuin This is a longstanding issue: https://github.com/akonwi/git-plus/issues/90

**Comment by mathuin** [comment]
Oooh, sorry about that, I guess I didn't look far enough back.  Thanks for the update and I apologize for the duplicate!
