### ISSUE TITLE
Doesn't work in Atom 1.8.0

### ISSUE THREAD

**Issue by volkanunsal** [akonwi/git-plus#468]
I can't seem to get any response after choosing a command from the command menu. No error messages. Nothing happens.

**Comment by valorloff** [comment]
+1 
pushing doesn't work

**Comment by akonwi** [comment]
Is still an issue? I'm on 1.8.0 and I don't see any problems. Make sure to open the dev console so if there are errors being logged you can see them.

@ninobergfeld If git isn't already in your path, you should see an error. There is an option in the package settings where you can specify the path to git anyway if you think that's the problem

**Comment by guigrpa** [comment]
It's still an issue, indeed, at least in Windows. Absolutely no action

**Comment by guigrpa** [comment]
Sorry, my bad. In my case, git-plus was not finding the git repo (not the git executable), since the root folder I opened in Atom was not the one containing the `.git` folder (but rather one level up). It worked correctly after I opened the child folder.

**Comment by jmullman** [comment]
Everything but push appears to work (Windows 10, Atom 1.8.0).

I've checked the Dev Console, and I don't see any complaints about git-plus, unfortunately.

**Comment by prvst** [comment]
Ubuntu 16.04.1 LTS, Atom 1.9. Git push also doesn't work

**Comment by akonwi** [comment]
I'm closing this because the version issue should be stale by now.

For those of you with pushing issues check out https://github.com/akonwi/git-plus/issues/224
