### ISSUE TITLE
Commit empty message

### ISSUE THREAD

**Issue by janosimas** [akonwi/git-plus#471]
After updating to 5.16.0 I'm unable to commit,
I always get the message "aborting due to empty commit message".

**Comment by michaelw85** [comment]
Same here. After saving it shows the commit message box as empty where on the initial try it shows the default info message.

**Comment by janosimas** [comment]
uptate to 5.16.2
when I try to commit two tabs appear with the commit contents,
I was able to add some text and commit but I got an error, I'll update with the error message later.

**Comment by akonwi** [comment]
@janosimas Do you have the Experimental Features setting enabled?

**Comment by janosimas** [comment]
no, it's disabled

**Comment by janosimas** [comment]
@akonwi I enabled and disabled it and seams to be working fine now.
Maybe atom kept some temp config file?

**Comment by akonwi** [comment]
@janosimas  Maybe it did. I have some issues locally where settings persist sometimes even after being removed from a package.

I'm going to close this since it seems to be resolved.
