### ISSUE TITLE
Commit with "resolves #34" comment discards #34

### ISSUE THREAD

**Issue by pdxwolfy** [akonwi/git-plus#473]
Since upgrading to 5.16.0, entering a commit message with something like "resolves #34" discards the #34 part of the commit message, and the associated issue is not resolved. At first I thought I was just mistyping, but I confirmed it on the most recent attempt; as soon as pressed Cmd-S to save the commit message, the #34 is wiped out.

**Comment by pdxwolfy** [comment]
Might be a duplicate of #472.

**Comment by akonwi** [comment]
Yes I think this is a duplicate. Can you update and verify it's fixed for you before we close this?

**Comment by pdxwolfy** [comment]
Yes, I've updated and verified. It seems to be fixed. Thanks!
