### ISSUE TITLE
diff automatically opens two tabs

### ISSUE THREAD

**Issue by bretthandrews** [akonwi/git-plus#474]
After updating to 5.16.0, diff will automatically open two tabs (with the same diff)

**Comment by szimek** [comment]
Got the same issue. It splits the screen in 3 horizontal panes, where only the bottom 2 are used and in both the same diff is displayed. I'm using version 5.16.1.

**Comment by akonwi** [comment]
Is this still an issue?

**Comment by bretthandrews** [comment]
It working properly for me in version 7.0.7. Thanks @akonwi!
