### ISSUE TITLE
Commit not working on latest 2 releases

### ISSUE THREAD

**Issue by andrewmartin** [akonwi/git-plus#476]
For some reason, and I noticed this only happens with the latest 2 releases, when I try and add a commit message, it fails with an error:

```Error: ENOENT: no such file or directory, open '/Users/andrewmartin/code/drew-web/.git/COMMIT_EDITMSG'```

It does successfully stage the file, just won't save the commit message, which is somewhat frustrating. It was working great for awhile too, that's the strange thing.

I'm currently on `5.15.0` and it's working fine, anything later than that and this error happens.

**Comment by akonwi** [comment]
To be clear, the commit message file opens, you type your message,  try to save the file, and then this message appears.

Is that correct?

**Comment by andrewmartin** [comment]
Yep, exactly as you describe. 

After I type my commit message, that little red error notification pops up in the top right corner, and the `COMMIT_EDITMSG` is essentially not saved. However, if I go to the Terminal and type in `git status` the file(s) are all staged, and a commit (with message) from there works as expected.

**Comment by akonwi** [comment]
I've created a branch ([476](https://github.com/akonwi/git-plus/tree/476)) with what I suspect is the fix. If you don't mind cloning that and replacing your installation of the package with it to give it a shot that would be great.

**Comment by andrewmartin** [comment]
@akonwi sorry it took me a bit, this worked!

**Comment by andrewmartin** [comment]
@akonwi mind letting me know when it's pushed up or merged into the official release? for now i'm going to use this branch 👍

**Comment by akonwi** [comment]
Merged and published 👍

**Comment by douggr** [comment]
awesome! many thanks.
