### ISSUE TITLE
Merging (Bower) branch with master (mac issue)

### ISSUE THREAD

**Issue by Norfeldt** [akonwi/git-plus#479]
Working on mac and have been seeing some merge problems.

Here is the case:
1. Work on a branch, use bower to install some JS frameworks
2. Do some code changes and commits.
3. Change back to master to do a merge, but it fails

I think that the issue is that `git plus` don't have the rights to add the folders and files. If I use git from the terminal an uses `sudo git merge hotfix --allow-root`

What should I do?

**Comment by akonwi** [comment]
The package doesn't need any read/write privileges to the filesystem. If you need to use `sudo` for your git commands then I don't think you have git setup properly
