### ISSUE TITLE
support submodules

### ISSUE THREAD

**Issue by maxheld83** [akonwi/git-plus#48]
it appears that git-plus may, as of yet, _not_ support submodules.
It'd great to see that and/or a confirmation that the below behaviour is in fact due to the lack of submodule support in git-plus (as opposed to somewhere else in the stack).

I first posted the below on the [atom forums](http://discuss.atom.io/t/using-git-submodules-within-atom/10104) but someone suggested this might be the place:

I'd like to able to use submodules efficiently _within_ Atom.

Use case file tree:
- `superproject`
  - `submodule1`
    - file-a
  - `submodule2`
  - `file-b`
  - `folder1`

**Expected behavior:**

I'd like to able to select `submodule1` (which, after all, includes a `.git`) or any folder or file therein (such as `file-a`) and be able to then have any `add`, `commit` and `push` etc. commands I do (with, say, `git-plus`) to apply to the _submodule_.

*\* Observed behavior:**

No matter where I am, any git operations will work only on the superproject.

In fact, if I _just_ open the `submodule1`, edit, add and commit I get this:

```
Window load time: 1625ms /Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:18
4
Uncaught Error: EEXIST, file already exists '/Users/Max/Github/barjoke/latexstyles/.git' /Users/Max/.atom/packages/git-plus/node_modules/fs-plus/node_modules/mkdirp/index.js:76
```

Any thoughts on how to handle this problem and submodules in general?

**Comment by xyzzy529** [comment]
Whatever happened with this?
I am having what sounds like the same problem. Submodules have Git repos and none of the line diff is working in any of the submodules or main root code.
