### ISSUE TITLE
Stuck in update view

### ISSUE THREAD

**Issue by Stanzilla** [akonwi/git-plus#480]
Every time this package gets updated, the atom package UI never finishes the "updating" process. The progress bar for the update is always on "updating..." and never finishes. The package is infact updated, the package ui just does not notice it. Is there a callback missing/not firing?

**Comment by akonwi** [comment]
This was raised in #262. This is actually an issue with atom [here](https://github.com/atom/settings-view/issues/532) and there is a pull request to fix it [here](https://github.com/atom/settings-view/pull/771)
