### ISSUE TITLE
Will it support git submodules?

### ISSUE THREAD

**Issue by jarodium** [akonwi/git-plus#483]
Hello,

Will git-plus support sub-modules in the future?

Best regards
Pedro

**Comment by JakeDEvans** [comment]
`git submodule update` this command alone would suffice for me.

**Comment by akonwi** [comment]
@jarodium With the latest version (5.24.0) you should be able to do most commands with submodule files when they are the current file.

Give it a shot and let me know

**Comment by akonwi** [comment]
@JakeDEvans you can use the `Run` command and type `submodule update`

**Comment by JakeDEvans** [comment]
opening the submodule folder in another window works well, submodule init/submodule update on the menu would be nice is all.

**Comment by akonwi** [comment]
I'm going to close this issue because I've addressed the OP's question. 

@JakeDEvans So the current solution for submodule update is to use the Run command. Can you open a new issue requesting it though? I just want to separate that from this issue
