### ISSUE TITLE
nested folders

### ISSUE THREAD

**Issue by idokaplan** [akonwi/git-plus#495]
Hi,

I have a project folder with sub repo folders.
For example, the project folder name is "AWS".
Inside "AWS" folder, I have stage and prod folders.
git push is not working if I open the project folder "AWS".
if I open "stage" and "prod" folder, git push is working.

Please advise.
Thanks!
Ido

**Comment by akonwi** [comment]
Check out https://github.com/akonwi/git-plus/issues/312
