### ISSUE TITLE
Issue with GPG commit

### ISSUE THREAD

**Issue by Wes974** [akonwi/git-plus#496]
Hi, I can't commit using git-plus because I have this message showing up :

![capture d ecran 2016-08-16 a 01 05 06](https://cloud.githubusercontent.com/assets/7169107/17679728/c72cc59e-634d-11e6-9632-aa7bc66bc64f.png)

Here is some details about my setup :

> $ where gpg
> /usr/local/bin/gpg
>  $ which gpg
> /usr/local/bin/gpg
>  $ gpg --version
> gpg (GnuPG/MacGPG2) 2.0.30
> libgcrypt 1.7.0
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Home: ~/.gnupg
> Algorithmes pris en charge :
> Clef publique : RSA, RSA, RSA, ELG, DSA
> Chiffrement : IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256,
>               TWOFISH, CAMELLIA128, CAMELLIA192, CAMELLIA256
> Hachage : MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
> Compression : Non compress'e, ZIP, ZLIB, BZIP2
>  $ atom --version
> Atom    : 1.9.8
> Electron: 0.37.8
> Chrome  : 49.0.2623.75
> Node    : 5.10.0

 git-plus 5.16.2

And also I have `no-tty` in my `~/.gnupg/gpg.conf`

**Comment by akonwi** [comment]
I don't think this is package specific. Check out https://github.com/isaacs/github/issues/675 and [this reddit thread](https://www.reddit.com/r/git/comments/4jflp1/need_help_with_git_commit_error_error_cannot_run/)

**Comment by blimmer** [comment]
For anyone who finds this issue, this is what I did to get it working:

```bash
git config --global gpg.program $(which gpg)
echo "no-tty" >> ~/.gnupg/gpg.conf
```
