### ISSUE TITLE
Issue with Git Push

### ISSUE THREAD

**Issue by burhandodhy** [akonwi/git-plus#497]
Hi , 

Something went wrong with git push . Seems that git push command work but it never pushed code on repo.

**Comment by jonomacx** [comment]
Hi @burhandodhy

Please provide further information such as screenshots, the process you were following, confirmation that your config details are correct, and whether the GIT PUSH command process works from the command line on your machine, but it does not from within git-plus.

If not, please close the issue, thanks.

**Comment by akonwi** [comment]
I'm closing this because there isn't any detail to work with. Also changes have been made to the push feature which may have resolved your issue.
