### ISSUE TITLE
May you improve the git log panel, such as show tree view.

### ISSUE THREAD

**Issue by huanggm** [akonwi/git-plus#498]
I find a package "[git-log](https://atom.io/packages/git-log)" . It could show the tree view of logs. I don't like to install another git package.

![1](https://cloud.githubusercontent.com/assets/4965664/17695145/d5719756-63d9-11e6-8781-e70797a5f834.gif)

**Comment by akonwi** [comment]
That package is dedicated to showing you logs with a good visual. If that is what you want then you should use it. I'd rather not spend time replicating the same feature that other packages provide

**Comment by huvber** [comment]
That package is very very slow on showing log and I agree that could be a good add-on to this amazing plugin
