### ISSUE TITLE
Show old version of a file

### ISSUE THREAD

**Issue by jiayihu** [akonwi/git-plus#499]
I often have the need to see how the current file was in a previous commit, not the diffs of that commit. 
I'm talking about this [command](http://stackoverflow.com/questions/338436/is-there-a-quick-git-command-to-see-an-old-version-of-a-file).

**Comment by ropeonfire** [comment]
You can view previous versions of a file using `Git Plus: Run` in the command palette, which then prompts you for a git command. For example: `show HEAD~1:./myFile.ext`. Unfortunately, it seems like you can't redirect this output to another file, and so for large files this solution might not be very useful.

**Comment by akonwi** [comment]
You could theoretically redirect the output if you wrote a custom command. See the [readme](https://github.com/akonwi/git-plus/blob/master/README.md#experimental-features) and this [wiki](https://github.com/akonwi/git-plus/wiki/Custom-Commands-Snippets) and
