### ISSUE TITLE
How to navigate inside git-plus context with keyboard.

### ISSUE THREAD

**Issue by chrisduong** [akonwi/git-plus#500]
Hi,

Firstly, I'm sorry if there is already a solution for it.  At the moment I cannot navigate with keyboard, for e.g, during `Unstage files` context. I think it is very productivity if we can use **keyboard** for quicker.

**Comment by akonwi** [comment]
You can use the arrow keys in the context of Stage and Unstage files. Also you can toggle the selections with enter and then submit with Shift-enter
