### ISSUE TITLE
Fatal: Cold not read Username for "https://github.com", No such device or address

### ISSUE THREAD

**Issue by fransuwar** [akonwi/git-plus#502]
I can't do PUSH, when I try it crash and show the title message.

But I can do in terminal on Ubuntu 14.04 without problem. I am using the 5.16.2 version of the plugin.

**Comment by akonwi** [comment]
Make sure your project is using ssh instead of https. Also make sure you set up ssh with this [guide](https://help.github.com/articles/set-up-git)

**Comment by linfan** [comment]
For private repo which need privilege to pull, should use either ssh address or put username&password in https address:

- `git@github.com:{username}/repo.git`
- `https://{username}:{password}@github.com/{username}/repo.git`

Note: if your put username&password in url, and the password contains '@' character, use '%40' instead.

**Comment by akonwi** [comment]
@linfan has given a potential solution. #224 has more solutions as well.

**Comment by habtu12** [comment]
try to generate a new token for your github account!
