### ISSUE TITLE
Performance hit with multiple git repositories (multiple root folders)

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#503]
Hello

Multiple root folders are neatly supported by git-plus; it seems to automatically pick up the correct root folder and Git repository by examining the currently active editor. I was wondering if something could be done to speed up this process? I have around eight Git repositories open simultaneously and each time I open the git-plus command list it experiences a two second delay before it shows.

Opening the command list is very fast on windows with one repository open so I assume it has something to do with scanning for the correct repository. (I'd be happy to try out a separate branch if necessary.)

Thanks in advance

**Comment by akonwi** [comment]
When I have 10 repos open I don't see any lag. Are you seeing this consistently with a fresh instance of atom?

**Comment by Gert-dev** [comment]
It seems to have improved somewhta since I opened this ticket, but there is still a noticeable delay when I have many root folders (with each a repository) open. When I have a single root folder (and a single repository) open, git-plus is very fast.

This happens when opening the git-plus command palette via `git-plus:menu`. As soon as the menu is open, traversing to other menus does not lag.

I also took the opportunity to create a profile to see what is slowing down the command the most, which seems to be the `refresh` command, which happens for every repository and spawns a process on the background:

![profile](https://cloud.githubusercontent.com/assets/6823929/20111182/9c3cae9e-a5e7-11e6-8d7b-6df715e584a8.png)

**Comment by akonwi** [comment]
Thanks for including the profiling info. The delays you have are significant compared to mine. I've removed the spawned process in the refresh function because I think it's unnecessary and reduced how often all the repos are iterated.

These changes will be in the next release which may come today.

**Comment by akonwi** [comment]
Let me know if the performance improves for you with the new update

**Comment by Gert-dev** [comment]
@akonwi That's a _lot_ better, thanks!
