### ISSUE TITLE
Package does not initialize itself until I run at least one command

### ISSUE THREAD

**Issue by xenithorb** [akonwi/git-plus#504]
The problem I'm having is that I expect git-plus to be loaded and ready to go when I start a new atom session. I particularly like the functionality of branch switch by clicking the branch-name indicator in the bottom right corner. This, however, is not available until I _run at least one git-plus_ command from the command palette. It's as if it's not being loaded properly until I run at least one command. 

Another indicator that something is wrong is that the "push pin" icon is not drawn until one command is run, either. 

Atom: RPM 1.9.9
OS: Fedora 24

**Comment by xenithorb** [comment]
Hello?

**Comment by akonwi** [comment]
For performance reasons the package isn't activated until it is manually invoked. It doesn't necessarily have to be a git command though. Opening the git command palette will suffice. 

I have plans to improve the performance of startup and activation and that will include initializing the package immediately

**Comment by xenithorb** [comment]
Thanks for taking the time to fix this
