### ISSUE TITLE
Ahead of origin icon doesn't go away after Git Plus: Add All Commit and Push

### ISSUE THREAD

**Issue by ychaikin** [akonwi/git-plus#505]
After bringing up command of "Git Plus: Add All Commit and Push" through the `Cmd-Shift-p` keyboard shortcut on Mac (El Capitan 10.11.6), Atom 1.9.9, Git Plus 5.16.2, the 'up arrow' icon on the bottom right still shows "ahead of origin" by 1.

Restart of Atom solves the problem.

Here is a screenshot of that:
![Git Plus Bug Screenshot](https://ychaikin.github.io/public-share/GitPlusBug.png)

**Comment by akonwi** [comment]
That status information in the status bar is native to atom and not provided by this package. Restarting isn't necessary though I don't think because that status should refresh on some UI events of atom. I've noticed it refresh when I leave atom and come back at least
