### ISSUE TITLE
Commit All And Push

### ISSUE THREAD

**Issue by rzvc** [akonwi/git-plus#506]
I added this to my local copy. You might consider including it by default.

commands.push ['git-plus:commit-all-push', 'Commit All And Push', -> GitCommit(repo, stageChanges: true, andPush: true)]

**Comment by rzvc** [comment]
Hey, I noticed that you added the change, but it's also adding all the untracked files, while my intention was to be able to commit all the changed files, without implicitly adding all the new files too.

**Comment by akonwi** [comment]
Yep. Sorry my mistake. It'll be fixed in the next update

**Comment by rzvc** [comment]
Awesome. Thanks!
