### ISSUE TITLE
Incorrect syntax highlighting in git diff

### ISSUE THREAD

**Issue by code-tree** [akonwi/git-plus#512]
When diffs have multiple sections it messes up the syntax highlighting. In the example below, a python docstring is started, but the end of it is cut, leaving the next section to be treated as part of the docstring.

![image](https://cloud.githubusercontent.com/assets/11289719/18409864/b04d3e88-777c-11e6-8cbe-f52937664d97.png)

**Comment by sharedprophet** [comment]
If the end of it isn't in the diff, I don't now how the syntax highlighting would be able to handle it correctly...?

**Comment by code-tree** [comment]
Yes, I don't know either. For that reason, it is probably better to disable syntax highlighting if there are multiple sections in a diff, as no highlighting is much better than wrong highlighting (very confusing).

**Comment by code-tree** [comment]
Actually, even with the above solution, the problem could still occur, as diff only includes a few lines of context around what is changed.

This was a great idea, but unfortunately I'm going to need to turn it off for my work, as it is too risky getting confused by any wrong highlighting.

**Comment by sharedprophet** [comment]
Multi-section diffs generally work fine. Special cases like this can break them, though. I will add an option to turn off the syntax highlighting.

**Comment by sharedprophet** [comment]
#511

**Comment by code-tree** [comment]
Yes, I guess it only applies to situations where a string is spread across multiple lines. Unfortunately, this is very common with docstrings in python. An option would be great, thanks

**Comment by akonwi** [comment]
Closing this since the toggle for that feature has been published.
