### ISSUE TITLE
the keyboard shortcuts dont seem to work

### ISSUE THREAD

**Issue by mlgann** [akonwi/git-plus#513]
Perhaps I'm doing in wrong but the instructions for the keyboard shortcuts like "Add All commit And Push"
![image](https://cloud.githubusercontent.com/assets/22204954/18531635/ec19168a-7a9c-11e6-8c57-0e5d4cd774be.png)

are vague... do i hit command+shift+A+P all together at the same time?
or do I hit the command+shift+A then command+shift+P after? 
I have tried this multiple ways and its driving me crazy that I cannot get anything to work..

**Comment by akonwi** [comment]
I think the theme you're using has a smaller setting for the line width than usual. 

it's `cmd-shift-a p` so command, shift, and 'a' are pressed at the same time then you press 'p' alone after.

The package settings has a table with these shortcuts which may be more helpful
