### ISSUE TITLE
Git push doesn't work with private repos

### ISSUE THREAD

**Issue by c0degeekPL** [akonwi/git-plus#520]
Hello! Pushing changes doesn't work with the private repos, because there is a password protection for a private repo. It is possible to put password somewhere to make push possible?

**Comment by 2mhost** [comment]
same issue here ..

**Comment by akonwi** [comment]
Make sure you're configured to use ssh using [this tutorial](https://help.github.com/articles/set-up-git) and that your repository is using the git protocol instead of 'http'. You can do that with `git remote set-url origin git@github.com:username/repo.git`

**Comment by ITZounds** [comment]
Thank you akonwi for the information, it worked

**Comment by GuruTheCoderYoutube** [comment]
I'm still getting "Permission denied (publickey)
Could not read from remote repository
Please make sure u have the correct access rights.
"
