### ISSUE TITLE
Cant Push

### ISSUE THREAD

**Issue by Arszilla** [akonwi/git-plus#525]
I cannot make a push to my repo.

I have to go to my terminal, enter my location for my code; and do it manually.

Git Plus doesnt ask for my username/password....

**Comment by prvst** [comment]
I'm facing the same issue in some project folders, this is actually the second time I post this here...

**Comment by lbodden** [comment]
I'm experiencing the same issue.

**Comment by hellfishg** [comment]
same, in linux debian.

**Comment by sharedprophet** [comment]
If you do it from the terminal it shouldn't ask again for a day or so, during which time git-plus should be able to do pushes fine.

**Comment by akonwi** [comment]
Refer to #224

**Comment by richiprieto** [comment]
I solve the problem with
`git config --global credential.helper cache`
