### ISSUE TITLE
Commit Amend shows an incorrect, single-line commit message

### ISSUE THREAD

**Issue by josh-berry** [akonwi/git-plus#528]
I have Atom 1.11.2, Git 2.10.1, and Git Plus 5.18.0 (running on macOS Sierra, 10.12.1). When I run the "Git Plus: Commit Amend" command from the palette, I do not see the full commit message. What I do see seems to vary depending on where my `HEAD` is pointing:

- If `HEAD` is a non-merge commit, only the first line of the commit message is shown.
- If `HEAD` is a merge commit, only the first line of some other non-merge commit in `HEAD`'s history is shown.

Continuing with the Amend operation replaces the original commit's message with the broken, single-line message (assuming I don't make any edits to the commit message that Git Plus shows me).

I know this is not a problem with my git installation, because I can run `git commit --amend` from the command line, and the entire commit message appears in Atom (which is my `$EDITOR`) as it's supposed to.

Not sure if this matters, but in Git Plus settings, I have "Experimental", "Verbose Commits", and "Word Diffs" all turned off (I assume this is the default).

Please let me know if there are any other settings or information you need to help diagnose this.  Thanks!

**Comment by akonwi** [comment]
Can you provide a video of this please? I'm trying to reproduce this and I don't see any issues with both non-merge and merge commits.

**Comment by santhoshtr** [comment]
I can confirm this. Whenever I do git commit amend I see only first line.

**Comment by akonwi** [comment]
@santhoshtr Is this still occurring?

**Comment by santhoshtr** [comment]
> @santhoshtr Is this still occurring?

It Works fine now
