### ISSUE TITLE
Submenu for tree-view Git commands

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#529]
Hello

It's great to see that commands are being added to the tree view menu, which also lowers the entry barrier for new users. I was wondering if it would be possible to put the current Git commands in a submenu? It seems likely that a lot more Git commands will be added in the future, this keeps things nice and tidy (and is also the approach taken by some IDE's).

Thanks in advance

**Comment by akonwi** [comment]
This is the plan. There are only two right now so when more start getting added they'll get shoved into a submenu
