### ISSUE TITLE
Deprecated selector in `git-plus\styles\git-plus.less`

### ISSUE THREAD

**Issue by sbistrovic** [akonwi/git-plus#538]
In `git-plus\styles\git-plus.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .diff .unimportant,
atom-text-editor::shadow .diff .unimportant` => `atom-text-editor .diff .unimportant,
atom-text-editor.editor .syntax--diff .syntax--unimportant`

* `atom-text-editor .diff .info,
atom-text-editor::shadow .diff .info` => `atom-text-editor .diff .info,
atom-text-editor.editor .syntax--diff .syntax--info`

* `atom-text-editor .diff .deletion,
atom-text-editor::shadow .diff .deletion` => `atom-text-editor .diff .deletion,
atom-text-editor.editor .syntax--diff .syntax--deletion`

* `atom-text-editor .diff .insertion,
atom-text-editor::shadow .diff .insertion` => `atom-text-editor .diff .insertion,
atom-text-editor.editor .syntax--diff .syntax--insertion`

* `atom-text-editor .diff .markup.removed.diff,
atom-text-editor::shadow .diff .markup.removed.diff,
atom-text-editor .diff .meta.diff.header.from-file,
atom-text-editor::shadow .diff .meta.diff.header.from-file` => `atom-text-editor .diff .markup.removed.diff,
atom-text-editor.editor .syntax--diff .syntax--markup.syntax--removed.syntax--diff,
atom-text-editor .diff .meta.diff.header.from-file,
atom-text-editor.editor .syntax--diff .syntax--meta.syntax--diff.syntax--header.syntax--from-file`

* `atom-text-editor .diff .markup.added.diff,
atom-text-editor::shadow .diff .markup.added.diff,
atom-text-editor .diff .meta.diff.header.to-file,
atom-text-editor::shadow .diff .meta.diff.header.to-file` => `atom-text-editor .diff .markup.added.diff,
atom-text-editor.editor .syntax--diff .syntax--markup.syntax--added.syntax--diff,
atom-text-editor .diff .meta.diff.header.to-file,
atom-text-editor.editor .syntax--diff .syntax--meta.syntax--diff.syntax--header.syntax--to-file`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by akonwi** [comment]
This was first reported in #537 so I'm marking this as the duplicate. Once the changes I've pushed are verified, I'll close that as well.

**Comment by sbistrovic** [comment]
👍

**Comment by akonwi** [comment]
I've kept the current selectors and added the new selectors so it will work with the current releases of atom. Once those selector changes are released in the stable version I'll remove the old selectors. 

You are probably still seeing errors because of that
