### ISSUE TITLE
Error when committing: "TypeError: commentchar.trim is not a function"

### ISSUE THREAD

**Issue by hertsenberg** [akonwi/git-plus#542]
When committing I'm getting: "TypeError: commentchar.trim is not a function"
![image](https://cloud.githubusercontent.com/assets/5654232/20219860/7f586cc8-a82b-11e6-9e31-9d197a6c3af0.png)

to test I tried to set a different core.commentChar but this did not work.

Git-plus doesn't let me enter a comment and doesn't commit my work any more.
(using: v5.25.1)

**Comment by akonwi** [comment]
What is your commentChar set to?

**Comment by hertsenberg** [comment]
First I did't set it, so it should be default # 
Then I tried ";"
and I tried setting it to "#".

In all cases git-plus would give this error.

**Comment by akonwi** [comment]
I've made some changes which may fix this. Give the latest release a shot and let me know if this has been resolved.

**Comment by hertsenberg** [comment]
Great! Thanks a lot. 
It's working fine now.
