### ISSUE TITLE
fatal: The current branch has no upstream branch

### ISSUE THREAD

**Issue by mkismy** [akonwi/git-plus#544]
After updating git-plus to version 5.25.1, every time I try pushing a new branch, it fails with the following messege:
```
fatal: The current branch branch/example has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin branch/example
```

I'm not sure what I was using previously, but it was before 5.23.3.

Steps to reproduce:

1. Create new branch.
2. Use push feature (ex. Push, Add And Commit And Push, …)
3. Fails

**Comment by akonwi** [comment]
Version 5.22.0 Introduced a new command `Push -u` for pushing new branches so you need to be explicit about --set-upstream. Previously, the push command would push and fail and then retry with `--set-upstream` and that side steps some git hooks.

**Comment by dmangot** [comment]
This was disappointing behavior for me as well.   Now 'add all commit and push' is broken for new branches so it's back to 3 distinct steps, the 3rd of which requires finding the second choice.  Had me really scratching my head when my branch did not show up.
