### ISSUE TITLE
[REQUEST] Output pane is a little too eager to hide sometimes

### ISSUE THREAD

**Issue by ghost** [akonwi/git-plus#547]
Hello

It seems that sometimes the output pane at the bottom is a little too "eager" to hide. I think this happens when you execute commands that use the output pane for a status report on exit in quick succession (e.g. push, switch branch, push or push, pull). What will happen is that for the second command, the output pane will be updated with the status of the last command, but it will not show automatically anymore or suddenly close very quickly by itself (you can still open it manually to see the contents).

This is a rather small problem, I only felt the need to report it because it gives you the feeling that "it's not doing anything" or "it's not working", whilst everything is working fine, the output pane just didn't show up automatically.

I'm not particularly familiar with the code base, but this reeks an awful lot like a `setTimeout` being spawned multiple times without the previous one being removed first with a `clearTimeout`. For example:
* Command C1 finishes and sets output O1 in the output pane, spawns timeout T1 to hide pane within 5 seconds
* Command C2 finishes 4 seconds later and sets output O2 in the output pane, spawns new timeout T2 but doesn't clear T1
* 1 second later the pane hides because T1 is executed (O2 was only visible for 1 second).
* 5 seconds after that T2 also executes, but has no effect as the pane is already hidden.

Thanks in advance

**Comment by akonwi** [comment]
You're totally right. That pane is a single instance that is cleared and toggled with different commands. The immediate change is to fix what you've pointed out is to clear the current timeout when the content is updated. That then leads to the content being overwritten really quickly and you see the initial outputs very briefly.

It may make sense to just keep appending to the pane so no messages are lost.

**Comment by Gert-dev** [comment]
That seems like a good alternative. I believe the pane currently automatically determines its own height based on its content, but it could receive a fixed height (and optionally be resizable) and just scroll the content.

There is perhaps the issue of somehow "highlighting" the last relevant output (the output of the last command). For example, if you have a lot of new remote branches, the `git pull` output will take up a larger height than a pull without a lot of new branches. This sometimes happens to such extent that a large portion of the Atom window is covered by the output pane resizing itself.

Using a scrolling output pane could neatly fix the sizing issue, but it might make it hard to "focus" the last relevant output as you will either end up at the bottom of the output pane or the start of the output, losing the complete overview.

Perhaps highlighting or simply delimiting the last output somehow might make it easier to see where it ends so you don't accidentally scroll back to output that isn't immediately relevant to the last command. Taking this a step further, you could even simply use a terminal-style (read-only) output pane where you first append the raw command being executed followed by its output. This way you can simply visually distinguish between the command and its output via styling (you could even go as far as providing som sort of "bookmark" buttons in the output pane that will simply jump up or down between commands for ease of use).

**Comment by akonwi** [comment]
Closing this to track it with #674
