### ISSUE TITLE
recognition issue

### ISSUE THREAD

**Issue by kimixu717** [akonwi/git-plus#552]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

-----------------

[Description of issue here]

Steps to reproduce:

1. -- git plus can only recognise the project in the current folder, if i add the wrong project folder ,such as the Last level folder, git plus cannot recognise it.
2. -- 
3. --

**Comment by akonwi** [comment]
This is not the case for me. I can't reproduce this

**Comment by akonwi** [comment]
Can you provide more steps to reproduce this?

**Comment by jontyD** [comment]
not sure if this is the same thing but now that atom can have more than one directory in the tree view if you switch between folders the branch does not change in the bottom right status thing although if you try to switch branches using the palette it asks which repo

**Comment by akonwi** [comment]
@jontyD the branch info in the status bar is part of atom-core and isn't from this package. Also, it does change for me when I have two repos open in the project and switch between files in those repositories

**Comment by jontyD** [comment]
Apologies I misunderstood, the file knows which repo it is in  but it is a bit confusing. I sort of expected choosing a different folder / repo would only show me files in that repo
