### ISSUE TITLE
Typing the keybinding for "git add" does not work the first time after a file save

### ISSUE THREAD

**Issue by baldwind** [akonwi/git-plus#557]
When I make a change to a file, save it, then type Command-Shift-A to add it to the index it will not work. I then type Command-Shift-A again and it will display the notice that it was added. I have tried this several times on different files and it always does not work the first time. I'm using Atom 1.12.5 on OS 10.11.6

Thanks

**Comment by akonwi** [comment]
The reason for this is explained in https://github.com/akonwi/git-plus/issues/415. The current workaround is to disable the keybindings from the package and define only the ones you want.

I'm going to mark this as a duplicate.
