### ISSUE TITLE
[REQUEST] Command Doc Err

### ISSUE THREAD

**Issue by shery15** [akonwi/git-plus#558]
The Commands **Git add and commit and push** and **Git add all commit and push** show the same Default key binding: `Cmd-Shift-A P`. In fact, the Default key binding of **Git add and commit and push** is `Cmd-Shift-A q`. 

Both [Github README](https://github.com/akonwi/git-plus/blob/master/README.md) and [Atom DOC](https://atom.io/packages/git-plus) need fix.

**Comment by akonwi** [comment]
Fixed just now. The next release will update it in atom.
