### ISSUE TITLE
[REQUEST] push to all remote repositories

### ISSUE THREAD

**Issue by petrklus** [akonwi/git-plus#563]
I would really like another option in the git push menu - a * or "all" to designate push to all of the remote repositories. I often work on two remotes and it would be great to be able to push to all of them in a single command (I recall TextMate has this option).

**Comment by akonwi** [comment]
I'm trying not to add particular features that are less commonly used across all git users.

This seems like a great candidate for a custom command though. You can read about custom commands [here](https://github.com/akonwi/git-plus#experimental-features) and try it out.
