### ISSUE TITLE
[REQUEST] Display some diff information when editing the commit message

### ISSUE THREAD

**Issue by AlexandreDecan** [akonwi/git-plus#569]
I think it can be really convenient to have the diff displayed when editing the commit message, similarly to what is done by the git plug-in for Sublime Text for instance:

https://cask.scotch.io/2014/08/git-sublime-commit-1115x500.jpg

Maybe this can be done directly under the commit message (like in the above screenshot) or in another pane that could be automatically open when a commit is performed?

**Comment by akonwi** [comment]
You can enable this with the 'Verbose Commits' toggle in the package settings. It's currently still marked as experimental so you'll need to turn on experimental features as well. It'll no longer be experimental after the next relase

**Comment by AlexandreDecan** [comment]
Oh, great, thank you! I actually saw the option but I didn't check "experimental features". 

Btw, great job for the plug-in!
