### ISSUE TITLE
[REQUEST] Git add all should not add files not in the repository

### ISSUE THREAD

**Issue by ybizeul** [akonwi/git-plus#572]
Here is my git status :

```
yann$ git status
On branch fix-docker
Your branch is ahead of 'origin/fix-docker' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   .gitlab-ci.yml
	modified:   Dockerfile
	modified:   site/themes/hugo-material-docs (modified content, untracked content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	grafana_4.0.2-1481203731_amd64.deb
	onedrive/corporate.py
	site/data/
	test/runsmall.py
```

Usually I commit my code doing `git commit -a -m "commit message"`.

I try to use git-plus and using __Git Add All + Commit__ adds the untrack files and commits.

I don't think it is the expected behavior, the way I understand it, it should mimic `-a` option and only add changed files.

The documentation is actually correct :
> Add all changed files and show the commit message file. Similar to Git add all and Git commit in succession.

**Comment by akonwi** [comment]
The documentation is poorly worded. 'Changed files' is referring to anything different whether untracked or not and is the equivalent of `git add . && git commit`. I'll change the documentation.

`Commit All` is the command for `git commit -a`.

Sorry for the confusion.

**Comment by ybizeul** [comment]
There is no Commit All, should I create a manual map to `git-plus:commit-all`?
<img width="251" alt="screen shot 2016-12-16 at 4 59 54 pm" src="https://cloud.githubusercontent.com/assets/182035/21279949/168cd9bc-c3b1-11e6-8de2-cfcfb1dd0187.png">

**Comment by akonwi** [comment]
You could do that. 

The menu in the top bar is only a subset of all the commands that this package has. 

You can use the command palette to see all the commands or use 'cmd-shift-h' to open the command palette specifically for this package

**Comment by ybizeul** [comment]
Make sure sense, I mapped the shortcut to commit all and all is good. Thanks!
