### ISSUE TITLE
"Init" is only menu option available in active Git repo.

### ISSUE THREAD

**Issue by phyllisstein** [akonwi/git-plus#576]
Hey there! I've noticed that since upgrading to 6.0.0, I'm no longer able to access any of Git Plus' commands in the Command Palette, with the exception of "Init." I'm running an Atom window with an active Git repo, as you can see from the attached screenshot, where Atom detects the current branch successfully.

A little experimentation suggests that this only happens when opening a project from Project Manager or dragging a folder into an empty workspace. Dragging a folder directly onto the Atom icon makes all the commands available. Not altogether sure what this portends though.

![screen shot 1](https://cloud.githubusercontent.com/assets/2207980/21462931/07dffa78-c930-11e6-9314-24ca5b10659a.png)

###### Steps to reproduce:
1. Open a new, empty Atom workspace.
2. Drag and drop a Git repo's root folder onto the window to open it.
3. Summon the Command Palette and type "Git Plus."
4. Search in vain for commands.

**Comment by akonwi** [comment]
The last update to the package had a change to only show the Init command when no repositories were found in the project. Unfortunately it seems atom doesn't have an API for detecting when a new project has been added to the project. I'm going to do more investigating and see if something can be down about that

**Comment by phyllisstein** [comment]
💃 Awesome! Thanks so much for turning this around so quickly.
