### ISSUE TITLE
Change items order of menu in tree view

### ISSUE THREAD

**Issue by gholami-mohammad** [akonwi/git-plus#578]
In the context menu , the checkout item is below the Add+Commit item and some times the checkout item clicked and all changes lost.
Please move this item to the end of list.

**Comment by akonwi** [comment]
That menu is sorted in alphabetical order for ease of navigation. I'll add a confirmation dialog so users have a chance to cancel if it was accidental

**Comment by gholami-mohammad** [comment]
Are you sure?? It don't show any confirmation dialog at all. I tested it but but just show me a success message!

**Comment by akonwi** [comment]
I haven't released the changes yet

**Comment by gholami-mohammad** [comment]
I will reinstall the package and will sent you the feedback.

**Comment by gholami-mohammad** [comment]
I reinstalled the package but checkout command not show me any dialog again!

**Comment by akonwi** [comment]
I still haven't released the changes

**Comment by akonwi** [comment]
I just pushed a new release with the fixes

**Comment by gholami-mohammad** [comment]
Excellent! Now it is working!
