### ISSUE TITLE
[REQUEST] Output Console - ability to visit links

### ISSUE THREAD

**Issue by choppedpork** [akonwi/git-plus#586]
Hello,

I'm using the git-plus plugin almost exclusively with my company's internal BitBucket server. When pushing to a branch, BitBucket sends back a message which includes a direct http(s) link to create a pull request - which is incredibly handy. Unfortunately the Output Console does not allow to select text (the cursor changes into a text selection one but it's not possible to actually select) so that I could copy the link.

It would be even nicer if the Output Console was able to detect http(s) links so that you could just click them in Atom!

**Comment by akonwi** [comment]
The ability to copy that text is very difficult. If you try to select and copy text outside of the text editor or input fields, you'll notice that you can't do that. Unfortunately that's just how atom works. 

I'll look into making the the links hyperlinks so you can just click them though.

**Comment by choppedpork** [comment]
Thanks @akonwi! I was hoping enabling copying would be easier but clickable hyperlinks will definitely work for my usecase.

**Comment by Meshimages** [comment]
+1

when using git-plus (awesome tool, thank you very much for saving my time !!!) with gitlab, there's a message sent back like 

`remote: To create a merge request for impl-nifty_feature, visit:`
`remote: https://gitlab.com/myzel.io/awesomeRepository/merge_requests/new?merge_request%5Bsource_branch%5D=impl-nifty_feature&merge_request%5Bsource_project_id%5D=3487709&merge_request%5Btarget_branch%5D=staging&merge_request%5Btarget_project_id%5D=3487709`

and it would be incredibily time-saving just beeing able to click that link to jump to the corresponding merge-request straight away

**Comment by akonwi** [comment]
Just published v8.1.0 that fixes this. Read more [here](https://github.com/akonwi/git-plus/blob/master/CHANGELOG.md#810)
