### ISSUE TITLE
[QUESTION] The bottom-dock package and service

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#588]
Hello

I just wanted to drop by and let you know about the [bottom-dock](https://github.com/benjaminRomano/bottom-dock) atom package. You may have already heard about it, but it offers a service that allows you to simply put a customized view in a panel that is docked at the bottom of the atom window. I realize you already have your own pane, of course, but just wanted to let you know that it might be interesting if you were looking to reduce the code you have to maintain for the dock itself :-). The advantage is that other packages supplying a dock will allow a user to switch between the docks using tabs.

Feel free to close this issue after you've read it and keep up the great work!

**Comment by akonwi** [comment]
Thanks for telling me about that. I hadn't heard about it yet but I like it a lot. I'm going to check it out.

**Comment by Gert-dev** [comment]
I'll close this for you, since git-plus now supports Atom's native docks, which is pretty much just as good (or even better) than what bottom-dock does! 🎉
