### ISSUE TITLE
[QUESTION] Can you use two factor authentication?

### ISSUE THREAD

**Issue by spences10** [akonwi/git-plus#592]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172).

Did you update the package and you are seeing this message `Failed to load the git-plus package`? Run `apm install` from the package's directory and restart atom.
-----------------

[Description of issue here]

Steps to reproduce:

1. -- try push to branch
2. -- fails
3. -- can't find if there's somewhere to configure it??

**Comment by akonwi** [comment]
Did you read the template and visit the links to similar issues with potential answers?

Your description of the failure isn't really helpful but maybe you'll find help in #224 and #575 because those issues are both related to pushing

**Comment by spences10** [comment]
Apologies, I really should read before posting.

The answer was in the second paragraph! 

Thank you
