### ISSUE TITLE
[REQUEST] - Append Repo and Branch when Pushing

### ISSUE THREAD

**Issue by ggedde** [akonwi/git-plus#596]
I am really loving git-plus.  Thank you!

I prefer to have my gitconfig set for push.default to be "nothing".
This makes it a requirement that I have to specify a remote and branch when running git push.
This is because I deal with multiple Remotes with the same branches and don't want to make the mistake of pushing the branch to the wrong remote.

However, when running git-plus push it will fail because git-plus just runs "git push".

I really like how when running git-plus pull that a prompt comes up to select which remote and branch I want to pull.

I would like to see the same option for push.  Maybe something in the settings like: "Prompt for remote/branch on push".  If checked then a prompt will come up when pushing to select the remote/branch and it will be appended to the "git push" command so it will work if push.default is set to "nothing".

Also if "Pull before Pushing" is checked then it just uses the remote/branch that was chosen on pull for the push and append it to the "git push" command.  That way you are not prompted twice.

Thanks

**Comment by akonwi** [comment]
I'll try to make this happen

**Comment by ggedde** [comment]
Awesome!
Thanks

**Comment by akonwi** [comment]
If you have more than one remote configured, you'll be prompted to select one. So I'm going to respect the git.push config and if the value is "nothing", then there'll be a prompt to choose the destination branch.

How's that?

**Comment by akonwi** [comment]
If you have multiple remotes, you will be prompted to select one. I think all I need to add is the toggle to prompt for which branch to push to.

**Comment by ggedde** [comment]
Awesome, that worked!
FYI, for others in case you missed it, there is a new setting that you have to check if you want to get prompted when pulling/pushing.


Thanks
