### ISSUE TITLE
[REQUEST] Refresh status bar after action

### ISSUE THREAD

**Issue by Gert-dev** [akonwi/git-plus#598]
Hello

I've noticed a small oddity that I'm not sure you can do anything about, but I thought I'd ask anyway; it seems that sometimes the amount fo Git commits in the status bar "runs behind". To reproduce this, I can perform the following steps:

1. Add a commit.
2. The status bar Git indicator will indicate there is one outstanding commit.
3. Push the commit using git-plus.
4. Wait for the bottom log dock to appear and disappear.
5. The status bar still lists the one outstanding commit.
6. Open the git-plus menu.
7. The one outstanding commit suddenly disappears.

Is it possible to have the outstanding commit disappear after step 3? Currently, it sometimes appears as if I forgot to push something whilst the push did happen, the status bar just hasn't updated yet.

I realize this may be something that is handled by Atom itself and not this package. I'm not sure what git-plus is doing whilst opening its menu, but it's fixing Atom's lag behind. Would it be possible to do this same thing after the command finishes or request Atom to refresh its status?

Thanks in advance

**Comment by akonwi** [comment]
I can refresh the repository status. This fix will be in the next release
