### ISSUE TITLE
No default Keybindings or setting to enable them

### ISSUE THREAD

**Issue by adamalbrecht** [akonwi/git-plus#601]
Perhaps I'm missing something, but there are no default keybindings for me. Nor is there a section in the package settings to enable them. I copy-pasted them into my keymap.cson file and it works perfectly fine, but I thought you might want to know.

I'm on MacOS 10.12.2 using Atom 1.13.0 with Git Plus 7.1.1.

**Comment by akonwi** [comment]
You don't have this section in the package settings below the 'Experimental Features'?

![screen shot 2017-01-19 at 9 51 12 am](https://cloud.githubusercontent.com/assets/2013804/22113922/772f574a-de2d-11e6-82e0-92d6e15608dc.png)

**Comment by adamalbrecht** [comment]
No it goes straight from **Experimental** to **Word Diff Grammar**

<img width="753" alt="git-plus-settings" src="https://cloud.githubusercontent.com/assets/180203/22114203/8f3725b2-de36-11e6-847a-4745aeba3d29.png">

**Comment by akonwi** [comment]
Whoa, that's a trip. Haha I have not seen that before.

Are any of your other packages not displaying the default keybindings?

Also, did you recently install/update the package?

Have you uninstalled and re-installed the package?

**Comment by adamalbrecht** [comment]
Yeah, I just checked out a few and they all have _Keybindings_ sections. (Specifically, advanced-new-file, git-blame, and vim-mode-plus)

And yes, I believe it just updated today. It had been installed for a long time.

But actually re-installing the package brought the keybindings section back. Weird.

**Comment by akonwi** [comment]
The keybinding settings are generated by atom because the package provides keybindings. If you checked the config file of this package it has no reference to keybindings. So I wonder if atom had a little blip when you updated the package.

**Comment by lightwave** [comment]
I have the same issue. What's the solution to make Atom see the keybinding?
