### ISSUE TITLE
git Fetch and checkout not working on git-plus for atom

### ISSUE THREAD

**Issue by herrtre** [akonwi/git-plus#602]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172).

Did you update the package and you are seeing this message `Failed to load the git-plus package`? Run `apm install` from the package's directory and restart atom.
-----------------

[Description of issue here]
The "git fetch" and "git checkout" are not working after upgrading to git-plus 7.1.1 on MacOS Sierra 10.12.2.
Steps to reproduce:

1. When trying to run "git fetch" through Git-Plus I  do not see it fetching my repositories.  I press return and nothing happens.  
2. The above also happens with "git checkout"
3. --

**Comment by akonwi** [comment]
There were no changes in 7.1.1 that were related to both those features. Can you validate this is not happening on previous versions?

**Comment by herrtre** [comment]
You can ignore this.  I was in the wrong directory.  Sorry for the inconvenience.



[cid:cambria_98eacbab-ee6d-4a67-a69d-bf0eeef2522e111.png]<http://cambriausa.com/>

[cid:foam_7a11f8ba-d255-48a7-b1ea-ba11aa3ffb34111.png]


Trevor Herrmann
Sr Network Engineer
TEL: 952-873-5100
CEL: 952-393-4845
FAX: 952-873-5101
805 Enterprise Drive East
Belle Plaine, MN 56011
[cid:facebook18_138442cd-3319-4a53-be7a-aad6466296c3111.png]<https://www.facebook.com/CambriaQuartz> [cid:twitter18_8a822fe1-8e90-49d6-b447-ff0b26a156d2111.png] <https://twitter.com/CambriaQuartz>  [cid:instagram18_7c071608-5b80-49dd-ba3a-10e90ad693f4111.png] <https://instagram.com/CambriaQuartz>  [cid:pinterest18_08a804e6-3043-4a54-8105-b22e5641bdce111.png] <https://www.pinterest.com/cambriaquartz>  [cid:houzz18_212a07e4-c6b2-4cb0-b78f-0898a954e459111.png] <http://www.houzz.com/pro/cambriaquartz/cambria>
