### ISSUE TITLE
[REQUEST] Create git dashboard

### ISSUE THREAD

**Issue by max-mykhailenko** [akonwi/git-plus#605]
I saw several very cool plugins for git in another editors which allows completely remove dropdown with files list and show all on one page:
- Emacs https://magit.vc
- Sublime Text https://github.com/divmain/GitSavvy

May I ask you to create dashboard page like in other?

**Comment by akonwi** [comment]
There is a request already for a status buffer in #274. I really like this and would love to make it happen. It isn't trivial with atom's API, so it's not a priority yet. I'm going to close this and keep 274 as the main thread for this feature.
