### ISSUE TITLE
[REQUEST] Git reset --hard

### ISSUE THREAD

**Issue by guillochon** [akonwi/git-plus#610]
It would be nice if git-plus offered the ability to do a hard reset. Currently there appears to be no way within the git-plus interface to remove local changes without stashing them. I think this should be relatively easy to add as it would be identical to the reset command but with the `--hard` flag passed to it?

**Comment by akonwi** [comment]
Have you used the `Checkout` command? Checking out will reset your unstaged changes. 

If you still want to run `reset --hard`, you can make it a custom command.

**Comment by guillochon** [comment]
`Checkout` definitely doesn't do what I would want, but the custom command seems like it would (thanks for pointing that out!). However, the hard reset is the most reliable way of reverting the repo to the last commit, so I think it should be offered amongst the default commands...

**Comment by akonwi** [comment]
Sorry `Checkout all files` and `Checkout current file`. These are equivalent to hard reset.

**Comment by guillochon** [comment]
That does what I need! Closing this request.
