### ISSUE TITLE
"fatal: Couldn't find remote ref feature" on pull

### ISSUE THREAD

**Issue by mherodev** [akonwi/git-plus#618]
When pulling from a coworker's remote branch which I've already checked out, I'm seeing "fatal: Couldn't find remote ref feature". This does not occur when running `git pull` normally in the command line.

Steps to reproduce:

1. --Checkout this particular remote branch
2. --cmd+shift+h "pull" enter
3. --"fatal: Couldn't find remote ref feature"

It seems like it's something specific to the way these branches are created, but I don't know how to get more details.

Thanks in advance
Michael

**Comment by akonwi** [comment]
Does the branch name have a "/" in it? If so, this could be the same issue as #614. I've fixed it and will release it today hopefully.

**Comment by mherodev** [comment]
That's the bug!

**Comment by mherodev** [comment]
Closed as duplicate.

**Comment by PQMISSCMP** [comment]
s
