### ISSUE TITLE
VS Code version of Git+?

### ISSUE THREAD

**Issue by mherodev** [akonwi/git-plus#619]
Any plans or interest in developing a VS Code version of Git+?

I've recently started experimenting with VS Code due to its fantastic code completion (IntelliSense), but if I miss anything from Atom, it's the Git-Plus integration.

There's Git Easy, but it doesn't compare.

**Comment by akonwi** [comment]
I don't use VS code so I haven't thought of it. I'd be happy to help if someone wanted to port this over but I don't have any plans at the moment to do that.
