### ISSUE TITLE
Pull using rebase not working

### ISSUE THREAD

**Issue by amraam83** [akonwi/git-plus#623]
When trying to execute a pull using rebase from packages->git-plus menu, atom does nothing. If instead pull is run from packages->git-plus->pull everything works correctly. I'm using Atom 1.14.1 on macOS 10.12.3.

Steps to reproduce:

1. Open atom
2. Select pull using rebase from packages->git-plus

**Comment by akonwi** [comment]
The pull rebase command was removed a few months ago in favor of the config option to always pull using rebase. I'm sorry, I forgot to remove the option from that menu.

If you don't want to use the configuration to always pull with the rebase flag, then you can setup a custom command or just use the 'Run' command when you want to do it.
