### ISSUE TITLE
[REQUEST] git tag -a 1+ major or git tag -a 1+ minor 

### ISSUE THREAD

**Issue by tesseslol** [akonwi/git-plus#624]
i want to automate the manage of git tags. 

git tag -a 1+ major = creates a tag with = current tag version +1 major
ecc...

**Comment by scippio** [comment]
+ push with --tags

**Comment by akonwi** [comment]
This seems like an ad hoc feature. Ideally, you should be able to setup a [custom command](https://github.com/akonwi/git-plus#experimental-features) with this package to accomplish that. 

You should be able to do a more thorough version of this:

``` coffeescript
gitPlus.registerCommand 'atom-text-editor', 'some-identifier:bump-major-version', ->
  gitPlus.getRepo()
  .then (repo) ->
    gitPlus.run(repo, 'describe --tags')
    .then (tag) ->
      [major, minor, patch] = tag.split('.')
      newMajorVersion = 1 + parseInt(major)
      gitPlus.run(repo, "tag -a #{newMajorVersion}.#{minor}.#{patch}")
```

You would need to create separate commands increment major, minor, and patch.

Currently, the promise returned by the `run` function doesn't resolve with the result from git. The release today will fix that, which will allow that block of code to work.
