### ISSUE TITLE
Update/Install Fails with 'No version provided'

### ISSUE THREAD

**Issue by ddreggors** [akonwi/git-plus#625]
Could not update or install git-plus v. 7.3.0 in atom on Linux (Fedora 25) the error is:

```
Installing “git-plus@7.3.0” failed.Hide output…

npm ERR! Linux 4.9.9-200.fc25.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/ddreggors/.atom/.apm/.apmrc" "--userconfig" "/home/ddreggors/.atom/.apmrc" "install" "/tmp/d-117115-16429-yzhqew/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5

npm ERR! No version provided
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117115-16429-158xqcd/npm-debug.log
```

Steps to reproduce:

1. Open Atom
2. Head to Settings -> Install if not installed or Settings -> Updates if installed
3. Search/Select git-plus
4. Click Install

I will add that looking at the package.json file I see a `"version":"7.3.0"` entry...

**Comment by akonwi** [comment]
This is odd. Have you retried to install/update it? I just uninstalled and installed it with no problem

**Comment by ddreggors** [comment]
Yes... first I was trying to update it, then uninstalled older version and
tried to just install again. It all fails with same error.

David Dreggors
dadreggors@gmail.com

**Comment by ddreggors** [comment]
Full disclosure, I even removed the 7.3.0 folder under
~/.atom/.apm/git-plus and let it re-pull the info... still has same error.

David Dreggors
dadreggors@gmail.com

**Comment by akonwi** [comment]
Do you get this error for any package you install?

I haven't seen this before and I haven't yet found any solutions to this with a couple google searches.

**Comment by ddreggors** [comment]
No only for this package... why was this closed?
Is there a solution?

**Comment by akonwi** [comment]
Oh sorry. I think I clicked the wrong button to submit. 

I'm not sure what to do. I can't reproduce it and this seems like a flukish thing because I don't see many other instances of this error around. You're also the only user of the package to open this issue so I assume this isn't occurring for most of them.

**Comment by ddreggors** [comment]
I am willing to run commands and edit files to help... I just have no idea where to start.

**Comment by ddreggors** [comment]
I also captured a verbose log of the failed install:

[git-plus-install.txt](https://github.com/akonwi/git-plus/files/780994/git-plus-install.txt)

**Comment by ddreggors** [comment]
I found this as well...
https://github.com/npm/npm/issues/7105

**Comment by ddreggors** [comment]
I found this:
https://github.com/akonwi/git-plus/issues/580


and so I tried to install v6.4.0 and sure enough....
```
[ddreggors@mobile-tek ~ ] [0]
$ apm install git-plus@6.4.0
Installing git-plus@6.4.0 to /home/ddreggors/.atom/packages ✓
[ddreggors@mobile-tek ~ ] [0]
$ 
```


I uninstalled 6.4.0 and tried the current again, still fails... but 6.4.0 will install for now

**Comment by ddreggors** [comment]
Here is the log of 6.4.0 for reference
[git-plus-6.4.0-install.txt](https://github.com/akonwi/git-plus/files/781464/git-plus-6.4.0-install.txt)

**Comment by ddreggors** [comment]
Appears to be bi-product of old environment, this system was recently upgraded.
I uninstalled atom, removed ~/.atom and re-installed atom. I can now install git-plus.


```
Installing git-plus to /home/ddreggors/.atom/packages ✓
```
