### ISSUE TITLE
[REQUEST] On git push, show messages from remote in notification

### ISSUE THREAD

**Issue by aph3rson** [akonwi/git-plus#642]
When pushing to a remote branch/repo, sometimes remote will send back messages, even on success. For example, GitLab CE will give a similar message on every push:

```
remote: 
remote: To create a merge request for feature-readme, visit:        
remote:   https://gitlab.server/user/repo/merge_requests/new?merge_request%5Bsource_branch%5D=pushed-branch        
remote: 
```

Instead of showing these in the console, perhaps these could be shown as a user notification. I'm not sure on what color the notification should be - perhaps red for failure, green for success, yellow for unknown?

**Comment by akonwi** [comment]
The notifications are typically too small to properly accommodate messages like that and for that reason, they have been put into the output view above the status bar. The notifications also disappear and the output view can be toggled by clicking the git+ logo in the statusbar
