### ISSUE TITLE
[Request] Support usage with Project Manager package

### ISSUE THREAD

**Issue by vali19th** [akonwi/git-plus#643]
If I start atom with project A, then change to project B using project-manager, git-plus doesn't recognize the project B as being a git repository. Only [this](http://oi67.tinypic.com/2cy1oo8.jpg) shows up if I open command palette and type "git plus".
Everything works as expected if project B is active when I start atom.

Steps to reproduce:

1. Close atom with project A active
2. Start atom
3. Change to project B using project-manager
4. Type "git plus" in command palette

**Comment by akonwi** [comment]
I'm sorry, I don't use project-manager and I'm not sure how it works so this won't be a priority for me. If you or someone else want to create a pull request, that would be appreciated

**Comment by vali19th** [comment]
I understand. Thank you for your response!

**Comment by vali19th** [comment]
The issue has been fixed with one of the latest updates to atom, git-plus or project-manager.
