### ISSUE TITLE
Fatal Authentication failed

### ISSUE THREAD

**Issue by kishorramanan** [akonwi/git-plus#645]
Atom Version: 1.15.0. x64
Git Version: 2.12.2.windows.2
Git Plus Version: 7.3.3

Git Path has been added to env Path
Removed credentials from Windows credential store too
Have git credential configured, a normal push / pull from the bash goes through without any issues.
But while I do via Atom getting the below error
![image](https://cloud.githubusercontent.com/assets/13584084/24819335/cef40dce-1c01-11e7-9c13-d97c7cb22f74.png)

**Comment by akonwi** [comment]
Have you looked for answers in #224 ?

**Comment by akonwi** [comment]
Closing this since it seems you found a solution in #224
