### ISSUE TITLE
Merge Error on "Already up to Date" [Bug]

### ISSUE THREAD

**Issue by ggedde** [akonwi/git-plus#647]
When merging if there is no changes then I am getting an error.
"TypeError: Path must be a string or buffer".

https://screencast.com/t/QT4SQssH
https://screencast.com/t/R5R0zwlZ

This only happens when merging branches that have no changes.
Not really a big deal, but though you should know.

MacOS 10.11
Atom: 1.15
Git-Plus: 7.3.3

**Comment by ggedde** [comment]
Actually this is happening with all merges even ones with changes.
Not quite sure why this is happening.
I do have push set default.nothing.
Also I have "Pull Before Pushing" and "Prompt for branch selection when pulling/pushing" enabled.
Thanks

**Comment by akonwi** [comment]
are you trying to merge local branches or remote branches?

**Comment by ggedde** [comment]
@akonwi Local.
I haven't noticed lately so seems to be resolved.
