### ISSUE TITLE
Git+ context menu not showing since Atom 1.17.0-beta2

### ISSUE THREAD

**Issue by yacut** [akonwi/git-plus#656]
### Description:
Prior to Atom 1.17.0-beta2 the `Git` context menu in tree-view was shown. Since that version, the option is missing.

#### Steps to reproduce:
1. Open a git project
2. Right click on a directory or a file

#### Expected behavior: 
Expect to see `Git` option

#### Actual behavior:
The `Git` option is not shown

#### Versions
1.17.0-beta2, 1.17.0-beta3, 1.17.0-beta4, 1.17-beta5

**Comment by yacut** [comment]
Same problem had the `search and replace` package. https://github.com/atom/find-and-replace/pull/889

**Comment by FlappyHeart** [comment]
@yacut this may be a bug of atom, see this https://github.com/atom/find-and-replace/issues/887

**Comment by pixilz** [comment]
@yacut the tree-view's dom has recently changed, this should probably fix it. https://github.com/akonwi/git-plus/pull/664

**Comment by yacut** [comment]
@pixilz yes, fixed. Thank you!
