### ISSUE TITLE
[QUESTION] Empty Commit Message?

### ISSUE THREAD

**Issue by darbyjack** [akonwi/git-plus#657]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172).

Did you update the package and you are seeing this message `Failed to load the git-plus package`? Run `apm install` from the package's directory and restart atom.
-----------------

[Description of issue here]
Updated to the latest update released yesterday and now when I add + commit and save the commit, it says my commit message is empty, when I clearly title it.
Steps to reproduce:

1. -- Add + Commit a file
2. -- Enter Git Commit Title
3. -- Save

**Comment by akonwi** [comment]
I can't reproduce this. Can you attach a gif or video please? Also is there anything logged related to this in the devtools?

**Comment by darbyjack** [comment]
https://glaremasters.me/i/umqs74c.gif

**Comment by akonwi** [comment]
haha that's an unexpected way to write commit messages. The latest update switched to behave more like the scissors mode for git commit [cleanup](https://git-scm.com/docs/git-commit#git-commit-scissors), meaning everything below the line with >8 gets removed. The reason for this is that it allows more flexibility in what can be included in the commit message like starting lines with the commit character and it is simpler to handle in the package than trying to strip out comments.
