### ISSUE TITLE
7.8.0 has lost git plus > add file in the Tree View

### ISSUE THREAD

**Issue by pete-hotchkiss** [akonwi/git-plus#660]
Updated to latest version of ATOM (1.17.0) and the ability to right click on a file in the tree view and add to the staged files for commit has been removed.

Steps to reproduce:

1. Open a project/folder
2. Make a change to a file
3. File file in tree view
4. Right click
5. Search high and low for the "Add File" option

**Comment by pete-hotchkiss** [comment]
PS > Running Atom 1.17.0

**Comment by H2rmone** [comment]
I have the same problem as you @pete-hotchkiss

**Comment by Klickmichel** [comment]
Same here. "Git plus" is missing in context menu since Atom 1.17.0

**Comment by pete-hotchkiss** [comment]
proving to be really problematic as it requires individual files to be added - and the 'add all' means other files need unstaging etc.

I'm guessing the peeps that be are working on it :-)

**Comment by ianvonholt** [comment]
Same problem with the upgrade to 1.17.0. 

I don't see any errors when loading in Developer Mode either.

**Comment by pixilz** [comment]
So the selector for adding the contextMenu in "git-plus/lib/context-menu.coffee" is 
`.tree-view.full-menu .file, .tree-view.full-menu .directory` 
Prior to this update that was correct, but with this recent update Atom's tree bar is nested differently in the DOM (which is interesting).

Anyway the new nesting of the tree-view looks like this:
`.tool-panel.tree-view > .full-menu.list-tree (.directory|.file)` 

(Obviously not the selector you want but just the dom structure)

**Comment by pixilz** [comment]
I believe this pull request should fix this: https://github.com/akonwi/git-plus/pull/664

**Comment by pete-hotchkiss** [comment]
nice - seems to work if I pull these changes into my local instance :+1:
