### ISSUE TITLE
actions of git plus from context menu on atom sidepanel is not working.

### ISSUE THREAD

**Issue by StanleyLiang** [akonwi/git-plus#666]
os: mac os sierra 10.12.4
atom version: 1.17.0 x64
git plus version: 7.9.1

issue description: there is no response as clicking context actions of git plus in atom side panel.
steps to reproduce: 
1. right click on a modified file in atom side panel.
2. choose any git plus actions in context menu.

**Comment by Encr1pt3d** [comment]
The same:

os: windows 64
atom version: 1.17.0 x64
git plus version: 7.9.1

issue description: there is no response as clicking context actions of git plus in atom side panel.
steps to reproduce:

right click on the top folder in atom side panel.
choose commit and do nothing, same as push.

Whereas in top meni when i click packages -> git plus it works in this top menu. But not in the side...

**Comment by avnes** [comment]
Similar problem on Linux after I upgraded to Atom 1.17.0

1. Right click on file in Atom side panel, and there is no longer any git-plus menu
2. Use menu Packages -> Git-Plus -> Add and nothing happens. Similar with Commit

os: Fedora 25
atom version: 1.17.0
git plus version: 7.9.1

**Comment by akonwi** [comment]
I'm aware of this. I'm going to try and push a fix this weekend

**Comment by akonwi** [comment]
I'm going to try and push a fix for this this weekend

**Comment by StanleyLiang** [comment]
I'm so glad it's fixed, appreciate for the instant fix.
