### ISSUE TITLE
[QUESTION] Git-plus push splitting my tree pane

### ISSUE THREAD

**Issue by jjdp** [akonwi/git-plus#669]
[Description of issue here]
Whenever i push using the git-plus package my tree view gets split
![split](https://cloud.githubusercontent.com/assets/5244520/26271756/ca3ec006-3d3c-11e7-94e0-c73cf2b287ab.png)

Steps to reproduce:

1. push to my git repo

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

using [git-plush 7.9.1](https://github.com/akonwi/git-plus)

**Comment by akonwi** [comment]
How are you pushing? Are you using the command from the one of the command palettes or a keymapping or from a context menu?

**Comment by jjdp** [comment]
from the packages context menu. i have not tried from the command palette or from a keymapping although will that make a difference?

**Comment by akonwi** [comment]
I'm currently investigating an issue with commands from the tree-view context menu not working. Are you using the tree-view context menu?

**Comment by jjdp** [comment]
it seems fine to me except for reveal/toggle tree side. i do not know what it does

**Comment by akonwi** [comment]
I don't understand what you mean. Are you invoking git-plus commands from the context menu in the tree-view? By that I mean are you right clicking on a file/folder in the tree-view and using the commands there

**Comment by jjdp** [comment]
no im using it through the menu bar -> packages -> git plus

**Comment by akonwi** [comment]
Can you share what the tree view is supposed to look like? I'm not sure what's wrong from the picture you shared originally.

**Comment by jjdp** [comment]
![split](https://cloud.githubusercontent.com/assets/5244520/26291922/8c911688-3ee4-11e7-899f-fd8b69e60f2e.png)

be default. no vertical line in the middle

**Comment by akonwi** [comment]
Oh I see now. I had no clue what the problem was but I get it now. I'm not sure what's happening with push to open a new pane like that but it may be fixed with the next update

**Comment by jjdp** [comment]
fixed on latest update
