### ISSUE TITLE
Git-plus not working after update!

### ISSUE THREAD

**Issue by gholami-mohammad** [akonwi/git-plus#670]
After updating Git-plus to **7.9.1** , it stops working.
Can not add and commit!!

**Comment by benmoot** [comment]
what is the error you are receiving?

**Comment by thecircleoflifefree** [comment]
Have you tried doing rollback to see if it fixes? What system you running?

**Comment by gholami-mohammad** [comment]
Darwin Mohammads-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by Pageboy** [comment]
Same here. Atom 1.17 and git-plus 7.91. MACos ... 10.12.5

**Comment by luisalvarado** [comment]
Yes correct. I thought I was crazy. The only thing I changed on Ubuntu was upgrading from Atom 1.16 to 1.17 and then applying the git-plus update to the latest 7.9.1 version

That's all. Before I was able to commit, add, pull, push, everything. Now nothing works. What is curious is that at the bottom it knows the changes on the remote master and it knows the changes I have done on several files.

Just in case right now am doing all git commands over the terminal while this gets fixed.

**Comment by akonwi** [comment]
@Pageboy @luisalvarado @gholami-mohammad No commands work at all? Are you invoking them from the command palette or context menus or by keymappings?

**Comment by gholami-mohammad** [comment]
Commands work from command palette but not work on context menus

**Comment by akonwi** [comment]
I just pushed an update to fix #666. This may have been the same issue

**Comment by gholami-mohammad** [comment]
Tanks. Solved for me.

**Comment by luisalvarado** [comment]
Confirmed, everything is working on the context menu. Excellent work @akonwi 
This is also confirmed by my 7 men crew of developers since updating to 7.9.2
