### ISSUE TITLE
 [QUESTION] What is the equivalent for ->  git remote -v 

### ISSUE THREAD

**Issue by thecircleoflifefree** [akonwi/git-plus#671]
Is this a question or a feature request?  **This is a question.**

Are you on a windows machine: **Yes**
 and do you have trouble pushing to remote repositories? **No**
Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers: **I already checked but do not see the specific answer.**

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312): **I dont think my issue is related to this, yet still checked and answer not there.**

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172): **No**
-----------------

[Description of issue here]

What is the equivalent in atom running git-plus for the following command: What is the equivalent for:
  **git remote -v**

**Comment by akonwi** [comment]
There is no command specifically for that.

You can run arbitrary commands like that with the `Run` command. It will open an input field where you can type `remote -v`.
