### ISSUE TITLE
[QUESTION] Probleme with git Push action

### ISSUE THREAD

**Issue by p-paul** [akonwi/git-plus#672]
Hi everybody,
I've a problem with git-plus in atom
all actions are OK but push action is KO
when i would like to push, i've this message in output of git+:
![1](https://cloud.githubusercontent.com/assets/26795401/26299488/49d4bf06-3edb-11e7-9ea1-287e777409c8.jpg)

i've disable proxy in config file
![2](https://cloud.githubusercontent.com/assets/26795401/26299489/49df2680-3edb-11e7-930a-5f87feea128e.jpg)

i've set username and email in git

When i execute git push in  a cmd window => it's ok.
So i don't understand why it's not run with git-plus.

Can you help me?
Thanks in advance.

**Comment by akonwi** [comment]
I'm not quite sure what is going on here.

Where was the proxy set? Was it in a global gitconfig or local?

**Comment by p-paul** [comment]
The only proxy setting is on my internet browser . IE and FireFox.
this is my local git configuration:
![image](https://cloud.githubusercontent.com/assets/26795401/26573219/360237a4-451d-11e7-9bab-0b077b5c736b.png)


this is my global git configuration:
![image](https://cloud.githubusercontent.com/assets/26795401/26573180/07f46e54-451d-11e7-9639-13e7a4da438a.png)
