### ISSUE TITLE
git-pus 7.9.2 "Aborting commit due to empty commit message"

### ISSUE THREAD

**Issue by raj-andy1** [akonwi/git-plus#673]
running Atom v 1.17 on Mac OS X 10.11.6
I updated the git-plus plugin to 7.8 and then all pushes to my repos started failing with the message "Aborting commit due to empty commit message"

I am not an advanced git user, but I am doing everything as it used to work (removing the comment #, and saving the message)

I also reinstalled Atom and updated to the latest git-plus 7.9.2 and still the same problem.
Help!!

Steps to reproduce:

1. Make changes to the files in the repository
2. Cmd + Shift + H to add, commit and push
3. Remove the # and save the commit message
4. Getting error.

Currently I am manually editing the file on github .com and pushing there. Unfortunately no lints/checks can be applied.

**Comment by akonwi** [comment]
Why are you removing the '#'? According to your steps you're trying to commit an empty message.

Make sure you read the instructions here
```
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
```

**Comment by raj-andy1** [comment]
Oops, thanks for the clarification. But this behavior seems to have changed only this release. Earlier release, I could remove the # and append my comment to the generated message below the dotted line.  Not sure if this changed in 7.9.2 or being enforced since 7.9.2

**Comment by akonwi** [comment]
Well in 7.9.2 I changed the way commits work to trim the commit message file like the `scissors` option in `git commit` because it is much simpler to create the commits that way. Stripping the file of comments can be done multiple ways based on whether the verbose commit option is turned on. By enforcing one way, that becomes much easier.
