### ISSUE TITLE
[REQUEST/QUESTION]

### ISSUE THREAD

**Issue by Zangoran** [akonwi/git-plus#676]
I was wondering if there was a way when committing changes with the COMMIT_EDITMSG to add a description to the commit, I only see a way to add the title. If this is not a feature, then I would like a request for this to become a feature. Thanks for your time!

**Comment by akonwi** [comment]
The first line of a commit is used as the title. New lines after that are the descriptions

**Comment by Zangoran** [comment]
Awesome thanks!
