### ISSUE TITLE
[REQUEST] Dont push all branches at once

### ISSUE THREAD

**Issue by joncodo** [akonwi/git-plus#678]
When you push, all the branches get updated on remote and not just the one you are working on.

Steps to reproduce:

1. -- Create a branch from master called test 1
2. -- Make a commit to that branch (a)
3. -- Create a branch from master called test 2
4. -- Make a commit to that branch (b)
5. -- Run the command to add + commit + push

I would expect only the current branch to be pushed but all local branches are pushed.

Some are pushed unintentionally such as a master branch that you were testing things on. I understand that I could do a better git flow here but to push all branches locally to remote is likely not the best or the intended method of the developers.

**Comment by akonwi** [comment]
I can't reproduce this. None of the commands in this package would push all branches. The only way I can see this happening is if you had some git config that was causing git push to behave like `git push --all`.

**Comment by joncodo** [comment]
If this can't be reproduced, feel free to close. :) Thank you for taking the time
