### ISSUE TITLE
Git: Init not doing anything?

### ISSUE THREAD

**Issue by xxKeefer** [akonwi/git-plus#679]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172).

Did you update the package and you are seeing this message `Failed to load the git-plus package`? Run `apm install` from the package's directory and restart atom.
-----------------

[Description of issue here]
i've just installed git-plus and i tyry to initialise with Git Init but that function just doesn't do anything in atom for me. i'm on a windows 7 machine i have no idea what i'm doing wrong. all the tutes i find do it exactly the smae way but i can't init.

Steps to reproduce:

1. --
2. --
3. --

**Comment by akonwi** [comment]
Can you share a gif or video of this?

Also open the dev tools and see if there are any errors being thrown or logged when you invoke the command.

**Comment by xxKeefer** [comment]
sorry, i'm a novice. after some elbow grease i found out what i was doing incorrectly. thank you for getting back to me.
