### ISSUE TITLE
[REQUEST] Push to the branch with the local branch name

### ISSUE THREAD

**Issue by albireox** [akonwi/git-plus#680]
When you have multiple remotes git-plus ask you to which one of them you want to push. That's ok, but then it asks you to select the branch to which you want to push. Normally, the selected branch is not the one you want to push to, but the first in alphabetic order. That is confusing and sometimes dangerous, as if you do it without paying attention you may en up pushing `master` to `origin/feature`. Instead, it would be best if the remote branch selected by default is the one that matches the name of the local branch. Ideally one would want a option in the settings to bypass the selection of a branch, and simply push by default to the remote branch with the same name as the local one.

**Comment by akonwi** [comment]
It sounds like you have the option labeled "Prompt for branch selection when pulling/pushing" turned on. If you disable it, pushing and pulling will go to the configured upstream branch

**Comment by albireox** [comment]
Yes, but in that case there is no way for me to pull/push from a certain remote, assuming I have more than one. I find very useful to be able to select the remote, but I don't think selecting a remote branch that is named differently than the local is that useful.

I realise you can checkout a remote branch with a different name, but I think at least git-plus should default to using the branch with the same name, if that exists.

**Comment by akonwi** [comment]
That setting only applies to branches. You still have to choose a remote source and then the branch is inferred for that remote.

**Comment by albireox** [comment]
You are right. I was confused or maybe this is new behaviour? In any case, that works for me. The only problem is that pulling without the  "Prompt for branch selection when pulling/pushing" won't let you choose the remote to use, it will always use the default upstream.

**Comment by akonwi** [comment]
That's true. Using multiple remotes is not something I usually do. In my experience though, it's only from the configured upstream that I want to ever pull from and just push to the other remote sources. This seems like an uncommon scenario
