### ISSUE TITLE
[QUESTION] Closing the console output using a shortcut

### ISSUE THREAD

**Issue by drorata** [akonwi/git-plus#685]
As described in [here](https://github.com/akonwi/git-plus#pushpullfetch-notifications), one can close the "console output" by clicking on the `git+`. Is it possible to close it somehow using a keyboard shortcut?

**Comment by akonwi** [comment]
The output view is in atom's dock which is an atom-core feature. There is no shortcut for toggling the dock but there is a command. If you open the atom command palette, there is a command called `Toggle bottom dock`. You can define mapping in your keymap file for `window:toggle-bottom-dock`.
