### ISSUE TITLE
Keybindings: Add All triggers inadvertently 

### ISSUE THREAD

**Issue by sjurgis** [akonwi/git-plus#688]
Latest atom, git-plus and MacOs 10.12 Sierra.
When adding a second file, using cmd+shift+a, add all will execute. Quite frustrating as I need to go back to shell and to git reset.

Also not sure if it's just my machine, but add key binding is generally slow / unresponsive :|

Steps to reproduce:

1. cmd+shift+a on a file open (sometimes notification appears, sometimes - doesn't)
2. Select next file, cmd+shift+a - Added all files notification appears.

**Comment by akonwi** [comment]
I think your problem might be related to #415. 

I think I'm going to remove the keybindings from this package, except for the menu toggle so users can create their own keybindings selectively and avoid the clashing.
