### ISSUE TITLE
Intermittent index.lock File exists errors

### ISSUE THREAD

**Issue by pdaniell** [akonwi/git-plus#693]
Intermittently, I receive a index.lock file exists error when I try to add-all-and-commit

Steps to reproduce:

1. Cmd+Shift+P to Engage the command palette
2. Choose Git Plus: Add All Commit and Push
3. See error message from git that index.lock file exists

Aftermath

When I go to the file system there is no index.lock file there. The system is left in the state where the file has been added but nothing else has been executed. This suggests that there is a race condition whereby the commit command is being issued before the add finishes and so it sees an index.lock file while I don't (because by the time i see the file system, add would have completed). Is there some way to sequentialize the commands? Maybe they are being fired off as three async processes that can execute simultaneously?

**Comment by UziTech** [comment]
This is a race condition with the [`github`](https://github.com/atom/github) package

check out the issue here: https://github.com/atom/github/issues/961

The only way I know to prevent this at the moment is to disable the `github` package

**Comment by pdaniell** [comment]
Yes disabling the github package works for me.

**Comment by BinaryMuse** [comment]
This should be fixed in Atom 1.23-beta (the next upcoming beta).
