### ISSUE TITLE
Please add a future like git-log

### ISSUE THREAD

**Issue by oknixus** [akonwi/git-plus#694]
As the titile, what about that add a future like git-log ?

**Comment by developer-lindner** [comment]
@oknixus it's already integrated?

**Comment by oknixus** [comment]
Yes. I just want her become more beautiful.
Thanks for your answer.

**Comment by developer-lindner** [comment]
@oknixus Well, then close this ticket?!

**Comment by oknixus** [comment]
@developer-lindner Ok. Thanks for your answer.
