### ISSUE TITLE
QUESTION - How to toggle the bottom panel using keyboard?

### ISSUE THREAD

**Issue by benpptung** [akonwi/git-plus#705]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

[Description of issue here]
In `linter-ui-default`, I can toggle the bottom panel using `linter-ui-default:toggle-panel`, but it seems there is no similar keyboard binding to hide the bottom panel in Git Plus?

If there is no command to hide the bottom panel, how about to add one?

**Comment by mateuspv** [comment]
You can run: `window:toggle-bottom-dock`,
There's no default keyboard binding for this, you can add your own keybindings for this on [keympap.cson](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/)
```cson
'atom-workspace':
  'ctrl-down': 'window:toggle-bottom-dock'
```

**Comment by brycefranzen** [comment]
I added this to my keymap file.  It will make it so that when the bottom dock is open and focused, you can just press escape to close it. Works wonders :)

```'atom-panel-container .atom-dock-inner.bottom':
    'escape': 'window:toggle-bottom-dock'```
