### ISSUE TITLE
Allow using URLs in terminal log

### ISSUE THREAD

**Issue by alexjurkiewicz** [akonwi/git-plus#715]
Bitbucket has this nifty feature when you push to a branch where it prompts you to create a pull request:
<img width="585" alt="screen shot 2017-11-06 at 12 37 47 pm" src="https://user-images.githubusercontent.com/379509/32421770-8d449fd4-c2ef-11e7-9172-05b227d3c073.png">
Unfortunately in git-plus I cannot copy the terminal log output and I cannot click the URL either.

Please add support for interacting with these URLs somehow! 👍

**Comment by ZyanKLee** [comment]
Similar features are built into github and gitlab as well, so this request would not only help bitbucket users.

**Comment by akonwi** [comment]
I'm currently working on an overhaul of the output view and one of the improvements is at the very least being able to copy the links. Hopefully I can publish the changes this week with click support too.

**Comment by akonwi** [comment]
Just published v8.1.0 that fixes this. Read more [here](https://github.com/akonwi/git-plus/blob/master/CHANGELOG.md#810)
