### ISSUE TITLE
[REQUEST] decaffeinate to js

### ISSUE THREAD

**Issue by yubaoquan** [akonwi/git-plus#724]
I was writing a feature to this package of revert, but got an error after adding new coffee files. And I was not good at coffeescript. So could you please decaffeinate this package to js?

**Comment by akonwi** [comment]
atom understands vanilla javascript and coffeescript. You can write the new files in js.

There's a lot to be done to decaffeinate here. A lot of the syntactic sugar and readability for views written with space-pen-views would be lost. Almost everything else can be re-written. I already started the process a while ago with some files but it's not something I think is valuable enough to do all at once.
