### ISSUE TITLE
[QUESTION] Support for commit --amend?

### ISSUE THREAD

**Issue by orschiro** [akonwi/git-plus#727]
Hi all, 

Great plugin, thanks so much!

I am not very experienced with Git but is it possible to provide a command for the command palette to amend a commit?

Thanks!

**Comment by giatrakosg** [comment]
Hi ,
 when I search in the command palette "amend" there seems to be the option to  amend the last commit .And by running git log in the terminal , the changes are saved. Maybe you have an outdated version of atom ?

**Comment by orschiro** [comment]
@giatrakosg you're right, thanks! Not sure why and how I missed it in the first place. 

Sorry for the noise.

![screenshot from 2018-02-24 10-17-11](https://user-images.githubusercontent.com/170947/36628020-f3bc2ff4-194b-11e8-97c0-469ca3365e02.png)
