### ISSUE TITLE
Git Clone... The most usefull tool is'nt available.

### ISSUE THREAD

**Issue by HorselessName** [akonwi/git-plus#730]
I downloaded the package just to test it if there was a clone option...
It's very annoying to have to download manually from Git and then use Atom for Pushes and Commits...
What if i could use Atom to do everything ?

That would be awesome

**Comment by jevo** [comment]
You can clone repos by using **Git Plus:Run** .
You have to paste the following command into the input field and press Return.
This command is:
`clone ssh://username@server.com/repoName` 
I'm using cloning in this way and it works fine.

**Comment by HorselessName** [comment]
Thanks, issue solved.
@jevo Working like a charm
