### ISSUE TITLE
[QUESTION] Git Commit Amend Keybinding

### ISSUE THREAD

**Issue by brunodahora** [akonwi/git-plus#741]
Hello!

I would like to add a git commit amend shortcut, but need to know what is the key to this command.
Can you share with me?

[]s

**Comment by Fryuni** [comment]
Just bind your shortcut to the `git-plus:commit-amend` command

Like so:
```
'atom-workspace':
  'ctrl-shift-e': 'git-plus:commit-amend'
```

**Comment by brunodahora** [comment]
Thank you very much!

**Comment by akonwi** [comment]
@brunodahora for the record, there's mention of this in the `Commands` section of the [README](https://github.com/akonwi/git-plus#commands)
