### ISSUE TITLE
amend commit does not appear to work now - 

### ISSUE THREAD

**Issue by jontyD** [akonwi/git-plus#742]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172).

Did you update the package and you are seeing this message `Failed to load the git-plus package`? Run `apm install` from the package's directory and restart atom.
-----------------

In  git plus palette, at the bottom, in the list of commits you can right click and get a small menu - for the latest commit there is a link to 'Amend' clicking this does nothing and no error appears in the console.
In previous versions you could  amend a commit
atom version: 1.27.1
git-plus version: 7.10.2

Steps to reproduce:

1. -- in list of commits right click on top commit
2. -- menu appears
3. -- in top of this menu select 'Amend'

**Comment by jontyD** [comment]
I have now spotted that what it does do is copy the existing commit as a new commit, not quite what I was expecting,(ps OS is ubuntu 18.04)

**Comment by akonwi** [comment]
What you're describing is from the core `github` package. In order to amend with git-plus, you need to select the command from the command palette (via ctrl-shift-p or ctrl-shift-h).
