### ISSUE TITLE
[QUESTION] ShortCut Keys aren't working (CMD+Shft+A Q) and git add all commit push (CMD+shft+A P) 

### ISSUE THREAD

**Issue by shdobxr** [akonwi/git-plus#750]
[QUESTION] 
-----------------

ShortCut Keys for Git add commit push (CMD+Shft+A Q) and git add all commit push (CMD+shft+A P) 

Steps to reproduce:

No worky:
1. Fresh install of ATOM + git-plus being the only additional package

Worky:
1. Installing the now deprecated git-plus-plus actually adds the hotkey functionality

**Comment by akonwi** [comment]
the changelog has a note about that change https://github.com/akonwi/git-plus/blob/master/CHANGELOG.md

**Comment by shdobxr** [comment]
Thanks @akonwi
