### ISSUE TITLE
Shortcuts don't work for new Git-Plus 8.0.0 version

### ISSUE THREAD

**Issue by vikeinstein** [akonwi/git-plus#751]
I enjoy using the Git-Plus package with Atom and I've been accustomed to using short-cuts for adding and committing on Mac and Linux machines. However, I recently updated my Git-Plus to version 8.0.0 and my Atom to 1.28.2.

Ever since I did this, these short cuts don't work again. I now have to manually choose the Add and Commit feature from Git-Plus's drop-down menu. I would like to be able to use the shorts-cuts since they make me work more efficiently. 

Is it possible for the developer to have a look at this? Thank you.

**Comment by akonwi** [comment]
the changelog has a note about that change https://github.com/akonwi/git-plus/blob/master/CHANGELOG.md
