### ISSUE TITLE
git plus keymappings are wiped out after upgrade to atom 1.29

### ISSUE THREAD

**Issue by devopsprosiva** [akonwi/git-plus#752]
I upgraded atom to 1.29. Since then none of the git plus keymappings work. I can run gitplus from the command palette and context menu but not the keymappings.

Atom version: 1.29
Git plus version: 8.0.0

**Comment by tomreeb** [comment]
+1

**Comment by ebalsumgo** [comment]
Yep none of the keybindings work, an even the git plus palette is not coming up

**Comment by akonwi** [comment]
see my comment in #751
