### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toggle' of null

### ISSUE THREAD

**Issue by dakinfosystems** [akonwi/git-plus#755]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 8.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toggle' of null

```
At /Users/pramod/.atom/packages/git-plus/lib/git-plus.js:602

TypeError: Cannot read property 'toggle' of null
    at HTMLAnchorElement.link.onclick (/packages/git-plus/lib/git-plus.js:602:32)
```

### Commands

```
 10x -9:31.5.0 core:backspace (input.hidden-input)
     -3:39.8.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:34.4.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:31.9.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:22.5.0 core:backspace (input.hidden-input)
     -1:44.7.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -1:37.5.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:17.3.0 application:add-project-folder (atom-pane.pane.active)
     -0:26.1.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
git-plus 8.1.0 
```

**Comment by akonwi** [comment]
Your window might be in a weird state. Can you close the window and launch atom for the same projects in that window from the command line and add the `clear-window-state` flag?

**Comment by deesto** [comment]
> Same here, same Atom&Mac version. Using `--clear-window-state` has no effect.

+1: Completely empty editor, newly opened project folder in tab, clicked 'git+' to open pane, got the same TypeError. I have also just upgraded Atom from 1.29 to 1.30; I didn't see this in 1.29.

**Comment by Tekwriter1221** [comment]
Same.+1: Completely empty editor, newly opened project folder in tab, clicked 'git+' to open pane, got the same TypeError.

**Comment by tadajiutaerjiudoushitajiu** [comment]
Can no one give a solution?

**Comment by tadajiutaerjiudoushitajiu** [comment]
I may have found one of the reasons.Try to display only one item (folder) on the left side to ensure that the'.git'file is the first in this directory.
![image](https://user-images.githubusercontent.com/32866231/45859562-8ee5c600-bd95-11e8-8386-57702726af0a.png)

**Comment by sofkaski** [comment]
I just installed a fresh atom 1.31.1 and this package 8.1.0 and there I have the same error.  I have an other environment with atom 1.26.1 and 8.1.0 and there the toggle works just fine. So, base atom version has an impact?

**Comment by sofkaski** [comment]
Further note: I downgraded atom to 1.29.0 and the error is there still.

**Comment by fabregas4you** [comment]
Same +1 , But @tadajiutaerjiudoushitajiu 's said true for me. Check your .git !

**Comment by rzjnzk** [comment]
I received the error immediately after clicking 'Toggle Git-Plus Output'.
.
**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package 8.1.0


### Stack Trace

Uncaught TypeError: Cannot read property 'toggle' of null

```
At E:\d\User\Software Projects\#atom\.atom\packages\git-plus\lib\git-plus.js:602

TypeError: Cannot read property 'toggle' of null
    at HTMLAnchorElement.link.onclick (/packages/git-plus/lib/git-plus.js:602:32)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-discord 2.0.1 
atom-rzjnzk-syntax 0.0.0 
auto-indent 0.5.0 
autocomplete-paths 2.12.2 
better-git-blame 0.4.7 
busy-signal 1.4.3 
close-unmodified-tabs 1.0.4 
emmet 2.4.3 
file-icons 2.1.26 
git-blame 1.7.0 
git-plus 8.1.0 
git-time-machine 2.1.0 
github-user-datatip 0.3.2 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
move-fast 0.0.1 
node-debugger 1.10.1 
node-requirer 0.1.12 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
project-manager 3.3.6 
sourcefetch-stackoverflow 0.5.0 
swackets 0.35.0 
teletype 0.13.3 
template-generator 0.16.0 
todo-show 2.3.2 
zentabs 0.8.9 
```
