### ISSUE TITLE
Package slowing Atom down

### ISSUE THREAD

**Issue by jordyvandomselaar** [akonwi/git-plus#765]
This package adds a conciderable load on Atom at boot time: 
![image](https://user-images.githubusercontent.com/12712484/46261493-8d826f00-c4f4-11e8-8bd9-63d2eee9eebb.png)

Is there anything that can be done about this? I really like this package, but Atom really slows down after a while.

**Comment by akonwi** [comment]
Can you reload atom 5-10 times and get an average of the activation times? It really shouldn't take that long. I see about 12ms.

**Comment by jordyvandomselaar** [comment]
Hey @akonwi ,

I've stopped using Atom as an IDE, opting for Phpstorm instead.

Thanks for your reply though, I'll close this issue =)

**Comment by robhicks** [comment]
I'm running Atom 1.39.0-beta3 x64 on a MacBook Pro (2016) with Mojave 10.14.5. 
My average start time of git-plus (over 5 reloads) is 435ms.

**Comment by akonwi** [comment]
@robhicks That's odd. Is this a recent development? How many projects are in the window, if any? Have you tried it with stable Atom to see if it's similar behavior?

**Comment by robhicks** [comment]
@akonwi I usually run each project in a separate Atom window. I just tried loading projects in the same window and git-plus loads in about 10ms. 
I tried the latest version of the stable branch with basically the same results. 
So, it looks like Atom will be faster if I don't use separate windows for each project.

**Comment by akonwi** [comment]
Those are interesting results. I wonder if the big numbers you saw were a bit flukey because I usually have at least 3 windows with multiple projects in them and the load times I see are consistent.
