### ISSUE TITLE
Cmd+C doesn't work in 8.2.0

### ISSUE THREAD

**Issue by oltodo** [akonwi/git-plus#770]
Hi, since I've been updating this package to the 8.2.0 version, using the copy shortcut (Cmd+C) sets an empty value to the clipboard.

Rollbacking to the 8.1.0 solved the problem:

```shell
$ apm install git-plus@8.1.0
```

**Comment by andyhofman** [comment]
Same here!

**Comment by nuxsmin** [comment]
Just commenting out from line 60 to 62 within https://github.com/akonwi/git-plus/blob/e3f77dfda770c5f5e06f1574c9722988e1995b39/lib/views/output-view/Root.tsx#L60 does the trick

Not sure about side behaviors...

**Comment by bonovski** [comment]
I rolled back to 8.1.0

**Comment by dorianfm** [comment]
+1 and to add to this, in the key binding resolver git-plus:copy is given priority over core:copy , breaking copy on OS X versions: 

![screen shot 2018-12-10 at 12 30 57](https://user-images.githubusercontent.com/274287/49732736-78098e00-fc77-11e8-8e32-c67cb9afc438.png)

**Comment by meventi-stephan** [comment]
Cmd+V doesn't also work. Made also a rollback to 8.1.0.

**Comment by oltodo** [comment]
Cmd+V should work fine according you have something in your clipboard

**Comment by akonwi** [comment]
whoa. sorry guys! I'll push a patch ASAP

**Comment by akonwi** [comment]
8.2.1 published

**Comment by chrisgo** [comment]
Thanks!  My patch was to add this to the end of keymap.cson (Menu: Atom > Keymap)

```
...
'atom-workspace':
  'cmd-c': 'core:copy'
  
'atom-text-editor':
  'cmd-c': 'core:copy'
```
