### ISSUE TITLE
[QUESTION] Command+C does not work

### ISSUE THREAD

**Issue by hao-xue** [akonwi/git-plus#771]
Hi, I wanted to use command+c to copy, but it doesn't work in Atom. 
Command+v and command+x works though. In my keybindings, "cmd-c  core:copy" is set already. Is there a way to fix this?
I'm on macOS Mojave 10.14.1, git-plus 8.2.0.

**Comment by Bjoernsen** [comment]
I have the same issue. I updated git-plus a few minutes ago. Now, I am not able to use ctrl + c to copy anymore.

![image](https://user-images.githubusercontent.com/4971650/49736400-536ae180-fc8a-11e8-9f7f-02dcbbaa9d1b.png)

**Comment by followthemadhat** [comment]
+1
seems like the latest version (8.2.0) breaks copy/paste functionality in the core editor
disabling the plugin solves the problem.

**Comment by akonwi** [comment]
8.2.1 published
