### ISSUE TITLE
[REQUEST]  BranchMenuView in staus-bar to select a branch

### ISSUE THREAD

**Issue by fubian** [akonwi/git-plus#774]
**Description of issue:**
In the `status-bar` of Atom the current branch is mentioned. With active _github_ package I can click on this button and select another branch I would like to checkout. With _git-plus_ only (without the core package _github_) it is not possible to checkout another branch in this way.

I would suggest to implement such a similar tooltip menu like the `BranchMenuView` in the core package _github_:
<img width="394" alt="31972638-76361c78-b8d6-11e7-92c2-b637bf16d81d" src="https://user-images.githubusercontent.com/10707291/50294434-30a0b000-0476-11e9-9f4a-092c58654e8a.png">

**Comment by akonwi** [comment]
Until about July, clicking on the branch was the equivalent of the `git-plus:checkout` command but I removed it since the github package was doing the same thing. It does make sense to re-enable the feature though.

**Comment by fubian** [comment]
Thanks! I would like it very much, because I do not use github and therefore I deactivated the core package...

**Comment by compiutitvchky-gam** [comment]
+ò-

**Comment by akonwi** [comment]
Fixed in the 8.3.0
