### ISSUE TITLE
[BUG?] user.email is overlapping commit messages of git log panel

### ISSUE THREAD

**Issue by clueo8** [akonwi/git-plus#778]
Within the git panel log on the right of the screen, the bottom has a log of all the commits...

I'm noticing that my email from the user.email variable is overlapping each and every commit message, saying:
email@whatever.com's
No matter how large I resize the window, it's always overlapping the message for every commit message.

I'm on Atom 1.32.2 and gitplus 8.4.2 on a Pixelbook using Crostini (Linux), which behind the scenes is using:

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch

**Comment by akonwi** [comment]
Do you mind sharing a screenshot? The pane you are describing sounds like the one provided by the [github package](https://atom.io/packages/github).

**Comment by clueo8** [comment]
I just got home and went to take the screen shot and it's no longer an issue... I tried rebooting, but it still looks good... False alarm I guess?  Thanks for the prompt reply.
