### ISSUE TITLE
[REQUEST] gitmoji support

### ISSUE THREAD

**Issue by xgdgsc** [akonwi/git-plus#780]
Curretly in Git log I see a list containing gitmoji weird like this:

![deepinscreenshot_select-area_20190131102719](https://user-images.githubusercontent.com/1189869/52026443-d568df80-2542-11e9-8e1a-70997ad24608.png)

Only the first one I commited through git-plus. Others are committed in other ways.

Comparing to this (I don' t know exactly which plugin it is from, maybe the atom builtin?), it shows all gitmojis from the same repo correctly.

![deepinscreenshot_select-area_20190131102915](https://user-images.githubusercontent.com/1189869/52026513-14973080-2543-11e9-940b-20cdf4d3f7ce.png)

**Comment by akonwi** [comment]
Yea that panel is the built in github package. I'll look into this. It should be straightforward

**Comment by akonwi** [comment]
Released in v8.5.0
