### ISSUE TITLE
Disconnected remote

### ISSUE THREAD

**Issue by RyanWinstead** [akonwi/git-plus#782]
Is this a question or a feature request? If so please start the title with [QUESTION] or [REQUEST].

Are you on a windows machine and do you have trouble pushing to remote repositories? Check out [this thread](https://github.com/akonwi/git-plus/issues/224) first because it probably has the solution and answers.

Are you having problems using submodules in atom with this package? Check out [this thread](https://github.com/akonwi/git-plus/issues/312).

Are you running MacOs 10.12 Sierra and having issues pulling/pushing? Check out [this comment](https://github.com/akonwi/git-plus/issues/575#issuecomment-269336172).

Did you update the package and you are seeing this message `Failed to load the git-plus package`? Run `apm install` from the package's directory and restart atom.
-----------------

[Description of issue here]
As soon as I installed the update, I immediately got the Not on Branch notification. Tried deleting the project locally and re-cloning to my computer and still not connected. I dont know much about git and it took me a whole week to finally connect my repo to atom and it was working before this update so im a little irritated.  
Steps to reproduce:

1. --
2. --
3. --

**Comment by akonwi** [comment]
I'm not sure what you mean by "connect". If you have the repo cloned, once you open it in atom, the features of this plugin should be available. What's the "Not on Branch" notification you're referring to? Can you share a screenshot?

**Comment by RyanWinstead** [comment]
I’m sorry I’m just a git noob. It was my fault. What I did was undo all my recent commits which dissconnected it from the branch I was in. Idk how this works but pretty sure it wasn’t git-plus that was the problem. Thanks for fast reply though!


Sent from Yahoo Mail for iPhone


On Tuesday, February 12, 2019, 4:20 PM, Akonwi Ngoh <notifications@github.com> wrote:


I'm not sure what you mean by "connect". If you have the repo cloned, once you open it in atom, the features of this plugin should be available. What's the "Not on Branch" notification you're referring to? Can you share a screenshot?

**Comment by akonwi** [comment]
Gotcha. I'm glad you got it sorted out!
