### ISSUE TITLE
"Diff branch files" no longer appears in the context menu

### ISSUE THREAD

**Issue by SRGDamia1** [akonwi/git-plus#783]
Using atom on Windows 7.  Regardless of what file I click on, I never get the "Diff Against Branch" context menu option.   In "context-menu.ts" ts looks like that option should still be available for all files, but I'm not getting it anymore.

**Comment by akonwi** [comment]
Yea I'm not seeing it on mac as well. This seems like an issue with atom since there weren't any changes here related to it. I'll investigate

**Comment by SRGDamia1** [comment]
Thank you!
