### ISSUE TITLE
Uncaught TypeError: (intermediate value).getName is not a function

### ISSUE THREAD

**Issue by boule46** [akonwi/git-plus#784]
Since the last update I have this error when I want to add all and commit (ctrl+shift+H). If I uninstall git plus and reinstall it disappear, but when I restart the computer it reappears. When I click on Git(), I can stage all and commit.

It's used on a windows machine, all packages are up to date.
Before last update, it was doing fine.

**Comment by akonwi** [comment]
That's odd. I'm not exactly sure what the cause of this is. I've just published an update (v8.6.2) that may resolve your issue. Let me know if it does.

**Comment by boule46** [comment]
Yes, It was weird, but it's fixed with the update. Super!

Le lun. 18 mars 2019 à 14:44, Akonwi Ngoh <notifications@github.com> a
écrit :
