### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by linjialiang** [akonwi/git-plus#786]
![图片](https://user-images.githubusercontent.com/8848263/54500663-f3a36700-4959-11e9-8b79-323b5f7c3941.png)

**Comment by akonwi** [comment]
Perhaps it is. What are the actions you're taking when that error occurs? I assume you don't see the current branches of the repositories in your tree-view next to the root directory either.

**Comment by linjialiang** [comment]
> The version library displays normally

![图片](https://user-images.githubusercontent.com/8848263/54573822-cffb2200-4a28-11e9-8380-000105dc1844.png)

> my packages

~~~shell
Community Packages (47) C:\Users\linji\.atom\packages
├── atom-beautify@0.33.4
├── atom-ide-datatip@0.8.1
├── atom-ide-definitions@0.2.0
├── atom-ide-markdown-service@1.1.0
├── atom-ide-signature-help@0.4.0
├── atom-material-syntax@1.0.8
├── atom-ternjs@0.19.1
├── autoprefixer@3.7.1
├── busy-signal@2.0.1
├── color-picker@2.3.0
├── docblockr@0.13.7
├── emmet@2.4.3
├── ex-mode@0.18.0
├── file-header@1.13.9
├── file-icons@2.1.31
├── git-plus@8.6.2
├── git-time-machine@2.1.0
├── highlight-selected@0.15.0
├── ide-php@0.7.18
├── intentions@1.1.5
├── language-ini@1.20.0
├── language-nginx@0.8.0
├── linter@2.3.0
├── linter-jshint@3.1.15
├── linter-ui-default@1.7.1
├── markdown-preview-enhanced@0.15.10
├── merge-conflicts@1.4.5
├── minimap@4.29.9
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── notepad-plus-plus-syntax@0.2.11
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── platformio-ide-terminal@2.9.1
├── project-manager@3.3.6
├── regex-railroad-diagram@0.19.4
├── relative-numbers@0.9.0
├── remote-ftp@2.2.2
├── split-diff@1.6.0
├── sync-settings@0.8.6
├── tree-view-git-status@1.5.2
└── vim-mode-plus@1.36.0
~~~

**Comment by ashthespy** [comment]
Have the same issue, in my case it occurs with both git and non git repos (Win10 box)
https://github.com/akonwi/git-plus/blob/86422efa4ddb2273d6c63faaa4dbc3c91cb283ec/lib/views/tree-view-branches.ts#L45 
`treeView.entryForPath` seems to return null, although the path is valid.

Seems like an upstream issue with `entryForPath`  in [`atom/tree-view`](https://github.com/atom/tree-view/)?


Moreover, similar to #781

I have a JSON parsing error:
```
Error parsing source map SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at retrieveSourceMap (<embedded>:11:150010)
    at mapSourcePosition (<embedded>:11:276207)
    at wrapCallSite (<embedded>:11:277637)
    at <embedded>:11:278414
    at Array.map (<anonymous>)
    at prepareStackTrace (<embedded>:11:278380)
    at Function.prepareStackTraceWithRawStackAssignment (<embedded>:11:150270)
```

**Comment by akonwi** [comment]
@ashthespy I've added a check to catch that `null` in the odd case where it happens. Do you mind opening an issue in the tree-view repo since you can provide more info about the circumstances?

I'm clueless about the parsing error but it shouldn't be an issue now.
