### ISSUE TITLE
Unable to create... '.git/index.lock': File exists

### ISSUE THREAD

**Issue by sergeyfilimonov** [akonwi/git-plus#793]
When I do `add-all-commit-and-push` in Atom on Mac, I always see en error about `.git/index.lock` file:

```shell
fatal: Unable to create '.../.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**What I have tried to fix the issue and what didn't work**:
- I uninstalled a standard Git package from Atom
- Uninstalled and installed git-plus
- Reset Atom
- Ran `rm -f .git/index.lock`, the error goes away but it creates lots of panes like here https://github.com/akonwi/git-plus/issues/792 and returns on the second attempt of `add-all-commit-and-push`

**My system**:
- Atom: 1.37.0
- git-plus 8.6.3
- macOS Mojave 10.14.3

**Comment by akonwi** [comment]
Do you have another app or git client running at the same time?

**Comment by sergeyfilimonov** [comment]
@akonwi no, I use only Atom. At first, I thought this is because I use multiple projects in one window. But with one window per one project I experience the same issue.
