### ISSUE TITLE
Git push doesn't work

### ISSUE THREAD

**Issue by felixangell** [akonwi/git-plus#85]
See gif :memo:
![error](https://cloud.githubusercontent.com/assets/6254332/3560339/13fb7cf6-0966-11e4-879b-14e0b30bd092.gif)

**Comment by sundaze** [comment]
Hello there. can you please just tell me/us which setting that exactly was or what you exactly did?! Perhaps that could help me aswell... :-)

Thanx in advance

**Comment by felixangell** [comment]
Yikes, not sure why I didn't write down my exact steps I took to fix this. Apologies, but I have no idea what I did :s

**Comment by dshuvar** [comment]
Hi @felixangell @sunbloat @akonwi 

Its very strange on windows git+ don't works correct if you try push\pull over ssh 
([git for windows](https://git-scm.com/download/win) works for me I checked it). 
But if you do **step 1.** change `.git/config` in your repo from ssh to https git+
for example:
from
```
[remote "origin"]
	url = git@gitlab.com:myawesomeorg/www.git

```
to
```
[remote "origin"]
	url = https://gitlab.com/myawesomeorg/www.git
```
And do **step 2.** install [git credentials store](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases) 
And may be do **step 3.** before that I added record about git in windows environment, its can be important.
After this steps - pull\push from git-plus works for me.

**Comment by qimuxi1990** [comment]
Thank you @dshuvar . Your solution works for me.
It is an HTTPs auth. Instead of using ssh keys + passphase, it uses username and password.
Hope some day we can figure out an ssh solution.
