### ISSUE TITLE
Git Diff All on Commit

### ISSUE THREAD

**Issue by Zren** [akonwi/git-plus#90]
Having a diff all underneath the commit message is one thing I liked about SublimeText's Git.

I added this https://github.com/Zren/git-plus/commit/4cd94dff7f418baf3b3db9ffd18f3257ea1bc806 to open and focus on the diff all. Which allows the you to scroll down, then Ctrl+W to close it, and jump right to the commit message.

Could probably make this configurable if you go my route instead of combining the two like in SublimeText.

**Comment by jeepkd** [comment]
+1

**Comment by r-darwish** [comment]
+1

**Comment by BluePhoenix** [comment]
+1 This would be helpful, as I like double checking what gets committed.

**Comment by akonwi** [comment]
It turns out the git-language package syntax highlighting for the commit message supports the `--verbose` version of commits. I simply added diffs to the commit message and it worked. I'm pushing a new version with the setting turned off by default so take a look

**Comment by akonwi** [comment]
Don't take a look haha I need to comment out the diffs when actually making the commit

**Comment by akonwi** [comment]
So it seems as if the `--cleanup=scissors` flag doesn't work if we pass in the path to the file through the `--file` flag. Though the cleanup can be done manually, I'm less thrilled about doing it that way. but that may the path I take

**Comment by akonwi** [comment]
If anyone would like to take a clone of the branch called '90' and test this feature, that'd be great. I'd like to make sure it works on someone else's machine as well

**Comment by tonibirrer** [comment]
Does this now work? 

I've spotted this in the preferences, but it doesn't seem to have an effect.
![image](https://cloud.githubusercontent.com/assets/1073572/15185471/a44c16c4-1799-11e6-84d2-d90760ecf40b.png)

**Comment by akonwi** [comment]
@tonibirrer This does not work yet. I'm not sure why that option is still around. It's also appearing for me though.

The first implementation had issues so I yanked it. I'll look at bringing it back

**Comment by akonwi** [comment]
I've update the branch called 90. I won't publish this until a few others try it out

**Comment by akonwi** [comment]
This is now hidden behind a toggle for experimental features which I pushed in the latest update.

**Comment by tonibirrer** [comment]
Very cool, it works now. Thanks!

**Comment by TrevorBurnham** [comment]
@akonwi I'm very happy to see this! The syntax used for rendering the diff isn't ideal, though.

Here's how the diff looks for me when I do a commit via Git Plus:

![image](https://cloud.githubusercontent.com/assets/224895/16395590/b48a9aa6-3c88-11e6-83bc-2a4c9fbdbe30.png)

And here's the same diff when I run `git commit` from the command line:

![image](https://cloud.githubusercontent.com/assets/224895/16395692/3dede7f8-3c89-11e6-9abf-eef2c18fe3e3.png)

The difference is that, by default, Atom renders the diff part of a `COMMIT_EDITMSG` file with the `diff` syntax language (which I've applied custom styles to). I'd like to see Git Plus render the file the same way.

**Comment by akonwi** [comment]
@TrevorBurnham do you have the "Word diff" setting toggled on in the package settings? That setting will also be applied to the diff for the commit

**Comment by TrevorBurnham** [comment]
Aha! Turning off "Word diff" fixed that problem for me, and I can now customize the syntax styles to get what I want.

**Comment by akonwi** [comment]
Closing this since it's been a feature for a while now

**Comment by twang2218** [comment]
I run into this issue today, thanks Git-Plus provides `Word diff` toggle for it, it really helpful. And I do think this `word diff` should turned off by default.

<img width="531" alt="2017-01-11 11 14 35" src="https://cloud.githubusercontent.com/assets/6299096/21830209/3b02def2-d7ef-11e6-988d-6651af586780.png">
