### ISSUE TITLE
Git Add individual hunks.

### ISSUE THREAD

**Issue by EdShaw** [akonwi/git-plus#92]
We can see the status of individual lines. It would be nice if we were able to individually add hunks.

AFAIK, git cli does NOT provide a non-interactive way of doing this, making this a tad awkward. 

This could integrate with the context-menu. If you right click on a changed line, the option to add that entire hunk could be available.

**Comment by cbenz** [comment]
And I would be glad to consider staging selected lines too. This is more precise than a hunk. Like in git-gui for ex.

**Comment by keithamus** [comment]
I'm going to throw in my 2¢ and say that having a "Stage Hunk under cursor" command would be awesome - so if I type a line of code I can immediately stage that line while still editing the file.

**Comment by akonwi** [comment]
Closing this so #388 can be the official issue for "staging hunks by line" or "from within the file"
