### ISSUE TITLE
Git push and pull doesn't work

### ISSUE THREAD

**Issue by edlongman** [akonwi/git-plus#99]
git push and pull doesn't work.
I think this is because I have a passphrse for my ssh key,
it creates a black bar below the status bar like so:
![git-plus-bug](https://cloud.githubusercontent.com/assets/693456/4031799/88bab864-2c6a-11e4-99e9-db09ac307f81.png)
I've tried looking into it but I struggle to debug coffee script, as far as I can see though it's a problem with the git.cmd part

**Comment by astnerweb** [comment]
Do anyone have a solution to this? 
I can do git status but not pull or push. Very frustrating
